/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, December 27, 2016 at 4:40:50 PM Japan Standard Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /usr/lib/libnfshared.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libobjc.A.dylib/NFAWDEventProtocol.h>

@class AWDNFCVASTransactionExceptionEvent, NSString;

@interface NFAWDVASTransactionException : NSObject <NFAWDEventProtocol> {

	unsigned _type;
	unsigned _swStatus;
	AWDNFCVASTransactionExceptionEvent* _metric;

}

@property (assign,nonatomic) unsigned type;                                            //@synthesize type=_type - In the implementation block
@property (assign,nonatomic) unsigned swStatus;                                        //@synthesize swStatus=_swStatus - In the implementation block
@property (nonatomic,retain) AWDNFCVASTransactionExceptionEvent * metric;              //@synthesize metric=_metric - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)init;
-(void)dealloc;
-(void)setType:(unsigned)arg1 ;
-(unsigned)type;
-(void)setSwStatus:(unsigned)arg1 ;
-(unsigned)swStatus;
-(unsigned)getMetricId;
-(id)getMetric;
-(void)updateExceptionUUID:(id)arg1 ;
-(void)setMetric:(AWDNFCVASTransactionExceptionEvent *)arg1 ;
-(AWDNFCVASTransactionExceptionEvent *)metric;
@end

