/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, December 27, 2016 at 4:40:50 PM Japan Standard Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /usr/lib/libnfshared.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol NFClientAppStateObserverDelegate;
@class BKSApplicationStateMonitor, NSMutableSet, NSMutableDictionary;

@interface NFClientAppStateObserver : NSObject {

	id<NFClientAppStateObserverDelegate> _delegate;
	BKSApplicationStateMonitor* _monitor;
	NSMutableSet* _connections;
	NSMutableDictionary* _bundleIdMap;
	BOOL _willSleep;

}

@property (readonly) BOOL willSleep;              //@synthesize willSleep=_willSleep - In the implementation block
-(void)dealloc;
-(id)initWithDelegate:(id)arg1 ;
-(void)_applicationStateChanged:(id)arg1 ;
-(BOOL)willSleep;
-(id)_lookupClientBundleId:(id)arg1 ;
-(void)registerForStateChangesToConnection:(id)arg1 ;
-(void)unregisterForStateChangesToConnection:(id)arg1 ;
-(BOOL)isClientSuspended:(id)arg1 ;
@end

