/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, December 27, 2016 at 4:40:50 PM Japan Standard Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /usr/lib/libnfshared.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface NFCurrency : NSObject
+(unsigned long long)decodeBCDAmount:(id)arg1 ;
+(id)encodeBCDAmount:(unsigned long long)arg1 ;
+(id)getCurrencyStringCodeFromNumericCode:(unsigned)arg1 ;
+(int)getFractionDigitsFromCurrencyStringCode:(id)arg1 ;
@end

