/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, December 27, 2016 at 5:08:19 PM Japan Standard Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /Applications/Maps.app/PlugIns/MapsWidget.appex/MapsWidget
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MapsWidget/RidesharingApplication.h>

@class NSString, NSArray;

@interface _RidesSimulatedApplication : NSObject <RidesharingApplication> {

	NSString* _name;
	NSString* _identifier;
	NSArray* _choices;

}

@property (nonatomic,readonly) NSString * identifier;                      //@synthesize identifier=_identifier - In the implementation block
@property (nonatomic,readonly) NSArray * choices;                          //@synthesize choices=_choices - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (nonatomic,readonly) NSString * name;                            //@synthesize name=_name - In the implementation block
@property (getter=isEnabled,nonatomic,readonly) BOOL enabled; 
+(id)simulatedOverApp;
+(id)simulatedRydeApp;
-(id)iconWithFormat:(int)arg1 ;
-(id)imageForINImage:(id)arg1 ;
-(id)initWithIdentifier:(id)arg1 name:(id)arg2 icon:(id)arg3 choices:(id)arg4 ;
-(NSString *)name;
-(NSString *)identifier;
-(BOOL)isEnabled;
-(NSArray *)choices;
@end

