/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, December 27, 2016 at 5:08:19 PM Japan Standard Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /Applications/Maps.app/PlugIns/MapsWidget.appex/MapsWidget
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MapsWidget/RidesharingAppChoicesProvider.h>

@protocol RidesharingRideChoice;
@class NSMapTable, CLPlacemark, RidesharingFailure, _RidesSimulatedApplication, NSString, NSArray;

@interface _RidesharingRideChoicesSimulatedDataSource : NSObject <RidesharingAppChoicesProvider> {

	NSMapTable* _observers;
	BOOL _loading;
	CLPlacemark* _origin;
	CLPlacemark* _destination;
	id<RidesharingRideChoice> _selectedChoice;
	RidesharingFailure* _failure;
	_RidesSimulatedApplication* _application;

}

@property (nonatomic,retain) _RidesSimulatedApplication * application;                //@synthesize application=_application - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (nonatomic,readonly) CLPlacemark * origin;                                  //@synthesize origin=_origin - In the implementation block
@property (nonatomic,readonly) CLPlacemark * destination;                             //@synthesize destination=_destination - In the implementation block
@property (getter=isLoading,nonatomic,readonly) BOOL loading;                         //@synthesize loading=_loading - In the implementation block
@property (nonatomic,readonly) NSString * loadingMessage; 
@property (nonatomic,readonly) RidesharingFailure * failure;                          //@synthesize failure=_failure - In the implementation block
@property (nonatomic,readonly) NSArray * selectableChoices; 
@property (nonatomic,readonly) id<RidesharingRideChoice> selectedChoice;              //@synthesize selectedChoice=_selectedChoice - In the implementation block
-(void)addObserver:(id)arg1 changeHandler:(/*^block*/id)arg2 ;
-(void)_invokeChangeHandlers;
-(id)snapshotOfCurrentProvider;
-(void)switchToNewSelectedChoice:(id)arg1 ;
-(void)openContainingApplication;
-(NSString *)loadingMessage;
-(RidesharingFailure *)failure;
-(NSArray *)selectableChoices;
-(id)initWithSimulatedApplication:(id)arg1 ;
-(void)removeObserver:(id)arg1 ;
-(CLPlacemark *)origin;
-(_RidesSimulatedApplication *)application;
-(void)setApplication:(_RidesSimulatedApplication *)arg1 ;
-(BOOL)isLoading;
-(CLPlacemark *)destination;
-(id<RidesharingRideChoice>)selectedChoice;
@end

