/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, December 27, 2016 at 5:08:19 PM Japan Standard Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /Applications/Maps.app/PlugIns/MapsWidget.appex/MapsWidget
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface DynamicTypeValue : NSObject {

	/*^block*/id _fontProvider;
	double _unscaledValue;

}

@property (nonatomic,copy) id fontProvider;                     //@synthesize fontProvider=_fontProvider - In the implementation block
@property (assign,nonatomic) double unscaledValue;              //@synthesize unscaledValue=_unscaledValue - In the implementation block
@property (nonatomic,readonly) double scaledValue; 
-(double)scaledValue;
-(id)fontProvider;
-(void)setFontProvider:(id)arg1 ;
-(double)unscaledValue;
-(void)setUnscaledValue:(double)arg1 ;
@end

