/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, December 27, 2016 at 5:08:19 PM Japan Standard Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /Applications/Maps.app/PlugIns/MapsWidget.appex/MapsWidget
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface LightLevelTheme : NSObject
+(id)mapsMediumFontOfSize:(double)arg1 ;
+(id)mapsLightFontOfSize:(double)arg1 ;
+(id)darkUITextColor;
+(id)dimmedTextColor;
+(id)compactTextColor;
+(id)calculatedTextColor:(BOOL)arg1 isDimmed:(BOOL)arg2 isUIDark:(BOOL)arg3 ;
+(id)mediumLargeTextAttributes:(BOOL)arg1 isDimmed:(BOOL)arg2 isUIDark:(BOOL)arg3 ;
+(id)lightSmallTextAttributes:(BOOL)arg1 isDimmed:(BOOL)arg2 isUIDark:(BOOL)arg3 ;
+(id)lightLargeTextAttributes:(BOOL)arg1 isDimmed:(BOOL)arg2 isUIDark:(BOOL)arg3 ;
+(id)mediumSmallTextAttributes:(BOOL)arg1 isDimmed:(BOOL)arg2 isUIDark:(BOOL)arg3 ;
+(id)updateTextAttributesForDimmedState:(id)arg1 isCompact:(BOOL)arg2 isDimmed:(BOOL)arg3 isUIDark:(BOOL)arg4 ;
+(id)dimmedBackgroundColor;
+(id)directionsListDividerColor;
+(id)directionsListDividerColorWithDarkBackground:(BOOL)arg1 ;
+(id)directionsListDimmedDividerColor;
+(id)directionsListDimmedHighlightedCellBackgroundColor;
+(id)mapReplacementColor;
+(id)textColor;
@end

