/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, December 27, 2016 at 5:08:19 PM Japan Standard Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /Applications/Maps.app/PlugIns/MapsWidget.appex/MapsWidget
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MapsWidget/MapsWidget-Structs.h>
#import <MapsWidget/MapsSuggestionsObject.h>

@protocol MapsSuggestionsStrategy, OS_dispatch_queue, OS_dispatch_source;
@class NSMutableArray, MapsSuggestionsTracker, MapsSuggestionsCurrentLocationUpdater, NSDate, NSObject, CLLocation, GEOAutomobileOptions, NSString;

@interface MapsSuggestionsManager : NSObject <MapsSuggestionsObject> {

	id<MapsSuggestionsStrategy> _strategy;
	NSMutableArray* _additionalFilters;
	unsigned long long _countToRequest;
	MapsSuggestionsTracker* _tracker;
	MapsSuggestionsCurrentLocationUpdater* _locationUpdater;
	NSDate* _etaValidUntil;
	NSMutableSet* _sources;
	NSMutableSet* _sinks;
	NSMutableDictionary* _storage;
	NSArray* _latestResults;
	NSObject*<OS_dispatch_queue> _gatheringQueue;
	NSObject*<OS_dispatch_queue> _storageQueue;
	BOOL _dirtyFlag;
	unsigned long long _defaultTansportType;
	NSObject*<OS_dispatch_source> _invalidateSinksOnExpiredTimer;
	NSObject*<OS_dispatch_source> _wipeStaleETATimer;
	int _mapType;
	long long _style;
	CLLocation* _currentLocation;
	GEOAutomobileOptions* _automobileOptions;

}

@property (retain) CLLocation * currentLocation;                                    //@synthesize currentLocation=_currentLocation - In the implementation block
@property (nonatomic,retain) id<MapsSuggestionsStrategy> strategy;                  //@synthesize strategy=_strategy - In the implementation block
@property (assign,nonatomic) int mapType;                                           //@synthesize mapType=_mapType - In the implementation block
@property (nonatomic,retain) GEOAutomobileOptions * automobileOptions;              //@synthesize automobileOptions=_automobileOptions - In the implementation block
@property (assign,nonatomic) long long style;                                       //@synthesize style=_style - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (nonatomic,readonly) NSString * uniqueName; 
+(void)load;
-(void)_updateCurrentLocation:(id)arg1 ;
-(void)_updateSource:(id)arg1 repeat:(BOOL)arg2 ;
-(void)_updateAllSourcesOnce;
-(void)_pruneExpiredSourceEntries;
-(NSArray*)_pruneExpiredFromEntries:(NSArray*)arg1 ;
-(void)_sendInvalidateToAllSinks;
-(void)_scheduleInvalidateSinksOnFirstExpiredOfEntries:(NSArray*)arg1 ;
-(BOOL)_updateResult;
-(BOOL)attachSource:(id)arg1 ;
-(BOOL)detachSource:(id)arg1 ;
-(BOOL)attachSink:(id)arg1 ;
-(BOOL)detachSink:(id)arg1 ;
-(void)_wipeStaleETAs;
-(BOOL)topSuggestionsForSink:(id)arg1 count:(unsigned long long)arg2 transportType:(unsigned long long)arg3 callback:(/*^block*/id)arg4 onQueue:(id)arg5 ;
-(void)addAdditionalFilter:(id)arg1 ;
-(void)removeAdditionalFilter:(id)arg1 ;
-(BOOL)_additionalFiltersAllowEntry:(id)arg1 ;
-(void)_pruneAdditionallyFilteredResults;
-(BOOL)saveStorageToFile:(id)arg1 ;
-(BOOL)loadStorageFromFile:(id)arg1 ;
-(unsigned long long)addOrUpdateSuggestionEntries:(NSArray*)arg1 source:(id)arg2 ;
-(unsigned long long)_addOrUpdateSuggestionEntries:(NSArray*)arg1 source:(id)arg2 ;
-(unsigned long long)addOrUpdateSuggestionEntries:(NSArray*)arg1 source:(id)arg2 deleteMissing:(BOOL)arg3 ;
-(BOOL)_removeEntry:(id)arg1 sourceName:(NSString*)arg2 ;
-(unsigned long long)deleteEntries:(NSArray*)arg1 source:(id)arg2 ;
-(unsigned long long)_deleteEntries:(NSArray*)arg1 source:(id)arg2 ;
-(unsigned long long)clearAllEntriesFromSource:(id)arg1 ;
-(unsigned long long)deleteAllEntriesFromSource:(id)arg1 ;
-(void)trackerRefreshedETAsUntil:(id)arg1 ;
-(id)dumpStorage;
-(NSArray*)storageForSource:(id)arg1 ;
-(NSSet*)sinks;
-(void)sendInvalidateToAllSinks;
-(void)scheduleRefereshForType:(unsigned char)arg1 ;
-(NSDictionary*)storage;
-(void)dealloc;
-(long long)style;
-(void)setStyle:(long long)arg1 ;
-(NSString *)uniqueName;
-(NSSet*)sources;
-(int)mapType;
-(void)setMapType:(int)arg1 ;
-(GEOAutomobileOptions *)automobileOptions;
-(void)setAutomobileOptions:(GEOAutomobileOptions *)arg1 ;
-(CLLocation *)currentLocation;
-(void)setCurrentLocation:(CLLocation *)arg1 ;
-(id)initWithStrategy:(id)arg1 ;
-(id<MapsSuggestionsStrategy>)strategy;
-(void)setStrategy:(id<MapsSuggestionsStrategy>)arg1 ;
-(void)clearResults;
@end

