/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, December 27, 2016 at 5:08:19 PM Japan Standard Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /Applications/Maps.app/PlugIns/MapsWidget.appex/MapsWidget
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

@class NSString, MapsSuggestionsManager;


@protocol MapsSuggestionsSource <MapsSuggestionsObject>
@property (nonatomic,retain) NSString * uniqueName; 
@property (assign,nonatomic,__weak) MapsSuggestionsManager * manager; 
@required
-(double)updateSuggestionEntries;
-(BOOL)canProduceEntriesOfType:(unsigned char)arg1;
-(id)init;
-(void)reset;
-(NSString *)uniqueName;
-(id)initWithManager:(id)arg1;
-(MapsSuggestionsManager *)manager;
-(void)setManager:(id)arg1;
-(void)setUniqueName:(NSString*)arg1;

@end

