/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, December 27, 2016 at 5:08:19 PM Japan Standard Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /Applications/Maps.app/PlugIns/MapsWidget.appex/MapsWidget
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSCache;

@interface MapsWidgetIconCache : NSObject {

	NSCache* _cache;

}
-(id)_defaultImageForEntry:(id)arg1 ;
-(void)fetchIconForSuggestionsEntry:(id)arg1 completionHandler:(/*^block*/id)arg2 ;
@end

