/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, December 27, 2016 at 5:08:19 PM Japan Standard Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /Applications/Maps.app/PlugIns/MapsWidget.appex/MapsWidget
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MapsWidget/MapsSuggestionsBaseSource.h>
#import <MapsWidget/MapsSuggestionsSource.h>

@protocol OS_dispatch_queue;
@class NSObject, NSString, MapsSuggestionsManager;

@interface MapsSuggestionsReservationsSource : MapsSuggestionsBaseSource <MapsSuggestionsSource> {

	NSObject*<OS_dispatch_queue> _queue;

}

@property (nonatomic,readonly) NSObject*<OS_dispatch_queue> queue;                 //@synthesize queue=_queue - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (nonatomic,readonly) NSString * uniqueName; 
@property (assign,nonatomic,__weak) MapsSuggestionsManager * manager; 
+(void)load;
-(double)updateSuggestionEntries;
-(BOOL)canProduceEntriesOfType:(unsigned char)arg1 ;
-(void)_getAllUserCurrentBookings;
-(void)_entriesForPolicy:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)_entriesForExtension:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)_createEntryForBooking:(id)arg1 vendorID:(id)arg2 bundleID:(id)arg3 completion:(/*^block*/id)arg4 ;
-(id)suggestionTitleForReservation:(id)arg1 ;
-(id)suggestionSubtitleForReservation:(id)arg1 timeZone:(id)arg2 ;
-(id)appRootIdentifierForExtension:(id)arg1 ;
-(void)reset;
-(NSObject*<OS_dispatch_queue>)queue;
-(id)initWithManager:(id)arg1 ;
@end

