/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, December 27, 2016 at 5:08:19 PM Japan Standard Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /Applications/Maps.app/PlugIns/MapsWidget.appex/MapsWidget
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MapsWidget/MapsSuggestionsBaseSource.h>
#import <MapsWidget/MapsSuggestionsSource.h>

@class NSString, MapsSuggestionsManager;

@interface MapsSuggestionsReInjectSource : MapsSuggestionsBaseSource <MapsSuggestionsSource> {

	NSString* _path;

}

@property (nonatomic,retain) NSString * path;                                      //@synthesize path=_path - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (nonatomic,readonly) NSString * uniqueName; 
@property (assign,nonatomic,__weak) MapsSuggestionsManager * manager; 
+(void)load;
-(double)updateSuggestionEntries;
-(BOOL)canProduceEntriesOfType:(unsigned char)arg1 ;
-(void)_processFileAtPath:(id)arg1 ;
-(void)reset;
-(NSString *)path;
-(void)setPath:(NSString *)arg1 ;
-(id)initWithManager:(id)arg1 ;
@end

