/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, December 27, 2016 at 5:08:19 PM Japan Standard Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /Applications/Maps.app/PlugIns/MapsWidget.appex/MapsWidget
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MapKit/MKTableViewCell.h>

@class UIStackView, UILayoutGuide, NSLayoutConstraint, _MKUILabel, MKArtworkImageView, MWTransitItem;

@interface MWTransitNavigationItemCell : MKTableViewCell {

	UIStackView* _stackView;
	UILayoutGuide* _contentGuide;
	UILayoutGuide* _leadingGutterGuide;
	NSLayoutConstraint* _leadingtGutterWidthConstraint;
	NSLayoutConstraint* _artworkXCenterOffsetFromLeadingGutter;
	NSLayoutConstraint* _rowHeightConstraint;
	NSLayoutConstraint* _primaryLabelToContentGuideConstraint;
	_MKUILabel* _primaryLabel;
	_MKUILabel* _secondaryLabel;
	MKArtworkImageView* _artworkImageView;
	MWTransitItem* _transitItem;

}

@property (nonatomic,readonly) _MKUILabel * primaryLabel;                                   //@synthesize primaryLabel=_primaryLabel - In the implementation block
@property (nonatomic,readonly) _MKUILabel * secondaryLabel;                                 //@synthesize secondaryLabel=_secondaryLabel - In the implementation block
@property (nonatomic,readonly) MKArtworkImageView * artworkImageView;                       //@synthesize artworkImageView=_artworkImageView - In the implementation block
@property (assign,nonatomic) double rowHeight; 
@property (assign,nonatomic) double leadingArtworkColumnWidth; 
@property (assign,nonatomic) double artworkViewXCenterOffsetFromLeadingColumn; 
@property (nonatomic,retain) MWTransitItem * transitItem;                                   //@synthesize transitItem=_transitItem - In the implementation block
+(id)_secondaryFont;
+(id)_primaryFont;
-(id)_initialConstraints;
-(void)_updatePrimaryLabelToContentGuideConstaint;
-(void)setTransitItem:(MWTransitItem *)arg1 ;
-(void)setLeadingArtworkColumnWidth:(double)arg1 ;
-(double)leadingArtworkColumnWidth;
-(void)setArtworkViewXCenterOffsetFromLeadingColumn:(double)arg1 ;
-(double)artworkViewXCenterOffsetFromLeadingColumn;
-(MWTransitItem *)transitItem;
-(void)dealloc;
-(void)setRowHeight:(double)arg1 ;
-(double)rowHeight;
-(id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2 ;
-(_MKUILabel *)secondaryLabel;
-(MKArtworkImageView *)artworkImageView;
-(void)_createSubviews;
-(void)_updateLayout;
-(_MKUILabel *)primaryLabel;
@end

