/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, December 27, 2016 at 5:08:19 PM Japan Standard Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /Applications/Maps.app/PlugIns/MapsWidget.appex/MapsWidget
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MapsWidget/_RidesharingApplicationsSourceObserver.h>

@class NSDate, NSMutableDictionary, NSMapTable, NSMutableArray, NSTimer, NSArray, NSString;

@interface RidesharingCurrentRideProviderDataSource : NSObject <_RidesharingApplicationsSourceObserver> {

	NSDate* _lastRefreshDate;
	NSMutableDictionary* _currentRideProvidersByAppIdentifier;
	NSMapTable* _observers;
	NSMutableArray* _pendingCompletions;
	BOOL _refreshing;
	NSTimer* _timer;
	NSMutableDictionary* _completedRideIdentifiersByAppIdentifier;
	NSMutableDictionary* _completedRideDatesByAppIdentifier;
	NSMutableDictionary* _currentObservationOperations;
	NSArray* _currentRides;

}

@property (readonly) NSArray * currentRides;                        //@synthesize currentRides=_currentRides - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)sharedDataSource;
-(void)addObserver:(id)arg1 changeHandler:(/*^block*/id)arg2 ;
-(void)_invokeChangeHandlers;
-(void)applicationsSource:(id)arg1 didChangeApplicationsByAddingOrReplacingApplications:(id)arg2 removingApplications:(id)arg3 ;
-(void)_garbageCollectCompletedRideDefaults;
-(void)_updateCompletedRideDefaults;
-(NSArray *)currentRides;
-(BOOL)hasCurrentRideForApplication:(id)arg1 ;
-(BOOL)hasCurrentIncompleteRideForApplication:(id)arg1 ;
-(id)trayIconForRideWithAppBundleIdentifier:(id)arg1 ;
-(void)_fetchStateForApplications:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)_observeProviderForRemoval:(id)arg1 forApplication:(id)arg2 ;
-(void)_donateCurrentRideProvider:(id)arg1 forApplication:(id)arg2 ;
-(void)refreshIfNeededWithCompletion:(/*^block*/id)arg1 ;
-(id)_init;
-(void)removeObserver:(id)arg1 ;
-(void)_refreshIfNeeded;
@end

