/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, December 27, 2016 at 5:08:19 PM Japan Standard Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /Applications/Maps.app/PlugIns/MapsWidget.appex/MapsWidget
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MapsWidget/MapsWidget-Structs.h>
#import <libobjc.A.dylib/NSCopying.h>

@class NSString;

@interface RidesharingFareLineItem : NSObject <NSCopying> {

	NSString* _title;
	NSString* _details;

}

@property (nonatomic,readonly) NSString * title;                //@synthesize title=_title - In the implementation block
@property (nonatomic,readonly) NSString * details;              //@synthesize details=_details - In the implementation block
+(id)_fareItemsFromRideOption:(id)arg1 ;
-(id)_initWithTitle:(id)arg1 details:(id)arg2 ;
-(id)init;
-(BOOL)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(NSString *)title;
-(id)copyWithZone:(NSZone*)arg1 ;
-(NSString *)details;
@end

