/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, December 27, 2016 at 5:08:19 PM Japan Standard Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /Applications/Maps.app/PlugIns/MapsWidget.appex/MapsWidget
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSTimer, INRideOption, NSString;

@interface RidesharingSurgeAlertProvider : NSObject {

	NSTimer* _expirationTimer;
	INRideOption* _rideOption;
	/*^block*/id _completion;
	/*^block*/id _didSupersede;

}

@property (nonatomic,readonly) NSString * title; 
@property (nonatomic,readonly) NSString * message; 
@property (nonatomic,readonly) NSString * confirmCommandTitle; 
@property (nonatomic,readonly) NSString * cancelCommandTitle; 
@property (nonatomic,copy) id didSupersede;                                 //@synthesize didSupersede=_didSupersede - In the implementation block
-(NSString *)cancelCommandTitle;
-(id)didSupersede;
-(void)setDidSupersede:(id)arg1 ;
-(id)_initWithChoice:(id)arg1 completion:(/*^block*/id)arg2 ;
-(NSString *)confirmCommandTitle;
-(id)init;
-(void)cancel;
-(void)dealloc;
-(NSString *)title;
-(NSString *)message;
-(void)_expire;
-(void)confirm;
@end

