/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, December 27, 2016 at 5:08:19 PM Japan Standard Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /Applications/Maps.app/PlugIns/MapsWidget.appex/MapsWidget
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MapsWidget/MapsWidget-Structs.h>
#import <UIKit/UIView.h>

@class UIImageView, GuidanceManeuverView, SignStyle, UIImage;

@interface SimpleSignView : UIView {

	UIImageView* _backgroundView;
	GuidanceManeuverView* _maneuverView;
	UIEdgeInsets _maneuverViewEdgeInsets;
	UIImageView* _shieldView;
	SignStyle* _style;

}

@property (assign,nonatomic) UIEdgeInsets maneuverViewEdgeInsets;                //@synthesize maneuverViewEdgeInsets=_maneuverViewEdgeInsets - In the implementation block
@property (nonatomic,readonly) GuidanceManeuverView * maneuverView; 
@property (nonatomic,retain) UIImage * shieldImage; 
@property (nonatomic,retain) SignStyle * style;                                  //@synthesize style=_style - In the implementation block
-(void)updateStyleForTheme;
-(GuidanceManeuverView *)maneuverView;
-(void)setManeuverViewEdgeInsets:(UIEdgeInsets)arg1 ;
-(id)shieldImageView;
-(UIImage *)shieldImage;
-(void)setShieldImage:(UIImage *)arg1 ;
-(UIEdgeInsets)maneuverViewEdgeInsets;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)layoutSubviews;
-(SignStyle *)style;
-(void)setStyle:(SignStyle *)arg1 ;
@end

