/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, December 27, 2016 at 5:08:19 PM Japan Standard Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /Applications/Maps.app/PlugIns/MapsWidget.appex/MapsWidget
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <MapsWidget/MapsWidget-Structs.h>
@class MergedTransitRoutingIncidentMessage, GEOComposedRouteStep, GEOComposedRouteLeg, MNTransitInstruction, GEOComposedTransitTripRouteStep, NSTimeZone;

@interface TransitLegSteppingModeSign : NSObject {

	MergedTransitRoutingIncidentMessage* _incidentMessage;
	BOOL _isMatchedSign;
	GEOComposedRouteStep* _step;
	GEOComposedRouteLeg* _leg;
	MNTransitInstruction* _instruction;
	NSRange _stepIndexRange;

}

@property (nonatomic,readonly) GEOComposedRouteStep * step;                                                     //@synthesize step=_step - In the implementation block
@property (nonatomic,readonly) GEOComposedRouteLeg * leg;                                                       //@synthesize leg=_leg - In the implementation block
@property (assign,nonatomic) NSRange stepIndexRange;                                                            //@synthesize stepIndexRange=_stepIndexRange - In the implementation block
@property (nonatomic,readonly) MNTransitInstruction * instruction;                                              //@synthesize instruction=_instruction - In the implementation block
@property (nonatomic,readonly) GEOComposedTransitTripRouteStep * boardClusteredStep; 
@property (nonatomic,readonly) id<GEOTransitRoutingIncidentMessage> transitRoutingIncidentMessage; 
@property (assign,nonatomic) BOOL isMatchedSign;                                                                //@synthesize isMatchedSign=_isMatchedSign - In the implementation block
@property (nonatomic,readonly) id<GEOServerFormattedString> majorFormattedInstruction; 
@property (nonatomic,readonly) id<GEOServerFormattedString> minorFormattedInstruction; 
@property (nonatomic,readonly) id<GEOServerFormattedString> tertiaryFormattedInstruction; 
@property (nonatomic,readonly) NSTimeZone * timeZoneForFormattedString; 
@property (nonatomic,readonly) BOOL isWalking; 
@property (nonatomic,readonly) BOOL hasValidInstructions; 
-(id)initWithStep:(id)arg1 stepIndexRange:(NSRange)arg2 ;
-(id)initWithStep:(id)arg1 stepIndexRange:(NSRange)arg2 extraIncident:(id)arg3 ;
-(id)initWithWalkingLeg:(id)arg1 stepIndexRange:(NSRange)arg2 ;
-(BOOL)hasValidInstructions;
-(GEOComposedTransitTripRouteStep *)boardClusteredStep;
-(NSRange)stepIndexRange;
-(void)setStepIndexRange:(NSRange)arg1 ;
-(BOOL)isMatchedSign;
-(void)setIsMatchedSign:(BOOL)arg1 ;
-(MNTransitInstruction *)instruction;
-(id<GEOTransitRoutingIncidentMessage>)transitRoutingIncidentMessage;
-(BOOL)isWalking;
-(GEOComposedRouteStep *)step;
-(GEOComposedRouteLeg *)leg;
-(NSTimeZone *)timeZoneForFormattedString;
-(id<GEOServerFormattedString>)majorFormattedInstruction;
-(id<GEOServerFormattedString>)minorFormattedInstruction;
-(id<GEOServerFormattedString>)tertiaryFormattedInstruction;
@end

