/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, December 27, 2016 at 5:08:33 PM Japan Standard Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /Applications/iBooks.app/Frameworks/IMCommonCore.framework/IMCommonCore
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface BCFutureBlockPair : NSObject {

	/*^block*/id _block;
	void* _caller;

}

@property (nonatomic,copy) id block;                    //@synthesize block=_block - In the implementation block
@property (assign,nonatomic) void* caller;              //@synthesize caller=_caller - In the implementation block
-(void)setCaller:(void*)arg1 ;
-(void)setBlock:(id)arg1 ;
-(id)block;
-(void*)caller;
@end

