/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, December 27, 2016 at 5:08:32 PM Japan Standard Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /Applications/iBooks.app/Frameworks/IMCommonCore.framework/IMCommonCore
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface BKAssetUtilities : NSObject
+(short)assetContentTypeForContentType:(short)arg1 ;
+(short)contentTypeForExtension:(id)arg1 ;
+(short)contentTypeForBKAssetContentType:(short)arg1 ;
+(id)pathExtensionForContentType:(short)arg1 ;
+(short)contentTypeForPath:(id)arg1 ;
+(id)localizedAssetKindForContentType:(short)arg1 ;
+(id)dictionaryRepresentationForAsset:(id)arg1 ;
@end

