/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, December 27, 2016 at 5:08:32 PM Japan Standard Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /Applications/iBooks.app/Frameworks/IMCommonCore.framework/IMCommonCore
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

@class NSString;


@protocol IMActivityItemSource <UIActivityItemSource,NSObject>
@property (nonatomic,retain) NSString * activityType; 
@optional
-(void)activityViewController:(id)arg1 didShareItems:(id)arg2 success:(BOOL)arg3;
-(id)activityViewController:(id)arg1 subjectForActivityType:(id)arg2;

@required
-(NSString *)activityType;
-(id)activityViewControllerPlaceholderItem:(id)arg1;
-(id)activityViewController:(id)arg1 itemForActivityType:(id)arg2;
-(id)supportedActivityTypes;
-(void)setActivityType:(id)arg1;

@end

