/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, December 27, 2016 at 5:08:32 PM Japan Standard Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /Applications/iBooks.app/Frameworks/IMCommonCore.framework/IMCommonCore
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class IMDatabaseHandle;

@interface IMAdminTable : NSObject {

	IMDatabaseHandle* _db;

}
-(id)initWithDatabaseHandle:(id)arg1 ;
-(BOOL)hasDatabaseVersion;
-(void)setProperty:(id)arg1 forKey:(id)arg2 domain:(id)arg3 ;
-(id)numberValueForKey:(id)arg1 domain:(id)arg2 ;
-(id)blobValueForKey:(id)arg1 domain:(id)arg2 ;
-(id)stringValueForKey:(id)arg1 domain:(id)arg2 ;
-(void)setDatabaseVersion:(long long)arg1 ;
-(long long)databaseVersion;
-(void)setLastAccessDate:(id)arg1 ;
-(id)lastAccessDate;
@end

