/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, December 27, 2016 at 5:08:31 PM Japan Standard Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /Applications/iBooks.app/Frameworks/IMCommonCore.framework/IMCommonCore
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <IMCommonCore/IMCommonCore-Structs.h>
#import <libobjc.A.dylib/NSDiscardableContent.h>

@class NSArray;

@interface IMImageCacheObject : NSObject <NSDiscardableContent> {

	BOOL _persistedToDisk;
	NSArray* _imageRefs;
	CGSize _imageSize;

}

@property (nonatomic,copy) NSArray * imageRefs;                 //@synthesize imageRefs=_imageRefs - In the implementation block
@property (assign,nonatomic) CGSize imageSize;                  //@synthesize imageSize=_imageSize - In the implementation block
@property (assign,nonatomic) BOOL persistedToDisk;              //@synthesize persistedToDisk=_persistedToDisk - In the implementation block
-(BOOL)persistedToDisk;
-(id)initWithImageRefs:(id)arg1 imageSize:(CGSize)arg2 ;
-(NSArray *)imageRefs;
-(void)setImageRefs:(NSArray *)arg1 ;
-(void)setPersistedToDisk:(BOOL)arg1 ;
-(CGSize)imageSize;
-(BOOL)beginContentAccess;
-(void)endContentAccess;
-(void)discardContentIfPossible;
-(BOOL)isContentDiscarded;
-(void)setImageSize:(CGSize)arg1 ;
@end

