/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, December 27, 2016 at 5:08:32 PM Japan Standard Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /Applications/iBooks.app/Frameworks/IMCommonCore.framework/IMCommonCore
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <IMCommonCore/IMAssertion.h>

@class IMSpringboardWallpaperManager, NSString;

@interface IMSpringboardWallpaperAnimationAssertion : NSObject <IMAssertion> {

	IMSpringboardWallpaperManager* _manager;

}

@property (nonatomic,__weak,readonly) IMSpringboardWallpaperManager * manager;              //@synthesize manager=_manager - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)dealloc;
-(void)invalidate;
-(id)initWithManager:(id)arg1 ;
-(IMSpringboardWallpaperManager *)manager;
@end

