/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, December 27, 2016 at 5:08:33 PM Japan Standard Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /Applications/iBooks.app/Frameworks/IMCommonCore.framework/IMCommonCore
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface IMUbiquityMetadataHelper : NSObject
+(void)_setValueInMutableDictionary:(id)arg1 forKey:(id)arg2 withValueForExtendedAttributeNamed:(id)arg3 fromUrl:(id)arg4 ;
+(void)_removeExtendedAttributeNamed:(id)arg1 forUrl:(id)arg2 ;
+(id)ubiquityMetadataForURL:(id)arg1 options:(unsigned long long)arg2 ;
+(void)clearUbiquityMetadataForURL:(id)arg1 ;
+(void)_setExtendedAttributeNamed:(id)arg1 toValue:(id)arg2 forUrl:(id)arg3 ;
@end

