/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, December 27, 2016 at 5:08:33 PM Japan Standard Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /Applications/iBooks.app/Frameworks/IMCommonCore.framework/IMCommonCore
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol IMUbiquityStatusChangeObserving <NSObject>
@optional
-(void)ubiquitySpaceAvailableChanged:(unsigned long long)arg1;

@required
-(void)ubiquityStatusChangedToAvailableWithNewIdentity:(id)arg1 oldIdentity:(id)arg2;

@end

