/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, December 27, 2016 at 4:41:30 PM Japan Standard Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /usr/lib/libacmobileshim.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol ACCSSOTGTStoragePolicy <NSObject>
@required
-(id)allTokensWithPrincipal:(id)arg1;
-(id)searchTokenWithPrincipal:(id)arg1;
-(BOOL)storeToken:(id)arg1;
-(BOOL)updateToken:(id)arg1;
-(BOOL)removeTokenWithPrincipal:(id)arg1;

@end

