/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, December 27, 2016 at 4:41:30 PM Japan Standard Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /usr/lib/libacmobileshim.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libacmobileshim.dylib/ACMHTTPHandler.h>

@interface ACMHTTPTicketVerificationHandler : ACMHTTPHandler
+(id)handlerName;
-(id)initWithContext:(id)arg1 ;
-(id)requestBody;
@end

