/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, December 27, 2016 at 4:41:31 PM Japan Standard Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /usr/lib/libprequelite.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <libprequelite.dylib/libprequelite.dylib-Structs.h>
@class NSMutableArray;

@interface PQLStatement : NSObject {

	sqlite3_stmtRef _stmt;
	PQLStatement* _next;
	NSMutableArray* _aliveBinds;
	/*^block*/id _profilingHook;
	SCD_Union_PQ5* _specUnion;
	BOOL _inUse;
	BOOL _isTraced;
	short _specLength;

}

@property (nonatomic,readonly) BOOL isTraced; 
-(void)dealloc;
-(id)description;
-(void)invalidate;
-(id)initWithFormat:(id)arg1 arguments:(char*)arg2 db:(id)arg3 cache:(cache_sRef)arg4 ;
-(void)unbindForDB:(id)arg1 returnedRows:(unsigned long long)arg2 ;
-(BOOL)isTraced;
-(BOOL)_prepare:(const char*)arg1 withDB:(id)arg2 ;
-(id)translate:(id)arg1 hasInjections:(BOOL*)arg2 arguments:(char*)arg3 ;
-(id)initWithStatement:(id)arg1 forDB:(id)arg2 ;
-(void)bindArguments:(char*)arg1 db:(id)arg2 ;
-(void)keepBindAlive:(id)arg1 ;
@end

