/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, December 27, 2016 at 5:08:26 PM Japan Standard Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /Applications/News.app/Frameworks/SilexJSONObject.framework/SilexJSONObject
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSString;

@interface SXClassFactoryItem : NSObject {

	NSString* _typeString;
	Class _baseClass;
	Class _itemClass;

}

@property (nonatomic,retain) NSString * typeString;              //@synthesize typeString=_typeString - In the implementation block
@property (assign,nonatomic) Class baseClass;                    //@synthesize baseClass=_baseClass - In the implementation block
@property (assign,nonatomic) Class itemClass;                    //@synthesize itemClass=_itemClass - In the implementation block
-(void)setBaseClass:(Class)arg1 ;
-(void)setTypeString:(NSString *)arg1 ;
-(BOOL)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(void)setItemClass:(Class)arg1 ;
-(Class)itemClass;
-(NSString *)typeString;
-(Class)baseClass;
@end

