/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, December 27, 2016 at 4:43:02 PM Japan Standard Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libcoreroutine.dylib/RTNotification.h>

@class NSString;

@interface RTBluetoothManagerNotificationConnected : RTNotification {

	NSString* _deviceName;
	NSString* _deviceAddress;

}

@property (nonatomic,retain) NSString * deviceName;                 //@synthesize deviceName=_deviceName - In the implementation block
@property (nonatomic,retain) NSString * deviceAddress;              //@synthesize deviceAddress=_deviceAddress - In the implementation block
-(void)setDeviceName:(NSString *)arg1 ;
-(NSString *)deviceName;
-(id)initWithDeviceName:(id)arg1 andDeviceAddress:(id)arg2 ;
-(NSString *)deviceAddress;
-(void)setDeviceAddress:(NSString *)arg1 ;
@end

