/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, December 27, 2016 at 4:43:04 PM Japan Standard Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libcoreroutine.dylib/RTNotification.h>

@interface RTDataProtectionManagerNotificationUnlockedSinceBoot : RTNotification {

	BOOL _unlockedSinceBoot;

}

@property (nonatomic,readonly) BOOL unlockedSinceBoot;              //@synthesize unlockedSinceBoot=_unlockedSinceBoot - In the implementation block
-(BOOL)unlockedSinceBoot;
-(id)initWithUnlockedSinceBoot:(BOOL)arg1 ;
@end

