/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, December 27, 2016 at 4:43:03 PM Japan Standard Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libcoreroutine.dylib/RTNotifier.h>

@class NSUUID, NRPairedDeviceRegistry;

@interface RTDeviceRegistry : RTNotifier {

	NSUUID* _currentlyPairedIdentifier;
	NRPairedDeviceRegistry* _pairedDeviceRegistry;

}

@property (nonatomic,retain) NSUUID * currentlyPairedIdentifier;                         //@synthesize currentlyPairedIdentifier=_currentlyPairedIdentifier - In the implementation block
@property (nonatomic,retain) NRPairedDeviceRegistry * pairedDeviceRegistry;              //@synthesize pairedDeviceRegistry=_pairedDeviceRegistry - In the implementation block
+(id)sharedInstance;
-(id)init;
-(void)dealloc;
-(void)internalAddObserver:(id)arg1 name:(id)arg2 ;
-(void)internalRemoveObserver:(id)arg1 name:(id)arg2 ;
-(void)fetchCurrentlyPairedWatchIdentifier:(/*^block*/id)arg1 ;
-(void)fetchIsPaired:(/*^block*/id)arg1 ;
-(id)initWithPairedDeviceRegistry:(id)arg1 ;
-(NRPairedDeviceRegistry *)pairedDeviceRegistry;
-(void)onPairChangeNotification:(id)arg1 ;
-(void)updateCurrentlyPairedWatchIdentifier:(id)arg1 ;
-(NSUUID *)currentlyPairedIdentifier;
-(void)setCurrentlyPairedIdentifier:(NSUUID *)arg1 ;
-(void)setPairedDeviceRegistry:(NRPairedDeviceRegistry *)arg1 ;
@end

