/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, December 27, 2016 at 4:43:03 PM Japan Standard Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSMutableArray;

@interface RTParkingQualityProvider : NSObject {

	NSMutableArray* _movingHistorgram;
	unsigned long long _parkingQualityIndicator;

}

@property (nonatomic,retain) NSMutableArray * movingHistorgram;                       //@synthesize movingHistorgram=_movingHistorgram - In the implementation block
@property (assign,nonatomic) unsigned long long parkingQualityIndicator;              //@synthesize parkingQualityIndicator=_parkingQualityIndicator - In the implementation block
-(id)init;
-(void)reset;
-(unsigned long long)calculateParkingQualityWithLocations:(id)arg1 parkingTimestamp:(double)arg2 ;
-(NSMutableArray *)movingHistorgram;
-(void)setParkingQualityIndicator:(unsigned long long)arg1 ;
-(unsigned long long)classifySamples:(id)arg1 ;
-(unsigned long long)parkingQualityToLocationQuality:(unsigned long long)arg1 ;
-(id)getHistogramFromSamples:(id)arg1 ;
-(id)getCdfFromHistogram:(id)arg1 numSamples:(double)arg2 ;
-(int)indexOfSmallestElement:(double*)arg1 size:(int)arg2 ;
-(unsigned long long)parkingQualityIndicator;
-(void)setMovingHistorgram:(NSMutableArray *)arg1 ;
@end

