/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, December 27, 2016 at 4:43:01 PM Japan Standard Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libcoreroutine.dylib/RTPredictionExpertFeatureAddonMO.h>

@class NSString;

@interface RTPredictionExpertFeatureAddonContextMO : RTPredictionExpertFeatureAddonMO

@property (nonatomic,retain) NSString * key; 
@property (nonatomic,retain) id value; 
+(id)managedObjectWithKey:(id)arg1 value:(id)arg2 inManagedObjectContext:(id)arg3 ;
@end

