/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, December 27, 2016 at 4:43:03 PM Japan Standard Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libobjc.A.dylib/RTPredictionExpertProtocol.h>

@protocol OS_dispatch_queue;
@class RTPredictionExpertDataSource, RTEventStoreHistogram, NSArray, NSUUID, NSObject, NSString;

@interface RTPredictionExpert : NSObject <RTPredictionExpertProtocol> {

	long long _category;
	RTPredictionExpertDataSource* _dataSource;
	RTEventStoreHistogram* _histogram;
	NSArray* _featureAddons;
	NSUUID* _identifier;
	NSObject*<OS_dispatch_queue> _queue;
	NSArray* _dataProviders;

}

@property (nonatomic,retain) RTEventStoreHistogram * histogram;                        //@synthesize histogram=_histogram - In the implementation block
@property (nonatomic,retain) NSArray * featureAddons;                                  //@synthesize featureAddons=_featureAddons - In the implementation block
@property (assign,nonatomic) long long category;                                       //@synthesize category=_category - In the implementation block
@property (nonatomic,retain) NSUUID * identifier;                                      //@synthesize identifier=_identifier - In the implementation block
@property (nonatomic,retain) NSObject*<OS_dispatch_queue> queue;                       //@synthesize queue=_queue - In the implementation block
@property (nonatomic,retain) NSArray * dataProviders;                                  //@synthesize dataProviders=_dataProviders - In the implementation block
@property (nonatomic,readonly) RTPredictionExpertDataSource * dataSource;              //@synthesize dataSource=_dataSource - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(RTPredictionExpertDataSource *)dataSource;
-(void)setCategory:(long long)arg1 ;
-(long long)category;
-(NSUUID *)identifier;
-(void)setIdentifier:(NSUUID *)arg1 ;
-(NSObject*<OS_dispatch_queue>)queue;
-(void)setQueue:(NSObject*<OS_dispatch_queue>)arg1 ;
-(void)processData:(/*^block*/id)arg1 ;
-(NSArray *)dataProviders;
-(void)setDataProviders:(NSArray *)arg1 ;
-(id)dataProviderForName:(id)arg1 ;
-(id)_createEventStoreWithClasses:(id)arg1 ;
-(void)setHistogram:(RTEventStoreHistogram *)arg1 ;
-(RTEventStoreHistogram *)histogram;
-(NSArray *)featureAddons;
-(void)createExpertMetricWithHandler:(/*^block*/id)arg1 ;
-(id)initWithQueue:(id)arg1 category:(long long)arg2 dataSource:(id)arg3 ;
-(void)setFeatureAddons:(NSArray *)arg1 ;
-(id)_combinedFilterPredicateForAddonType:(long long)arg1 ;
-(id)_combinedFilterPredicate;
@end

