/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, December 27, 2016 at 4:43:04 PM Japan Standard Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libcoreroutine.dylib/RTPredictionExpertFeatureAddonMO.h>

@interface RTPredictionExpertFeatureAddonTimeOfDayMO : RTPredictionExpertFeatureAddonMO

@property (nonatomic,retain) id endDateComponents; 
@property (nonatomic,retain) id startDateComponents; 
+(id)managedObjectWithStartDateComponents:(id)arg1 endDateComponents:(id)arg2 inManagedObjectContext:(id)arg3 ;
+(id)_managedObjectWithStartDateComponents:(id)arg1 endDateComponents:(id)arg2 inManagedObjectContext:(id)arg3 ;
+(id)managedObjectWithDateRange:(id)arg1 inManagedObjectContext:(id)arg2 ;
@end

