/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, December 27, 2016 at 4:43:03 PM Japan Standard Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libcoreroutine.dylib/RTPredictionTableController.h>

@interface RTPredictionTableControllerRoomAssist : RTPredictionTableController
-(void)predictionWithMicroLocation:(id)arg1 limit:(unsigned long long)arg2 confidence:(double)arg3 handler:(/*^block*/id)arg4 ;
-(void)_predictionWithMicroLocation:(id)arg1 limit:(unsigned long long)arg2 confidence:(double)arg3 predictionTable:(id)arg4 handler:(/*^block*/id)arg5 ;
-(void)predictionWithMicroLocation:(id)arg1 handler:(/*^block*/id)arg2 ;
@end

