/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, December 27, 2016 at 4:43:03 PM Japan Standard Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libcoreroutine.dylib/RTNotification.h>

@interface RTStarkManagerNotificationTrustedConnectionEstablished : RTNotification {

	BOOL _trustedConnectionEstablished;

}

@property (assign,nonatomic) BOOL trustedConnectionEstablished;              //@synthesize trustedConnectionEstablished=_trustedConnectionEstablished - In the implementation block
-(id)initWithTrustedConnectionEstablished:(BOOL)arg1 ;
-(BOOL)trustedConnectionEstablished;
-(void)setTrustedConnectionEstablished:(BOOL)arg1 ;
@end

