/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, December 27, 2016 at 4:43:00 PM Japan Standard Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /usr/lib/libcoreroutine.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libcoreroutine.dylib/RTTaskDependency.h>

@interface RTTaskDependencyReachability : RTTaskDependency {

	long long _reachability;

}

@property (nonatomic,readonly) long long reachability;              //@synthesize reachability=_reachability - In the implementation block
-(long long)reachability;
-(BOOL)evaluate:(id)arg1 ;
-(id)initWithReachability:(long long)arg1 ;
@end

