/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, December 27, 2016 at 5:08:27 PM Japan Standard Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /Applications/News.app/PlugIns/NewsToday.appex/NewsToday
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <NewsToday/FRReadonlyPersonalizationAggregateStore.h>

@protocol FRReadonlyPersonalizationAggregateStore <NSObject>
@required
-(id)aggregatesForFeatures:(id)arg1 configurableValues:(id)arg2;
-(id)baselineAggregateWithConfigurableValues:(id)arg1;

@end


@protocol FCDerivedPersonalizationData;
@class NSString;

@interface FRReadonlyPersonalizationAggregateStore : NSObject <FRReadonlyPersonalizationAggregateStore> {

	id<FCDerivedPersonalizationData> _derivedPersonalizationData;

}

@property (nonatomic,retain) id<FCDerivedPersonalizationData> derivedPersonalizationData;              //@synthesize derivedPersonalizationData=_derivedPersonalizationData - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)aggregatesForFeatures:(id)arg1 configurableValues:(id)arg2 ;
-(id)baselineAggregateWithConfigurableValues:(id)arg1 ;
-(id)initWithDerivedPersonalizationData:(id)arg1 ;
-(id)init;
-(id<FCDerivedPersonalizationData>)derivedPersonalizationData;
-(void)setDerivedPersonalizationData:(id<FCDerivedPersonalizationData>)arg1 ;
@end

