/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, December 27, 2016 at 5:08:27 PM Japan Standard Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /Applications/News.app/PlugIns/NewsToday.appex/NewsToday
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <NewsToday/FCFeedPersonalizing.h>

@protocol FCContentContext, FCTodayWidgetDropboxData;
@class NSString;

@interface FTFeedPersonalizer : NSObject <FCFeedPersonalizing> {

	id<FCContentContext> _contentContext;
	id<FCTodayWidgetDropboxData> _todayWidgetData;

}

@property (nonatomic,retain) id<FCContentContext> contentContext;                     //@synthesize contentContext=_contentContext - In the implementation block
@property (nonatomic,copy) id<FCTodayWidgetDropboxData> todayWidgetData;              //@synthesize todayWidgetData=_todayWidgetData - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)initWithContentContext:(id)arg1 todayWidgetData:(id)arg2 ;
-(id<FCTodayWidgetDropboxData>)todayWidgetData;
-(void)prepareForUseWithCompletionHandler:(/*^block*/id)arg1 ;
-(void)setTodayWidgetData:(id<FCTodayWidgetDropboxData>)arg1 ;
-(id)init;
-(id)rankTagIDsDescending:(id)arg1 ;
-(id)scoresForTagIDs:(id)arg1 ;
-(id)sortArticles:(id)arg1 ;
-(void)setContentContext:(id<FCContentContext>)arg1 ;
-(id<FCContentContext>)contentContext;
-(id)limitArticlesByMinimumArticleQuality:(id)arg1 ;
-(id)limitArticlesByFlowRate:(id)arg1 dateRange:(id)arg2 ;
@end

