/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, December 27, 2016 at 5:08:27 PM Japan Standard Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /Applications/News.app/PlugIns/NewsToday.appex/NewsToday
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <NewsToday/NewsToday-Structs.h>
#import <libobjc.A.dylib/NSCopying.h>

@interface FTInterfaceConfiguration : NSObject <NSCopying> {

	double _rowHeight;
	double _verticalLayoutMargin;
	unsigned long long _thumbnailSizePreset;
	unsigned long long _sourceNameImageSizePreset;

}

@property (nonatomic,readonly) double rowHeight;                                          //@synthesize rowHeight=_rowHeight - In the implementation block
@property (nonatomic,readonly) double verticalLayoutMargin;                               //@synthesize verticalLayoutMargin=_verticalLayoutMargin - In the implementation block
@property (nonatomic,readonly) unsigned long long thumbnailSizePreset;                    //@synthesize thumbnailSizePreset=_thumbnailSizePreset - In the implementation block
@property (nonatomic,readonly) unsigned long long sourceNameImageSizePreset;              //@synthesize sourceNameImageSizePreset=_sourceNameImageSizePreset - In the implementation block
-(unsigned long long)thumbnailSizePreset;
-(unsigned long long)sourceNameImageSizePreset;
-(id)initWithRowHeight:(double)arg1 verticalLayoutMargin:(double)arg2 thumbnailSizePreset:(unsigned long long)arg3 sourceNameImageSizePreset:(unsigned long long)arg4 ;
-(double)verticalLayoutMargin;
-(id)init;
-(double)rowHeight;
-(id)copyWithZone:(NSZone*)arg1 ;
@end

