/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, December 27, 2016 at 5:08:26 PM Japan Standard Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /Applications/News.app/PlugIns/NewsToday.appex/NewsToday
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <NewsToday/FTHeadlineResultOperation.h>

@class FTHeadlineResults;

@interface FTNewsHeadlineResultOperation : FTHeadlineResultOperation {

	FTHeadlineResults* _resultHeadlineResults;

}

@property (nonatomic,copy) FTHeadlineResults * resultHeadlineResults;              //@synthesize resultHeadlineResults=_resultHeadlineResults - In the implementation block
+(void)initialize;
-(void)setResultHeadlineResults:(FTHeadlineResults *)arg1 ;
-(FTHeadlineResults *)resultHeadlineResults;
-(id)_resolveWidgetConfigWithFeldsparID:(id)arg1 appConfiguration:(id)arg2 ;
-(void)_fetchHeadlineResultsWithSectionDescriptorsInFallbackOrder:(id)arg1 sectionDescriptorsInDisplayOrder:(id)arg2 todayWidgetData:(id)arg3 headlinesLimit:(unsigned long long)arg4 sourceConfigurationIdentifier:(id)arg5 completion:(/*^block*/id)arg6 ;
-(void)_finalizeHeadlineResultsWithFormerSectionDescriptor:(id)arg1 formerResults:(id)arg2 latterSectionDescriptor:(id)arg3 latterResults:(id)arg4 sourceConfigurationIdentifier:(id)arg5 completion:(/*^block*/id)arg6 ;
-(void)_reorderDescriptorPairInDisplayOrderWithFormerDescriptor:(id)arg1 formerResults:(id)arg2 latterDescriptor:(id)arg3 latterResults:(id)arg4 descriptorsInDisplayOrder:(id)arg5 completion:(/*^block*/id)arg6 ;
-(id)init;
-(BOOL)validateOperation;
-(void)performOperation;
-(void)operationWillFinishWithError:(id)arg1 ;
@end

