/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, December 27, 2016 at 5:08:27 PM Japan Standard Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /Applications/News.app/PlugIns/NewsToday.appex/NewsToday
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <NewsToday/FTWidgetModeContext.h>

@protocol FTWidgetEventTracker;
@class FTHeadlineResultsSource, NSString;

@interface FTNewsWidgetModeContext : NSObject <FTWidgetModeContext> {

	BOOL _supportsEventTracking;
	FTHeadlineResultsSource* _headlineResultsSource;
	id<FTWidgetEventTracker> _widgetEventTracker;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (nonatomic,readonly) FTHeadlineResultsSource * headlineResultsSource;              //@synthesize headlineResultsSource=_headlineResultsSource - In the implementation block
@property (nonatomic,readonly) id<FTWidgetEventTracker> widgetEventTracker;                  //@synthesize widgetEventTracker=_widgetEventTracker - In the implementation block
@property (nonatomic,readonly) BOOL supportsEventTracking;                                   //@synthesize supportsEventTracking=_supportsEventTracking - In the implementation block
-(id)initWithDropbox:(id)arg1 contentContext:(id)arg2 ;
-(FTHeadlineResultsSource *)headlineResultsSource;
-(id<FTWidgetEventTracker>)widgetEventTracker;
-(BOOL)supportsEventTracking;
-(id)init;
@end

