/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, December 27, 2016 at 5:08:27 PM Japan Standard Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /Applications/News.app/PlugIns/NewsToday.appex/NewsToday
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <NewsToday/NewsToday-Structs.h>
#import <NewsToday/FTWidgetEventTracker.h>

@class _PWTWidgetEventTracker, FTHeadlineEngagementEventTracker, FTWidgetAppearanceEventTracker, FTWidgetUpdateEventTracker, NSString;

@interface FTProactiveWidgetEventTracker : NSObject <FTWidgetEventTracker> {

	BOOL _widgetVisible;
	_PWTWidgetEventTracker* _widgetEventTracker;
	FTHeadlineEngagementEventTracker* _headlineEngagementEventTracker;
	FTWidgetAppearanceEventTracker* _widgetAppearanceEventTracker;
	FTWidgetUpdateEventTracker* _widgetUpdateEventTracker;

}

@property (nonatomic,retain) _PWTWidgetEventTracker * widgetEventTracker;                                    //@synthesize widgetEventTracker=_widgetEventTracker - In the implementation block
@property (assign,getter=isWidgetVisible,nonatomic) BOOL widgetVisible;                                      //@synthesize widgetVisible=_widgetVisible - In the implementation block
@property (nonatomic,retain) FTHeadlineEngagementEventTracker * headlineEngagementEventTracker;              //@synthesize headlineEngagementEventTracker=_headlineEngagementEventTracker - In the implementation block
@property (nonatomic,retain) FTWidgetAppearanceEventTracker * widgetAppearanceEventTracker;                  //@synthesize widgetAppearanceEventTracker=_widgetAppearanceEventTracker - In the implementation block
@property (nonatomic,retain) FTWidgetUpdateEventTracker * widgetUpdateEventTracker;                          //@synthesize widgetUpdateEventTracker=_widgetUpdateEventTracker - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(_PWTWidgetEventTracker *)widgetEventTracker;
-(FTHeadlineEngagementEventTracker *)headlineEngagementEventTracker;
-(void)setHeadlineEngagementEventTracker:(FTHeadlineEngagementEventTracker *)arg1 ;
-(void)widgetDidAppearWithHeadlineSource:(id)arg1 sourceConfigurationIdentifier:(id)arg2 ;
-(void)widgetDidFetchHeadlineResults:(id)arg1 ;
-(void)widgetPerformedUpdateWithHeadlineSource:(id)arg1 sourceConfigurationIdentifier:(id)arg2 updateFetchDuration:(double)arg3 updateResult:(unsigned long long)arg4 wifiReachable:(BOOL)arg5 cellularRadioAccessTechnology:(long long)arg6 ;
-(void)headlinesDidBecomeVisible:(id)arg1 withTriggerEvent:(unsigned long long)arg2 ;
-(void)userEngagedWithHeadline:(id)arg1 headlineSource:(id)arg2 sourceConfigurationIdentifier:(id)arg3 headlineSection:(id)arg4 otherVisibleHeadlineSection:(id)arg5 headlineOrder:(unsigned long long)arg6 widgetDisplayMode:(long long)arg7 ;
-(void)setWidgetEventTracker:(_PWTWidgetEventTracker *)arg1 ;
-(FTWidgetUpdateEventTracker *)widgetUpdateEventTracker;
-(void)setWidgetUpdateEventTracker:(FTWidgetUpdateEventTracker *)arg1 ;
-(FTWidgetAppearanceEventTracker *)widgetAppearanceEventTracker;
-(void)setWidgetAppearanceEventTracker:(FTWidgetAppearanceEventTracker *)arg1 ;
-(void)setWidgetVisible:(BOOL)arg1 ;
-(BOOL)isWidgetVisible;
-(id)init;
-(void)widgetWillAppear;
-(void)widgetWillDisappear;
-(void)widgetDidDisappear;
-(void)widgetActiveDisplayModeDidChange:(long long)arg1 withMaximumSize:(CGSize)arg2 ;
@end

