/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, December 27, 2016 at 5:08:27 PM Japan Standard Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /Applications/News.app/PlugIns/NewsToday.appex/NewsToday
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <NewsToday/FTHeadlineResultOperation.h>

@class NSNumber, FTHeadlineResults;

@interface FTReloadAnimationDemoHeadlineResultOperation : FTHeadlineResultOperation {

	unsigned long long _fromResultType;
	NSNumber* _resultCursor;
	FTHeadlineResults* _resultHeadlineResults;

}

@property (assign,nonatomic) unsigned long long fromResultType;                    //@synthesize fromResultType=_fromResultType - In the implementation block
@property (nonatomic,copy) NSNumber * resultCursor;                                //@synthesize resultCursor=_resultCursor - In the implementation block
@property (nonatomic,copy) FTHeadlineResults * resultHeadlineResults;              //@synthesize resultHeadlineResults=_resultHeadlineResults - In the implementation block
-(void)setResultHeadlineResults:(FTHeadlineResults *)arg1 ;
-(FTHeadlineResults *)resultHeadlineResults;
-(void)setFromResultType:(unsigned long long)arg1 ;
-(unsigned long long)fromResultType;
-(unsigned long long)_resultTypeAfterResultType:(unsigned long long)arg1 ;
-(id)init;
-(BOOL)validateOperation;
-(void)performOperation;
-(void)operationWillFinishWithError:(id)arg1 ;
-(void)setResultCursor:(NSNumber *)arg1 ;
-(void)prepareOperation;
-(NSNumber *)resultCursor;
@end

