/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, December 27, 2016 at 5:08:26 PM Japan Standard Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /Applications/News.app/PlugIns/NewsToday.appex/NewsToday
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

@class NSString;


@protocol FTSectionDescriptor <NSObject,NSCopying>
@property (nonatomic,readonly) NSString * identifier; 
@property (nonatomic,readonly) NSString * name; 
@property (nonatomic,readonly) long long cutoffTime; 
@property (nonatomic,readonly) unsigned long long readStoriesFilterMethod; 
@required
-(id)sortTransformationWithFeedPersonalizer:(id)arg1;
-(unsigned long long)readStoriesFilterMethod;
-(id)extractResultsFromCatchUpOperation:(id)arg1;
-(void)configureCatchUpOperationWithFetchRequest:(id)arg1;
-(NSString *)name;
-(NSString *)identifier;
-(long long)cutoffTime;

@end

