/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, December 27, 2016 at 5:08:27 PM Japan Standard Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /Applications/News.app/PlugIns/NewsToday.appex/NewsToday
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UITableViewCell.h>

@protocol NSCopying;
@class UIView, UIVisualEffectView, UILabel, UIImageView, NSObject, NSLayoutConstraint;

@interface FTTableViewCell : UITableViewCell {

	BOOL _hasThumbnail;
	BOOL _hasSourceNameImage;
	UIView* _topSeparator;
	UIView* _bottomSeparator;
	double _nameImageUnscaledHeight;
	UIVisualEffectView* _primaryVisualEffectView;
	UIVisualEffectView* _secondaryVisualEffectView;
	UILabel* _sourceNameLabel;
	UIImageView* _sourceNameImageView;
	UILabel* _titleLabel;
	UIImageView* _thumbnailImageView;
	UILabel* _ageLabel;
	UILabel* _badgeLabel;
	NSObject*<NSCopying> _identifier;
	NSLayoutConstraint* _titleTopYConstraint;
	NSLayoutConstraint* _textToThumbnailConstraint;
	NSLayoutConstraint* _textToTrailingAnchorConstraint;
	NSLayoutConstraint* _sourceNameLabelToTitleConstraint;
	NSLayoutConstraint* _sourceNameImageCenterYConstraint;
	NSLayoutConstraint* _titleToAgeConstraint;
	NSLayoutConstraint* _badgeToAgeConstraint;
	NSLayoutConstraint* _leadingToAgeConstraint;

}

@property (nonatomic,retain) UIVisualEffectView * primaryVisualEffectView;                       //@synthesize primaryVisualEffectView=_primaryVisualEffectView - In the implementation block
@property (nonatomic,retain) UIVisualEffectView * secondaryVisualEffectView;                     //@synthesize secondaryVisualEffectView=_secondaryVisualEffectView - In the implementation block
@property (nonatomic,retain) UILabel * sourceNameLabel;                                          //@synthesize sourceNameLabel=_sourceNameLabel - In the implementation block
@property (nonatomic,retain) UIImageView * sourceNameImageView;                                  //@synthesize sourceNameImageView=_sourceNameImageView - In the implementation block
@property (nonatomic,retain) UILabel * titleLabel;                                               //@synthesize titleLabel=_titleLabel - In the implementation block
@property (nonatomic,retain) UIImageView * thumbnailImageView;                                   //@synthesize thumbnailImageView=_thumbnailImageView - In the implementation block
@property (nonatomic,retain) UILabel * ageLabel;                                                 //@synthesize ageLabel=_ageLabel - In the implementation block
@property (nonatomic,retain) UILabel * badgeLabel;                                               //@synthesize badgeLabel=_badgeLabel - In the implementation block
@property (nonatomic,copy) NSObject*<NSCopying> identifier;                                      //@synthesize identifier=_identifier - In the implementation block
@property (assign,nonatomic) BOOL hasThumbnail;                                                  //@synthesize hasThumbnail=_hasThumbnail - In the implementation block
@property (assign,nonatomic) BOOL hasSourceNameImage;                                            //@synthesize hasSourceNameImage=_hasSourceNameImage - In the implementation block
@property (nonatomic,retain) NSLayoutConstraint * titleTopYConstraint;                           //@synthesize titleTopYConstraint=_titleTopYConstraint - In the implementation block
@property (nonatomic,retain) NSLayoutConstraint * textToThumbnailConstraint;                     //@synthesize textToThumbnailConstraint=_textToThumbnailConstraint - In the implementation block
@property (nonatomic,retain) NSLayoutConstraint * textToTrailingAnchorConstraint;                //@synthesize textToTrailingAnchorConstraint=_textToTrailingAnchorConstraint - In the implementation block
@property (nonatomic,retain) NSLayoutConstraint * sourceNameLabelToTitleConstraint;              //@synthesize sourceNameLabelToTitleConstraint=_sourceNameLabelToTitleConstraint - In the implementation block
@property (nonatomic,retain) NSLayoutConstraint * sourceNameImageCenterYConstraint;              //@synthesize sourceNameImageCenterYConstraint=_sourceNameImageCenterYConstraint - In the implementation block
@property (nonatomic,retain) NSLayoutConstraint * titleToAgeConstraint;                          //@synthesize titleToAgeConstraint=_titleToAgeConstraint - In the implementation block
@property (nonatomic,retain) NSLayoutConstraint * badgeToAgeConstraint;                          //@synthesize badgeToAgeConstraint=_badgeToAgeConstraint - In the implementation block
@property (nonatomic,retain) NSLayoutConstraint * leadingToAgeConstraint;                        //@synthesize leadingToAgeConstraint=_leadingToAgeConstraint - In the implementation block
@property (nonatomic,readonly) UIView * topSeparator;                                            //@synthesize topSeparator=_topSeparator - In the implementation block
@property (nonatomic,readonly) UIView * bottomSeparator;                                         //@synthesize bottomSeparator=_bottomSeparator - In the implementation block
@property (assign,nonatomic) double nameImageUnscaledHeight;                                     //@synthesize nameImageUnscaledHeight=_nameImageUnscaledHeight - In the implementation block
-(void)populateWithHeadline:(id)arg1 ;
-(void)setNameImageUnscaledHeight:(double)arg1 ;
-(void)setBadgeLabel:(UILabel *)arg1 ;
-(void)_updateTextToThumbnailConstraintConstant;
-(void)_updateToTitleConstraintConstants;
-(void)_updateTextToTrailingConstraint;
-(void)_updateSourceViewToTextConstraint;
-(void)_updateToAgeConstraints;
-(void)_updateFontsAndMetrics;
-(void)_updateNameImageCenterYConstraint;
-(void)_updateTitleTopYConstraint;
-(UILabel *)sourceNameLabel;
-(UILabel *)ageLabel;
-(UILabel *)badgeLabel;
-(UIImageView *)sourceNameImageView;
-(void)setHasSourceNameImage:(BOOL)arg1 ;
-(BOOL)hasSourceNameImage;
-(double)nameImageUnscaledHeight;
-(void)setSourceNameLabel:(UILabel *)arg1 ;
-(void)setSourceNameImageView:(UIImageView *)arg1 ;
-(void)setAgeLabel:(UILabel *)arg1 ;
-(NSLayoutConstraint *)titleTopYConstraint;
-(void)setTitleTopYConstraint:(NSLayoutConstraint *)arg1 ;
-(NSLayoutConstraint *)textToThumbnailConstraint;
-(void)setTextToThumbnailConstraint:(NSLayoutConstraint *)arg1 ;
-(NSLayoutConstraint *)textToTrailingAnchorConstraint;
-(void)setTextToTrailingAnchorConstraint:(NSLayoutConstraint *)arg1 ;
-(NSLayoutConstraint *)sourceNameLabelToTitleConstraint;
-(void)setSourceNameLabelToTitleConstraint:(NSLayoutConstraint *)arg1 ;
-(NSLayoutConstraint *)sourceNameImageCenterYConstraint;
-(void)setSourceNameImageCenterYConstraint:(NSLayoutConstraint *)arg1 ;
-(NSLayoutConstraint *)titleToAgeConstraint;
-(void)setTitleToAgeConstraint:(NSLayoutConstraint *)arg1 ;
-(NSLayoutConstraint *)badgeToAgeConstraint;
-(void)setBadgeToAgeConstraint:(NSLayoutConstraint *)arg1 ;
-(NSLayoutConstraint *)leadingToAgeConstraint;
-(void)setLeadingToAgeConstraint:(NSLayoutConstraint *)arg1 ;
-(void)layoutSubviews;
-(void)dealloc;
-(id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2 ;
-(NSObject*<NSCopying>)identifier;
-(void)layoutMarginsDidChange;
-(void)setIdentifier:(NSObject*<NSCopying>)arg1 ;
-(void)updateConstraints;
-(UILabel *)titleLabel;
-(void)setHighlighted:(BOOL)arg1 animated:(BOOL)arg2 ;
-(void)prepareForReuse;
-(id)accessibilityLabel;
-(BOOL)isAccessibilityElement;
-(void)setTitleLabel:(UILabel *)arg1 ;
-(BOOL)hasThumbnail;
-(UIVisualEffectView *)primaryVisualEffectView;
-(void)setPrimaryVisualEffectView:(UIVisualEffectView *)arg1 ;
-(UIVisualEffectView *)secondaryVisualEffectView;
-(void)setSecondaryVisualEffectView:(UIVisualEffectView *)arg1 ;
-(UIView *)topSeparator;
-(UIView *)bottomSeparator;
-(UIImageView *)thumbnailImageView;
-(void)setThumbnailImageView:(UIImageView *)arg1 ;
-(void)setHasThumbnail:(BOOL)arg1 ;
@end

