/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, December 27, 2016 at 5:08:27 PM Japan Standard Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /Applications/News.app/PlugIns/NewsToday.appex/NewsToday
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

@class FTHeadlineResultsSource;


@protocol FTWidgetModeContext <NSObject>
@property (nonatomic,readonly) FTHeadlineResultsSource * headlineResultsSource; 
@property (nonatomic,readonly) id<FTWidgetEventTracker> widgetEventTracker; 
@property (nonatomic,readonly) BOOL supportsEventTracking; 
@required
-(id)initWithDropbox:(id)arg1 contentContext:(id)arg2;
-(FTHeadlineResultsSource *)headlineResultsSource;
-(id<FTWidgetEventTracker>)widgetEventTracker;
-(BOOL)supportsEventTracking;
-(id)init;

@end

