/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, December 27, 2016 at 4:44:19 PM Japan Standard Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /usr/lib/log/liblog_mediaremote.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <liblog_mediaremote.dylib/MLFLogFormatter.h>

@interface MLFNowPlayingFormatter : MLFLogFormatter
-(id)formattedString;
-(id)_descriptionForValue:(id)arg1 fromNowPlayingInfoKey:(id)arg2 ;
@end

