/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, December 27, 2016 at 4:43:00 PM Japan Standard Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /usr/lib/libCTLogHelper.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <libCTLogHelper.dylib/libCTLogHelper.dylib-Structs.h>
@interface CTLogHelperControllerObjc : NSObject {

	shared_ptr<CTLogHelperController>* ptr;

}
-(id)init;
-(void)enableLogging:(BOOL)arg1 ;
-(void)dumpLogging;
-(BOOL)isWifLoggingEnabled;
-(BOOL)isThumperLoggingEnabled;
@end

