/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, December 27, 2016 at 5:08:29 PM Japan Standard Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /Applications/ServerDocuments.app/Frameworks/ServerDocsClient.framework/ServerDocsClient
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class ACAccountStore, ACAccountType, NSArray;

@interface SVAccountManager : NSObject {

	ACAccountStore* accountStore;
	ACAccountType* serverAccountType;
	NSArray* cachedServerAccounts;

}
+(id)sharedManager;
-(id)serverDocumentsAccounts;
-(void)accountStoreDidChange;
-(void)getServerDocumentsAccounts;
-(id)init;
-(id)accountWithIdentifier:(id)arg1 ;
@end

