/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, December 27, 2016 at 5:08:29 PM Japan Standard Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /Applications/ServerDocuments.app/Frameworks/ServerDocsClient.framework/ServerDocsClient
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UICollectionViewCell.h>

@class UIImageView, UILabel, NSLayoutConstraint;

@interface SVServerCollectionViewCell : UICollectionViewCell {

	UIImageView* _imageView;
	UILabel* _textLabel;
	NSLayoutConstraint* _imageViewWidthConstraint;

}

@property (assign,nonatomic,__weak) NSLayoutConstraint * imageViewWidthConstraint;              //@synthesize imageViewWidthConstraint=_imageViewWidthConstraint - In the implementation block
@property (assign,nonatomic,__weak) UIImageView * imageView;                                    //@synthesize imageView=_imageView - In the implementation block
@property (assign,nonatomic,__weak) UILabel * textLabel;                                        //@synthesize textLabel=_textLabel - In the implementation block
-(NSLayoutConstraint *)imageViewWidthConstraint;
-(void)setImageViewWidthConstraint:(NSLayoutConstraint *)arg1 ;
-(void)layoutSubviews;
-(void)awakeFromNib;
-(void)setHighlighted:(BOOL)arg1 ;
-(void)setSelected:(BOOL)arg1 ;
-(UILabel *)textLabel;
-(UIImageView *)imageView;
-(void)setImageView:(UIImageView *)arg1 ;
-(void)setTextLabel:(UILabel *)arg1 ;
-(void)updateFonts;
@end

