/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, December 27, 2016 at 5:08:23 PM Japan Standard Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /Applications/MobileSafari.app/MobileSafari
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol _SFBookmarkInfoViewControllerDelegate <NSObject>
@optional
-(void)bookmarkInfoViewController:(id)arg1 didFinishWithResult:(BOOL)arg2;
-(BOOL)bookmarkInfoViewControllerShouldUseTranslucentAppearance:(id)arg1;
-(BOOL)bookmarkInfoViewControllerCanSaveBookmarkChanges:(id)arg1;

@end

