/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, December 27, 2016 at 5:08:23 PM Japan Standard Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /Applications/MobileSafari.app/MobileSafari
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <SafariServices/_SFManagedActivityViewController.h>

@class TabDocument;

@interface ActionPanel : _SFManagedActivityViewController {

	BOOL _inCancel;
	BOOL _inCompletionHandler;
	TabDocument* _tabDocument;

}

@property (assign,nonatomic,__weak) id<ActionPanelDelegate> delegate; 
@property (nonatomic,readonly) TabDocument * tabDocument;                          //@synthesize tabDocument=_tabDocument - In the implementation block
-(void)_activityDidComplete:(id)arg1 withSuccess:(BOOL)arg2 ;
-(void)_preparePostToSocialNetwork:(id)arg1 ;
-(void)_prepareMail:(id)arg1 ;
-(void)_preparePrint:(id)arg1 completion:(/*^block*/id)arg2 ;
-(id)initWithTabDocument:(id)arg1 activityDelegate:(id)arg2 ;
-(TabDocument *)tabDocument;
-(long long)preferredStatusBarStyle;
-(void)viewDidDisappear:(BOOL)arg1 ;
-(id)_titleForActivity:(id)arg1 ;
-(void)_cancel;
-(id)excludedActivityTypes;
-(void)_prepareActivity:(id)arg1 completion:(/*^block*/id)arg2 ;
-(void)_executeActivity;
-(void)activityDidComplete:(id)arg1 withReturnedItems:(id)arg2 success:(BOOL)arg3 ;
@end

