/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, December 27, 2016 at 5:08:24 PM Japan Standard Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /Applications/MobileSafari.app/MobileSafari
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MobileSafari/Activity.h>
#import <MobileSafari/WebClipDelegate.h>
#import <MobileSafari/WebClipViewControllerDelegate.h>

@class UINavigationController, WebClipViewController, UIWebClip, NSString;

@interface AddToHomeScreenUIActivity : Activity <WebClipDelegate, WebClipViewControllerDelegate> {

	UINavigationController* _wrappingNavigationController;
	WebClipViewController* _webClipViewController;
	UIWebClip* _webClip;
	BOOL _webClipConfigured;
	BOOL _waitingForSnapshot;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)initWithTabDocument:(id)arg1 ;
-(void)webClipViewController:(id)arg1 didFinishWithResult:(BOOL)arg2 ;
-(void)_createWebClip;
-(void)_updateImageFromActiveTabDocument;
-(void)dealloc;
-(void)activityDidFinish:(BOOL)arg1 ;
-(id)activityType;
-(id)activityTitle;
-(BOOL)canPerformWithActivityItems:(id)arg1 ;
-(void)prepareWithActivityItems:(id)arg1 ;
-(id)activityViewController;
-(void)webClip:(id)arg1 iconRequestDidFinishWithImage:(id)arg2 precomposed:(BOOL)arg3 ;
-(void)webClip:(id)arg1 startupImageRequestDidFinishWithImage:(id)arg2 ;
-(void)webClip:(id)arg1 startupLandscapeImageRequestDidFinishWithImage:(id)arg2 ;
-(id)activityImage;
-(id)_beforeActivity;
-(id)_embeddedActivityViewController;
@end

