/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, December 27, 2016 at 5:08:24 PM Japan Standard Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /Applications/MobileSafari.app/MobileSafari
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class UIApplicationShortcutItem, BrowserController;

@interface ApplicationShortcutController : NSObject {

	UIApplicationShortcutItem* _showReadingListShortcutItem;
	UIApplicationShortcutItem* _showBookmarksShortcutItem;
	UIApplicationShortcutItem* _newPrivateTabShortcutItem;
	UIApplicationShortcutItem* _newTabShortcutItem;
	BrowserController* _browserController;

}

@property (assign,nonatomic,__weak) BrowserController * browserController;              //@synthesize browserController=_browserController - In the implementation block
-(void)updateShortcutItemsIfNeeded;
-(BOOL)handleShortcutItemWithType:(id)arg1 ;
-(void)setBrowserController:(BrowserController *)arg1 ;
-(BrowserController *)browserController;
-(id)_shortcutItemWithType:(id)arg1 iconTemplate:(id)arg2 ;
-(void)_openNewEmptyTabWithURLFieldFocused:(BOOL)arg1 privateBrowsingState:(long long)arg2 ;
-(void)_showBookmarksPanelWithSelectedCollection:(id)arg1 ;
-(id)_shortcutItems;
-(id)init;
@end

