/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, December 27, 2016 at 5:08:23 PM Japan Standard Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /Applications/MobileSafari.app/MobileSafari
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <SafariServices/_SFPopoverSizingTableViewController.h>

@protocol BackForwardTableViewControllerDelegate;
@class NSArray;

@interface BackForwardTableViewController : _SFPopoverSizingTableViewController {

	BOOL _reversesListOrder;
	id<BackForwardTableViewControllerDelegate> _delegate;
	NSArray* _backForwardList;

}

@property (assign,nonatomic,__weak) id<BackForwardTableViewControllerDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (nonatomic,copy) NSArray * backForwardList;                                                 //@synthesize backForwardList=_backForwardList - In the implementation block
@property (assign,nonatomic) BOOL reversesListOrder;                                                  //@synthesize reversesListOrder=_reversesListOrder - In the implementation block
-(void)setBackForwardList:(NSArray *)arg1 ;
-(BOOL)reversesListOrder;
-(void)setReversesListOrder:(BOOL)arg1 ;
-(void)setDelegate:(id<BackForwardTableViewControllerDelegate>)arg1 ;
-(void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2 ;
-(long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2 ;
-(id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2 ;
-(id<BackForwardTableViewControllerDelegate>)delegate;
-(void)loadView;
-(id)initWithStyle:(long long)arg1 ;
-(void)done;
-(NSArray *)backForwardList;
-(id)itemAtIndexPath:(id)arg1 ;
@end

