/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, December 27, 2016 at 5:08:23 PM Japan Standard Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /Applications/MobileSafari.app/MobileSafari
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol BookmarkFavoritesViewControllerDelegate <NSObject>
@required
-(void)bookmarkFavoritesViewController:(id)arg1 didSelectNavigationDestination:(id)arg2;
-(void)bookmarkFavoritesViewController:(id)arg1 didSelectFolder:(id)arg2;
-(void)bookmarkFavoritesViewController:(id)arg1 editBookmark:(id)arg2;
-(void)didTapOutsideBookmarkFavoritesViewController:(id)arg1;
-(UIEdgeInsets*)contentInsetForFavoritesViewController:(id)arg1;
-(long long)bookmarkFavoritesViewControllerFavoritesGridViewLayoutType:(id)arg1;
-(id)bookmarkFavoritesViewController:(id)arg1 previewViewControllerForBookmark:(id)arg2;
-(void)bookmarkFavoritesViewController:(id)arg1 commitPreviewedViewController:(id)arg2;

@end

