/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, December 27, 2016 at 5:08:23 PM Japan Standard Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /Applications/MobileSafari.app/MobileSafari
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol BookmarksBarViewDelegate <NSObject>
@optional
-(void)bookmarksBarView:(id)arg1 bookmarksNavigationControllerViewDidAppear:(id)arg2;
-(void)bookmarksBarView:(id)arg1 bookmarksNavigationControllerViewDidDisappear:(id)arg2;
-(void)bookmarksBarView:(id)arg1 bookmarksNavigationController:(id)arg2 showLockedBookmarksDatabaseAlertForBookmarkAddition:(BOOL)arg3;

@required
-(void)bookmarksBarView:(id)arg1 didSelectNavigationDestination:(id)arg2;

@end

