/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, December 27, 2016 at 5:08:24 PM Japan Standard Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /Applications/MobileSafari.app/MobileSafari
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <MobileSafari/MobileSafari-Structs.h>
@interface BrowserContainerArrangement : NSObject {

	CGSize _onScreenChildSize;
	CGPoint _onScreenChildStartingOrigin;
	CGSize _offScreenChildSize;
	unsigned long long _childCount;
	long long _hintingEdge;
	NSRange _onScreenChildRange;
	CGSize _size;
	CGAffineTransform _hintingTransform;

}

@property (nonatomic,readonly) unsigned long long childCount;                           //@synthesize childCount=_childCount - In the implementation block
@property (nonatomic,readonly) NSRange onScreenChildRange;                              //@synthesize onScreenChildRange=_onScreenChildRange - In the implementation block
@property (nonatomic,readonly) CGSize size;                                             //@synthesize size=_size - In the implementation block
@property (nonatomic,readonly) long long hintingEdge;                                   //@synthesize hintingEdge=_hintingEdge - In the implementation block
@property (nonatomic,readonly) CGAffineTransform hintingTransform;                      //@synthesize hintingTransform=_hintingTransform - In the implementation block
@property (nonatomic,readonly) CGRect separatorFrame; 
@property (nonatomic,readonly) unsigned long long firstOnScreenChildIndex; 
@property (nonatomic,readonly) unsigned long long lastOnScreenChildIndex; 
-(CGRect)childFrameAtIndex:(unsigned long long)arg1 ;
-(unsigned long long)firstOnScreenChildIndex;
-(unsigned long long)lastOnScreenChildIndex;
-(BOOL)childIsOnScreenAtIndex:(unsigned long long)arg1 ;
-(CGAffineTransform)hintingTransform;
-(CGRect)separatorFrame;
-(id)initWithChildCount:(unsigned long long)arg1 onScreenChildRange:(NSRange)arg2 size:(CGSize)arg3 hintingEdge:(long long)arg4 ;
-(NSRange)onScreenChildRange;
-(void)_calculateOutputs;
-(long long)hintingEdge;
-(id)init;
-(CGSize)size;
-(id)debugDescription;
-(unsigned long long)childCount;
@end

