/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, December 27, 2016 at 5:08:24 PM Japan Standard Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /Applications/MobileSafari.app/MobileSafari
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSString, UIWindow;

@interface CatalogViewControllerState : NSObject {

	BOOL _showingCompletions;
	BOOL _showingUniversalFirstTimeExperience;
	long long _favoritesState;
	NSString* _queryString;
	UIWindow* _detailWindow;

}

@property (assign,nonatomic) long long favoritesState;                                                                           //@synthesize favoritesState=_favoritesState - In the implementation block
@property (nonatomic,copy) NSString * queryString;                                                                               //@synthesize queryString=_queryString - In the implementation block
@property (assign,getter=isShowingCompletions,nonatomic) BOOL showingCompletions;                                                //@synthesize showingCompletions=_showingCompletions - In the implementation block
@property (assign,getter=isShowingUniversalFirstTimeExperience,nonatomic) BOOL showingUniversalFirstTimeExperience;              //@synthesize showingUniversalFirstTimeExperience=_showingUniversalFirstTimeExperience - In the implementation block
@property (nonatomic,retain) UIWindow * detailWindow;                                                                            //@synthesize detailWindow=_detailWindow - In the implementation block
-(BOOL)isShowingCompletions;
-(void)setShowingCompletions:(BOOL)arg1 ;
-(void)setShowingUniversalFirstTimeExperience:(BOOL)arg1 ;
-(void)setFavoritesState:(long long)arg1 ;
-(UIWindow *)detailWindow;
-(void)setDetailWindow:(UIWindow *)arg1 ;
-(long long)favoritesState;
-(BOOL)isShowingUniversalFirstTimeExperience;
-(NSString *)queryString;
-(void)setQueryString:(NSString *)arg1 ;
@end

