/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, December 27, 2016 at 5:08:24 PM Japan Standard Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /Applications/MobileSafari.app/MobileSafari
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MobileSafari/MobileSafari-Structs.h>
#import <UIKit/UIView.h>
#import <MobileSafari/CloudTabItemViewDelegate.h>
#import <MobileSafari/ViewReuseManagerDelegate.h>

@protocol CloudTabTableDelegate;
@class WBSCloudTabDevice, CloudTabHeaderView, ViewReuseManager, WBSCloudTab, NSString;

@interface CloudTabTable : UIView <CloudTabItemViewDelegate, ViewReuseManagerDelegate> {

	long long _style;
	WBSCloudTabDevice* _device;
	CloudTabHeaderView* _headerView;
	unsigned long long _indexOfFocusedTab;
	ViewReuseManager* _itemViewReuseManager;
	NSRange _trackedItemViewRange;
	id<CloudTabTableDelegate> _delegate;
	WBSCloudTab* _focusedTab;
	double _offsetAboveFocusedTab;
	double _offsetBelowFocusedTab;
	/*^block*/id _layoutAnimator;
	CGRect _visibleRect;

}

@property (assign,nonatomic,__weak) id<CloudTabTableDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (assign,nonatomic) CGRect visibleRect;                                     //@synthesize visibleRect=_visibleRect - In the implementation block
@property (nonatomic,retain) WBSCloudTab * focusedTab;                               //@synthesize focusedTab=_focusedTab - In the implementation block
@property (assign,nonatomic) double offsetAboveFocusedTab;                           //@synthesize offsetAboveFocusedTab=_offsetAboveFocusedTab - In the implementation block
@property (assign,nonatomic) double offsetBelowFocusedTab;                           //@synthesize offsetBelowFocusedTab=_offsetBelowFocusedTab - In the implementation block
@property (nonatomic,copy) id layoutAnimator;                                        //@synthesize layoutAnimator=_layoutAnimator - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(CGRect)_rectForItemAtIndex:(unsigned long long)arg1 ;
-(void)_layoutItemView:(id)arg1 representingItemAtIndex:(unsigned long long)arg2 ;
-(void)_didSelectItemView:(id)arg1 ;
-(BOOL)_shouldShowSeparatorForItemViewAtIndex:(unsigned long long)arg1 ;
-(void)cloudTabItemViewDidStartEditing:(id)arg1 ;
-(void)cloudTabItemViewDidFinishEditing:(id)arg1 ;
-(void)cloudTabItemViewDeleteButtonWasTapped:(id)arg1 ;
-(void)cloudTabItemViewHighlightStateDidChange:(id)arg1 ;
-(void)viewReuseManager:(id)arg1 willRecycleView:(id)arg2 ;
-(void)viewReuseManager:(id)arg1 prepareView:(id)arg2 toRepresentObjectAtIndex:(unsigned long long)arg3 ;
-(id)initWithDevice:(id)arg1 style:(long long)arg2 ;
-(void)setFocusedTab:(WBSCloudTab *)arg1 ;
-(void)setOffsetAboveFocusedTab:(double)arg1 ;
-(void)setOffsetBelowFocusedTab:(double)arg1 ;
-(CGRect)rectForTab:(id)arg1 ;
-(WBSCloudTab *)focusedTab;
-(double)offsetAboveFocusedTab;
-(double)offsetBelowFocusedTab;
-(id)layoutAnimator;
-(void)setLayoutAnimator:(id)arg1 ;
-(void)layoutSubviews;
-(void)setDelegate:(id<CloudTabTableDelegate>)arg1 ;
-(CGSize)sizeThatFits:(CGSize)arg1 ;
-(id<CloudTabTableDelegate>)delegate;
-(CGRect)visibleRect;
-(void)setVisibleRect:(CGRect)arg1 ;
-(NSRange)_visibleItemRange;
@end

