/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, December 27, 2016 at 5:08:24 PM Japan Standard Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /Applications/MobileSafari.app/MobileSafari
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <SafariShared/WBSCloudTabStore.h>

@protocol CloudTabStoreDelegate;
@class WBSEncryptedCloudKeyValueStore, NSTimer;

@interface CloudTabStore : WBSCloudTabStore {

	WBSEncryptedCloudKeyValueStore* _syncedDevicesStore;
	WBSEncryptedCloudKeyValueStore* _userRequestsStore;
	NSTimer* _refreshTimer;
	long long _periodicUpdateRequestCount;
	id<CloudTabStoreDelegate> _delegate;

}

@property (assign,nonatomic,__weak) id<CloudTabStoreDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
+(id)cloudTabForTabDocument:(id)arg1 ;
-(void)synchronizeCloudTabDevices;
-(void)_syncedDevicesStoreDidUpdate:(id)arg1 ;
-(void)_userRequestsStoreDidUpdate:(id)arg1 ;
-(BOOL)cloudTabsAreEnabled;
-(void)_notifyCloudTabStoreDidUpdateWithType:(id)arg1 ;
-(void)clearTabsForCurrentDeviceWithCompletion:(/*^block*/id)arg1 ;
-(void)saveCurrentDeviceCloudTabs:(id)arg1 completion:(/*^block*/id)arg2 ;
-(BOOL)canSaveCloudTabsForCurrentDevice;
-(void)_removeConflictingDevice;
-(void)saveCurrentDeviceCloudTabs:(id)arg1 ;
-(void)_requestUpdateFromServer;
-(void)_refreshTimerDidFire:(id)arg1 ;
-(id)_storeForIdentifier:(long long)arg1 ;
-(void)startObservingTabStoreStateChanges;
-(void)stopObservingTabStoreStateChanges;
-(void)_cloudTabsEnabledDidChange;
-(void)_clearAllDevices;
-(void)saveCurrentDeviceTabsFromSuspendState;
-(void)startPerformingPeriodicUpdates;
-(void)stopPerformingPeriodicUpdates;
-(void)saveCurrentDeviceTabDocuments:(id)arg1 completion:(/*^block*/id)arg2 ;
-(id)init;
-(id)currentDevice;
-(void)setDelegate:(id<CloudTabStoreDelegate>)arg1 ;
-(id<CloudTabStoreDelegate>)delegate;
-(void)clearTabsForCurrentDevice;
-(id)_keyValueStoreDictionaryRepresentation:(long long)arg1 ;
-(void)_removeObjectFromKeyValueStore:(long long)arg1 forKey:(id)arg2 ;
-(id)_currentDeviceUUID;
-(void)_closeRequestedTabIfPossible:(id)arg1 ;
-(void)_setDictionaryInKeyValueStore:(long long)arg1 dictionary:(id)arg2 forKey:(id)arg3 ;
-(id)syncedCloudTabDevices;
-(BOOL)closeTab:(id)arg1 onDevice:(id)arg2 ;
-(BOOL)closeTabs:(id)arg1 onDevice:(id)arg2 ;
-(BOOL)closeAllTabsOnDevice:(id)arg1 ;
@end

