/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, December 27, 2016 at 5:08:24 PM Japan Standard Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /Applications/MobileSafari.app/MobileSafari
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MobileSafari/MobileSafari-Structs.h>
#import <UIKit/UIButton.h>
#import <UIKit/UIGestureRecognizerDelegate.h>

@protocol CloudTabItemViewDelegate;
@class UIView, UIPanGestureRecognizer, CloudTabItemDeleteConfirmationView, WBSCloudTab, NSString;

@interface CloudTabItemView : UIButton <UIGestureRecognizerDelegate> {

	UIView* _separatorView;
	UIView* _highlightView;
	BOOL _editing;
	double _startingSwipeOffset;
	double _swipeOffset;
	UIPanGestureRecognizer* _panGestureRecognizer;
	CloudTabItemDeleteConfirmationView* _deleteConfirmationView;
	double _leftEdgeInset;
	BOOL _editable;
	long long _style;
	id<CloudTabItemViewDelegate> _delegate;
	WBSCloudTab* _cloudTab;

}

@property (assign,nonatomic) long long style;                                           //@synthesize style=_style - In the implementation block
@property (assign,nonatomic,__weak) id<CloudTabItemViewDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (nonatomic,retain) WBSCloudTab * cloudTab;                                    //@synthesize cloudTab=_cloudTab - In the implementation block
@property (assign,getter=isEditable,nonatomic) BOOL editable;                           //@synthesize editable=_editable - In the implementation block
@property (assign,nonatomic) BOOL showsSeparator; 
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(double)defaultHeight;
-(WBSCloudTab *)cloudTab;
-(void)setCloudTab:(WBSCloudTab *)arg1 ;
-(void)setShowsSeparator:(BOOL)arg1 ;
-(void)_panRecognized:(id)arg1 ;
-(void)_setUpDeleteConfirmationViewIfNecessary;
-(double)_swipeOffsetFromPanGestureRecognizer;
-(BOOL)showsSeparator;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)layoutSubviews;
-(void)setDelegate:(id<CloudTabItemViewDelegate>)arg1 ;
-(void)dealloc;
-(CGSize)sizeThatFits:(CGSize)arg1 ;
-(id<CloudTabItemViewDelegate>)delegate;
-(BOOL)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2 ;
-(void)touchesBegan:(id)arg1 withEvent:(id)arg2 ;
-(void)touchesMoved:(id)arg1 withEvent:(id)arg2 ;
-(void)touchesEnded:(id)arg1 withEvent:(id)arg2 ;
-(void)touchesCancelled:(id)arg1 withEvent:(id)arg2 ;
-(BOOL)isEditable;
-(long long)style;
-(void)_updateStyle;
-(void)setStyle:(long long)arg1 ;
-(void)setHighlighted:(BOOL)arg1 ;
-(void)setHighlighted:(BOOL)arg1 animated:(BOOL)arg2 ;
-(void)setEditable:(BOOL)arg1 ;
-(CGRect)titleRectForContentRect:(CGRect)arg1 ;
-(void)_setEditing:(BOOL)arg1 animated:(BOOL)arg2 ;
-(void)_deleteButtonTapped:(id)arg1 ;
@end

