/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, December 27, 2016 at 5:08:24 PM Japan Standard Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /Applications/MobileSafari.app/MobileSafari
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol CompletionProviderDelegate;
@class NSMutableDictionary, NSMutableArray;

@interface CompletionProvider : NSObject {

	NSMutableDictionary* _completionsByString;
	NSMutableArray* _completedStringsInPruneOrder;
	BOOL _failing;
	BOOL _inCompletionsForString;
	id<CompletionProviderDelegate> _delegate;

}

@property (assign,nonatomic,__weak) id<CompletionProviderDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (getter=isFailing,nonatomic,readonly) BOOL failing;                             //@synthesize failing=_failing - In the implementation block
-(id)completionsForString:(id)arg1 ;
-(void)setCompletions:(id)arg1 forString:(id)arg2 ;
-(id)completionsForQuery:(id)arg1 ;
-(void)setStringToComplete:(id)arg1 ;
-(unsigned long long)maximumCachedCompletionCount;
-(void)clearCachedCompletions;
-(void)_pruneCachedCompletions;
-(BOOL)isFailing;
-(id)init;
-(void)setDelegate:(id<CompletionProviderDelegate>)arg1 ;
-(id<CompletionProviderDelegate>)delegate;
-(void)fail;
@end

