/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, December 27, 2016 at 5:08:24 PM Japan Standard Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /Applications/MobileSafari.app/MobileSafari
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

@class NSString;


@protocol CompletionItem <WBSCompletionListItem>
@property (nonatomic,copy) NSString * completionString; 
@property (nonatomic,readonly) NSString * completionTableHeaderViewReuseIdentifier; 
@property (assign,nonatomic) unsigned long long minimumRankOfTopHitToSuppressResult; 
@property (nonatomic,readonly) BOOL restoresSearchState; 
@property (nonatomic,retain) id<CompletionItemActionHandler> handlerForActionItem; 
@optional
-(BOOL)shouldPrefetchWithMatchLength:(unsigned long long)arg1;
-(BOOL)restoresSearchState;
-(NSString *)completionTableHeaderViewReuseIdentifier;
-(id)completionTableHeaderView;
-(void)configureCompletionTableHeaderView:(id)arg1 forCompletionList:(id)arg2;
-(id<CompletionItemActionHandler>)handlerForActionItem;
-(void)setCompletionString:(id)arg1;
-(void)setHandlerForActionItem:(id)arg1;
-(double)completionTableViewCellCustomHeightForCompletionList:(id)arg1;
-(id)originalURLString;
-(id)userVisibleURLString;
-(NSString *)completionString;
-(unsigned long long)minimumRankOfTopHitToSuppressResult;
-(void)setMinimumRankOfTopHitToSuppressResult:(unsigned long long)arg1;

@required
-(void)acceptCompletionWithActionHandler:(id)arg1;
-(id)completionTableViewCellForCompletionList:(id)arg1;
-(void)configureCompletionTableViewCell:(id)arg1 forCompletionList:(id)arg2;
-(void)auditAcceptedCompletionWithRank:(unsigned long long)arg1;
-(id)completionTableViewCellReuseIdentifier;
-(id)reflectedStringForUserTypedString:(id)arg1;

@end

