/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, December 27, 2016 at 5:08:24 PM Japan Standard Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /Applications/MobileSafari.app/MobileSafari
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MobileSafari/MobileSafari-Structs.h>
#import <UIKit/UIScrollViewDelegate.h>

@protocol ContinuousReadingViewControllerDelegate;
@class ContinuousReadingPreviewView, ContinuousReadingItem, SafariWebView, UIScrollView, UIView, ContinuousReadingBannerView, NSString;

@interface ContinuousReadingViewController : NSObject <UIScrollViewDelegate> {

	BOOL _suppressingAutoScroll;
	BOOL _committingToContinuousDocument;
	BOOL _scrollingToNextContinuousDocument;
	ContinuousReadingPreviewView* _previousItemPreviewView;
	ContinuousReadingPreviewView* _previewView;
	ContinuousReadingItem* _currentItem;
	SafariWebView* _currentWebView;
	id<ContinuousReadingViewControllerDelegate> _delegate;
	UIScrollView* _outerScrollView;

}

@property (setter=_setOuterScrollView:,getter=_outerScrollView,nonatomic,retain) UIScrollView * outerScrollView;               //@synthesize outerScrollView=_outerScrollView - In the implementation block
@property (nonatomic,retain,readonly) UIView * view; 
@property (nonatomic,retain) ContinuousReadingPreviewView * previousItemPreviewView;                                           //@synthesize previousItemPreviewView=_previousItemPreviewView - In the implementation block
@property (nonatomic,retain) ContinuousReadingPreviewView * previewView;                                                       //@synthesize previewView=_previewView - In the implementation block
@property (nonatomic,readonly) ContinuousReadingBannerView * topBannerView; 
@property (nonatomic,retain) ContinuousReadingItem * currentItem;                                                              //@synthesize currentItem=_currentItem - In the implementation block
@property (assign,nonatomic,__weak) SafariWebView * currentWebView;                                                            //@synthesize currentWebView=_currentWebView - In the implementation block
@property (assign,getter=isSuppressingAutoScroll,nonatomic) BOOL suppressingAutoScroll;                                        //@synthesize suppressingAutoScroll=_suppressingAutoScroll - In the implementation block
@property (getter=isCommittingToContinuousDocument,nonatomic,readonly) BOOL committingToContinuousDocument;                    //@synthesize committingToContinuousDocument=_committingToContinuousDocument - In the implementation block
@property (getter=isScrollingToNextContinuousDocument,nonatomic,readonly) BOOL scrollingToNextContinuousDocument;              //@synthesize scrollingToNextContinuousDocument=_scrollingToNextContinuousDocument - In the implementation block
@property (getter=isUserInteractingWithContainer,nonatomic,readonly) BOOL userInteractingWithContainer; 
@property (nonatomic,readonly) double scrollOffsetYForCurrentDocument; 
@property (assign,nonatomic,__weak) id<ContinuousReadingViewControllerDelegate> delegate;                                      //@synthesize delegate=_delegate - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(ContinuousReadingPreviewView *)previousItemPreviewView;
-(void)updateOuterScrollView;
-(ContinuousReadingBannerView *)topBannerView;
-(void)updateContinuousPreviewViewSizeAttributes;
-(BOOL)isScrollingToNextContinuousDocument;
-(BOOL)isCommittingToContinuousDocument;
-(void)setSuppressingAutoScroll:(BOOL)arg1 ;
-(void)innerScrollViewDidScroll:(id)arg1 ;
-(void)setCurrentWebView:(SafariWebView *)arg1 ;
-(void)didCreateWebViewForPreviousDocument:(id)arg1 ;
-(void)didCreateWebViewForNextDocument:(id)arg1 ;
-(BOOL)isUserInteractingWithContainer;
-(void)setPreviousItemPreviewView:(ContinuousReadingPreviewView *)arg1 ;
-(double)scrollOffsetYForCurrentDocument;
-(id)_outerScrollView;
-(void)_willCommitToContinuousDocumentInPreviewView:(id)arg1 ;
-(double)_scrollOffsetYForNextDocument;
-(void)_commitToNextContinuousDocument;
-(double)_scrollOffsetYForPreviousDocument;
-(void)_commitToPreviousContinuousDocument;
-(BOOL)isSuppressingAutoScroll;
-(void)_setOuterScrollView:(id)arg1 ;
-(void)setDelegate:(id<ContinuousReadingViewControllerDelegate>)arg1 ;
-(void)dealloc;
-(void)scrollViewDidScroll:(id)arg1 ;
-(void)scrollViewWillEndDragging:(id)arg1 withVelocity:(CGPoint)arg2 targetContentOffset:(inout CGPoint*)arg3 ;
-(void)scrollViewDidEndDecelerating:(id)arg1 ;
-(id<ContinuousReadingViewControllerDelegate>)delegate;
-(UIView *)view;
-(ContinuousReadingItem *)currentItem;
-(void)setCurrentItem:(ContinuousReadingItem *)arg1 ;
-(SafariWebView *)currentWebView;
-(ContinuousReadingPreviewView *)previewView;
-(void)setPreviewView:(ContinuousReadingPreviewView *)arg1 ;
@end

