/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, December 27, 2016 at 5:08:23 PM Japan Standard Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /Applications/MobileSafari.app/MobileSafari
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol ContinuousReadingViewControllerDelegate <NSObject>
@required
-(void)continuousReadingViewController:(id)arg1 scrollViewDidScroll:(id)arg2;
-(void)continuousReadingViewControllerWillCommitToLoadNextItem:(id)arg1;
-(void)continuousReadingViewControllerCommitToLoadPreviousItem:(id)arg1;
-(void)continuousReadingViewController:(id)arg1 didCommitToLoadItem:(id)arg2;
-(double)continuousReadingViewControllerNextWebViewLandingOffset:(id)arg1 includeBottomBar:(BOOL)arg2;

@end

