/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, December 27, 2016 at 5:08:24 PM Japan Standard Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /Applications/MobileSafari.app/MobileSafari
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MobileSafari/MobileSafari-Structs.h>
#import <UIKit/UIView.h>

@class NSMutableArray, NSMapTable, NSArray, UIImage;

@interface EvenlyDistributedImagesView : UIView {

	NSMutableArray* _imageViews;
	NSMutableArray* _imagePlacementConstraints;
	NSMapTable* _aspectRatioConstraints;
	NSMapTable* _absoluteSizeConstraints;
	NSArray* _widthConstraints;
	NSArray* _heightConstraints;
	BOOL _preserveAspectRatio;
	NSArray* _images;
	UIImage* _maskImage;
	double _fixedHeight;
	double _fixedWidth;
	double _horizontalSpaceBetweenImages;
	CGSize _absoluteImageSize;

}

@property (nonatomic,copy) NSArray * images;                                   //@synthesize images=_images - In the implementation block
@property (nonatomic,retain) UIImage * maskImage;                              //@synthesize maskImage=_maskImage - In the implementation block
@property (nonatomic,readonly) NSArray * imageViews;                           //@synthesize imageViews=_imageViews - In the implementation block
@property (assign,nonatomic) CGSize absoluteImageSize;                         //@synthesize absoluteImageSize=_absoluteImageSize - In the implementation block
@property (assign,nonatomic) double fixedHeight;                               //@synthesize fixedHeight=_fixedHeight - In the implementation block
@property (assign,nonatomic) double fixedWidth;                                //@synthesize fixedWidth=_fixedWidth - In the implementation block
@property (assign,nonatomic) double horizontalSpaceBetweenImages;              //@synthesize horizontalSpaceBetweenImages=_horizontalSpaceBetweenImages - In the implementation block
@property (assign,nonatomic) BOOL preserveAspectRatio;                         //@synthesize preserveAspectRatio=_preserveAspectRatio - In the implementation block
-(void)_setAspectRatioConstraintForImageView:(id)arg1 ;
-(void)_setAbsoluteSizeConstraintsForImageView:(id)arg1 ;
-(void)_setSizingConstraintsForImageView:(id)arg1 ;
-(void)_removeSizingConstraintsForImageView:(id)arg1 ;
-(void)setPreserveAspectRatio:(BOOL)arg1 ;
-(void)setAbsoluteImageSize:(CGSize)arg1 ;
-(void)setHorizontalSpaceBetweenImages:(double)arg1 ;
-(CGSize)absoluteImageSize;
-(double)horizontalSpaceBetweenImages;
-(BOOL)preserveAspectRatio;
-(NSArray *)images;
-(void)setImages:(NSArray *)arg1 ;
-(void)setMaskImage:(UIImage *)arg1 ;
-(NSArray *)imageViews;
-(void)setFixedWidth:(double)arg1 ;
-(void)setFixedHeight:(double)arg1 ;
-(UIImage *)maskImage;
-(double)fixedHeight;
-(double)fixedWidth;
-(void)_setUpConstraints;
@end

