/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, December 27, 2016 at 5:08:24 PM Japan Standard Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /Applications/MobileSafari.app/MobileSafari
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSArray;

@interface HistoryTableViewDataSourceChangeCollection : NSObject {

	NSArray* _insertChanges;
	NSArray* _deleteChanges;

}

@property (nonatomic,copy) NSArray * insertChanges;              //@synthesize insertChanges=_insertChanges - In the implementation block
@property (nonatomic,copy) NSArray * deleteChanges;              //@synthesize deleteChanges=_deleteChanges - In the implementation block
-(NSArray *)insertChanges;
-(NSArray *)deleteChanges;
-(void)setInsertChanges:(NSArray *)arg1 ;
-(void)setDeleteChanges:(NSArray *)arg1 ;
-(id)init;
@end

