/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, December 27, 2016 at 5:08:24 PM Japan Standard Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /Applications/MobileSafari.app/MobileSafari
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MobileSafari/MobileSafari-Structs.h>
#import <UIKit/UIToolbar.h>

@class UILabel, UIBarButtonItem, OpenInApplicationBarButtonItem, TabDocument;

@interface QuickLookBannerView : UIToolbar {

	UILabel* _filenameLabel;
	UIBarButtonItem* _flexibleSpaceItem;
	OpenInApplicationBarButtonItem* _openInApplicationItem;
	UIBarButtonItem* _openInOtherApplicationsItem;
	TabDocument* _tabDocument;

}

@property (assign,nonatomic,__weak) id<QuickLookBannerViewDelegate> quickLookDelegate; 
-(id)initWithTabDocument:(id)arg1 quickLookBannerViewDelegate:(id)arg2 ;
-(void)_layoutFilenameLabel;
-(void)_animateTo:(double)arg1 ;
-(void)setQuickLookDelegate:(id<QuickLookBannerViewDelegate>)arg1 ;
-(id<QuickLookBannerViewDelegate>)quickLookDelegate;
-(void)setFrame:(CGRect)arg1 ;
-(void)animateIn;
-(void)animateOut;
-(BOOL)updateWithQuickLookDocument:(id)arg1 ;
@end

