/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, December 27, 2016 at 5:08:24 PM Japan Standard Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /Applications/MobileSafari.app/MobileSafari
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MobileSafari/CompletionItem.h>

@class WebBookmark, SFSearchResult, NSString;

@interface ReadingListCompletionItem : NSObject <CompletionItem> {

	WebBookmark* _bookmark;
	SFSearchResult* _sfSearchResultValue;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (nonatomic,readonly) NSString * parsecDomainIdentifier; 
@property (nonatomic,readonly) SFSearchResult * sfSearchResultValue;                              //@synthesize sfSearchResultValue=_sfSearchResultValue - In the implementation block
@property (nonatomic,readonly) unsigned long long engagementDestination; 
@property (nonatomic,readonly) NSString * lastSearchQuery; 
@property (nonatomic,copy) NSString * completionString; 
@property (nonatomic,readonly) NSString * completionTableHeaderViewReuseIdentifier; 
@property (assign,nonatomic) unsigned long long minimumRankOfTopHitToSuppressResult; 
@property (nonatomic,readonly) BOOL restoresSearchState; 
@property (nonatomic,retain) id<CompletionItemActionHandler> handlerForActionItem; 
-(void)acceptCompletionWithActionHandler:(id)arg1 ;
-(id)completionTableViewCellForCompletionList:(id)arg1 ;
-(void)configureCompletionTableViewCell:(id)arg1 forCompletionList:(id)arg2 ;
-(void)auditAcceptedCompletionWithRank:(unsigned long long)arg1 ;
-(id)completionTableViewCellReuseIdentifier;
-(id)reflectedStringForUserTypedString:(id)arg1 ;
-(id)initWithReadingListBookmark:(id)arg1 ;
-(NSString *)parsecDomainIdentifier;
-(SFSearchResult *)sfSearchResultValue;
-(unsigned long long)engagementDestination;
@end

