/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, December 27, 2016 at 5:08:24 PM Japan Standard Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /Applications/MobileSafari.app/MobileSafari
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MobileSafari/MobileSafari-Structs.h>
#import <SafariServices/_SFPopoverSizingTableViewController.h>

@protocol RecentlyClosedTabViewControllerDelegate;
@interface RecentlyClosedTabViewController : _SFPopoverSizingTableViewController {

	id<RecentlyClosedTabViewControllerDelegate> _recentTabsDelegate;

}

@property (assign,nonatomic,__weak) id<RecentlyClosedTabViewControllerDelegate> recentTabsDelegate;              //@synthesize recentTabsDelegate=_recentTabsDelegate - In the implementation block
-(void)addRecentlyClosedTabDocument:(id)arg1 ;
-(void)removeAllRecentlyClosedTabDocuments;
-(id<RecentlyClosedTabViewControllerDelegate>)recentTabsDelegate;
-(void)setRecentTabsDelegate:(id<RecentlyClosedTabViewControllerDelegate>)arg1 ;
-(void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2 ;
-(long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2 ;
-(id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2 ;
-(id)tableView:(id)arg1 titleForHeaderInSection:(long long)arg2 ;
-(void)loadView;
-(CGSize)preferredContentSize;
-(id)initWithStyle:(long long)arg1 ;
-(void)doneButtonTapped;
-(id)recentlyClosedTabs;
@end

