/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, December 27, 2016 at 5:08:24 PM Japan Standard Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /Applications/MobileSafari.app/MobileSafari
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MobileSafari/MobileSafari-Structs.h>
#import <MobileSafari/PurplePageLoadTestRunner.h>

@interface ReplayPagesTestRunner : PurplePageLoadTestRunner {

	_sFILE* _suiteFile;
	unsigned long long _attemptCount;
	unsigned long long _successCount;
	BOOL _eternal;

}

@property (assign,nonatomic) BOOL eternal;              //@synthesize eternal=_eternal - In the implementation block
-(void)finishedTestPage:(id)arg1 ;
-(BOOL)loadTestSuiteFile:(id)arg1 ;
-(void)startNextPage;
-(BOOL)eternal;
-(void)setEternal:(BOOL)arg1 ;
-(void)dealloc;
@end

