/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, December 27, 2016 at 5:08:24 PM Japan Standard Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /Applications/MobileSafari.app/MobileSafari
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol OS_dispatch_queue;
@class NSArray, NSObject, NSString, NSDictionary;

@interface SearchEngineController : NSObject {

	NSArray* _searchEngines;
	unsigned long long _defaultSearchEngineIndex;
	NSObject*<OS_dispatch_queue> _searchEngineArrayAccessQueue;
	NSString* _countryCode;
	NSDictionary* _templateParameterValues;
	NSDictionary* _carrierTemplateParameterValues;

}

@property (nonatomic,copy,readonly) NSArray * engines; 
@property (nonatomic,readonly) NSString * countryCode;                                     //@synthesize countryCode=_countryCode - In the implementation block
@property (nonatomic,readonly) NSDictionary * templateParameterValues;                     //@synthesize templateParameterValues=_templateParameterValues - In the implementation block
@property (nonatomic,readonly) NSDictionary * carrierTemplateParameterValues;              //@synthesize carrierTemplateParameterValues=_carrierTemplateParameterValues - In the implementation block
+(void)_initializeSharedInstance;
+(id)sharedInstanceIfAvailable;
+(id)sharedInstance;
-(void)reloadSearchEngines;
-(id)defaultSearchEngine;
-(void)_populateSearchEngines;
-(void)_setEngines:(id)arg1 defaultSearchEngineIndex:(unsigned long long)arg2 ;
-(void)_loadSystemProperties;
-(unsigned long long)_addWebSearchProvidersToArray:(id)arg1 ;
-(void)_addSpecialSearchEnginesToArray:(id)arg1 ;
-(void)_readDefaultSearchEngine;
-(id)_existingEngineInfoFor:(id)arg1 ;
-(void)_setDefaultSearchEngine:(id)arg1 ;
-(void)_getEngines:(inout id*)arg1 defaultSearchEngineIndex:(inout unsigned long long*)arg2 ;
-(id)engineInfoFor:(id)arg1 ;
-(id)engineInfoForScriptName:(id)arg1 ;
-(id)safeSearchRequestForSearchRequest:(id)arg1 ;
-(NSDictionary *)templateParameterValues;
-(NSDictionary *)carrierTemplateParameterValues;
-(id)init;
-(id)description;
-(NSArray *)engines;
-(NSString *)countryCode;
@end

