/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, December 27, 2016 at 5:08:24 PM Japan Standard Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /Applications/MobileSafari.app/MobileSafari
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MobileSafari/VibrantTableViewCell.h>

@protocol SharedLinksSubscriptionsTableViewCellDelegate;
@class UIImageView, NSIndexPath;

@interface SharedLinksSubscriptionsTableViewCell : VibrantTableViewCell {

	UIImageView* _serviceIconView;
	id<SharedLinksSubscriptionsTableViewCellDelegate> _delegate;
	NSIndexPath* _indexPathToWorkAround19506053;

}

@property (assign,nonatomic) id<SharedLinksSubscriptionsTableViewCellDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (nonatomic,retain) NSIndexPath * indexPathToWorkAround19506053;                             //@synthesize indexPathToWorkAround19506053=_indexPathToWorkAround19506053 - In the implementation block
-(void)setIndexPathToWorkAround19506053:(NSIndexPath *)arg1 ;
-(void)setUsesSwitchControl:(BOOL)arg1 isOn:(BOOL)arg2 ;
-(void)setServiceIcon:(id)arg1 ;
-(NSIndexPath *)indexPathToWorkAround19506053;
-(void)_subscriptionToggled:(id)arg1 ;
-(void)setDelegate:(id<SharedLinksSubscriptionsTableViewCellDelegate>)arg1 ;
-(id<SharedLinksSubscriptionsTableViewCellDelegate>)delegate;
@end

