/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, December 27, 2016 at 5:08:24 PM Japan Standard Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /Applications/MobileSafari.app/MobileSafari
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UIViewController.h>
#import <MobileSafari/WBSAutomaticReadingListFallbackIconProvider.h>
#import <MobileSafari/BookmarksToolbarItemProvider.h>
#import <MobileSafari/PreviewTableViewControllerDelegate.h>
#import <MobileSafari/SharedLinksSubscriptionsViewControllerDelegate.h>
#import <MobileSafari/SocialLinksTableViewCellDelegate.h>
#import <MobileSafari/BookmarksPanelStateRestoring.h>
#import <UIKit/UITableViewDelegate.h>
#import <UIKit/UITableViewDataSource.h>

@protocol SocialLinksViewControllerDelegate, LinkPreviewProvider;
@class PreviewTableViewController, NSMutableArray, _UIContentUnavailableView, UIBarButtonItem, NSString;

@interface SocialLinksViewController : UIViewController <WBSAutomaticReadingListFallbackIconProvider, BookmarksToolbarItemProvider, PreviewTableViewControllerDelegate, SharedLinksSubscriptionsViewControllerDelegate, SocialLinksTableViewCellDelegate, BookmarksPanelStateRestoring, UITableViewDelegate, UITableViewDataSource> {

	PreviewTableViewController* _tableViewController;
	NSMutableArray* _cachedItems;
	_UIContentUnavailableView* _explanationView;
	UIBarButtonItem* _subscriptionsButton;
	BOOL _forceCallToRequestCompleted;
	BOOL _finishedFirstRequest;
	id<SocialLinksViewControllerDelegate> _delegate;
	id<LinkPreviewProvider> _linkPreviewProvider;

}

@property (assign,nonatomic,__weak) id<SocialLinksViewControllerDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (assign,nonatomic,__weak) id<LinkPreviewProvider> linkPreviewProvider;                 //@synthesize linkPreviewProvider=_linkPreviewProvider - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
@property (nonatomic,readonly) NSString * collectionType; 
+(void)initialize;
+(BOOL)hasAnyAccount;
+(void)getFallbackIconForAutomaticReadingListItem:(id)arg1 completionBlock:(/*^block*/id)arg2 ;
-(id)bookmarksNavigationController;
-(id<LinkPreviewProvider>)linkPreviewProvider;
-(void)setLinkPreviewProvider:(id<LinkPreviewProvider>)arg1 ;
-(id)currentStateDictionary;
-(BOOL)restoreStateWithDictionary:(id)arg1 ;
-(double)currentScrollPosition;
-(void)restoreScrollPosition:(double)arg1 ;
-(id)bookmarksRightBarButtonItem;
-(void)updateCurrentSelectedItemIfNeeded;
-(id)safari_tableViewScrollPositionSaveIdentifier;
-(id)sharedLinksSubscriptionsViewControllerCurrentWebFeedURL:(id)arg1 ;
-(void)sharedLinksSubscriptionsViewControllerSubscribeToCurrentWebFeed:(id)arg1 ;
-(id)sharedLinksSubscriptionsViewControllerServiceIconForAccount:(id)arg1 ;
-(id)previewTableViewController:(id)arg1 URLForRowAtIndexPath:(id)arg2 ;
-(void)_clearExplanationView;
-(void)_showExplanationView;
-(id)safari_tableViewForScrollPositionSaving;
-(void)_itemsChanged:(id)arg1 ;
-(void)_requestCompleted:(id)arg1 ;
-(void)_contentSizeDidChange:(id)arg1 ;
-(void)refreshStateChanged:(id)arg1 ;
-(void)_requestMoreItemsFromAllSources;
-(id)_currentAutomaticReadingListItem;
-(void)_updateExplanationViewVisibility;
-(void)_didPressSubscriptionsButton;
-(id)_serviceIconForSource:(id)arg1 ;
-(id)socialLinksTableViewCell:(id)arg1 serviceImageForReadingListItem:(id)arg2 ;
-(void)socialLinksTableViewCellProfilePictureWasTapped:(id)arg1 ;
-(id)init;
-(void)setDelegate:(id<SocialLinksViewControllerDelegate>)arg1 ;
-(void)dealloc;
-(void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3 ;
-(void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2 ;
-(long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2 ;
-(id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2 ;
-(void)traitCollectionDidChange:(id)arg1 ;
-(id<SocialLinksViewControllerDelegate>)delegate;
-(void)loadView;
-(void)viewWillAppear:(BOOL)arg1 ;
-(void)viewDidAppear:(BOOL)arg1 ;
-(void)viewWillDisappear:(BOOL)arg1 ;
-(void)_accountsChanged:(id)arg1 ;
-(NSString *)collectionType;
@end

