/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, December 27, 2016 at 5:08:23 PM Japan Standard Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /Applications/MobileSafari.app/MobileSafari
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol TabDocumentDelegate
@required
-(void)removeAppBannerFromTabDocument:(id)arg1 animated:(BOOL)arg2;
-(void)tabDocumentDidUpdateShowingContinuous:(id)arg1;
-(void)tabDocumentDidUpdatePersistentState:(id)arg1;
-(void)tabDocumentDidStartLoading:(id)arg1;
-(void)tabDocumentWillStartLoadFromUserClick:(id)arg1;
-(BOOL)tabDocumentCanDownloadFile:(id)arg1;
-(BOOL)tabDocumentCanRedirectToExternalApplication:(id)arg1;
-(void)tabDocumentDidCancelRedirectToExternalApplication:(id)arg1;
-(void)tabDocument:(id)arg1 didFinishLoadingWithError:(BOOL)arg2;
-(void)tabDocumentDidChangeLocationWithinPageForMainFrame:(id)arg1;
-(void)tabDocumentDidUpdateTitle:(id)arg1;
-(void)tabDocumentDidUpdateBackForward:(id)arg1;
-(void)tabDocument:(id)arg1 progressChanged:(float)arg2;
-(void)tabDocumentStartedLoadingResource:(id)arg1;
-(void)tabDocumentFluidProgressRocketAnimationDidComplete:(id)arg1;
-(void)tabDocumentStoppedLoadingResource:(id)arg1;
-(void)tabDocument:(id)arg1 didReceiveAuthenticationChallenge:(id)arg2 completionHandler:(/*^block*/id)arg3;
-(BOOL)tabDocumentShouldHandleCertificateError:(id)arg1;
-(BOOL)tabDocumentCanShowJavaScriptAlertConfirmOrTextInput:(id)arg1;
-(void)showAlertForTabDocument:(id)arg1;
-(void)hideAlertForTabDocument:(id)arg1;
-(void)tabDocument:(id)arg1 didDetectReaderAvailability:(BOOL)arg2;
-(void)tabDocument:(id)arg1 didCreateNewTabDocument:(id)arg2;
-(BOOL)tabDocumentShouldBlockPopUp:(id)arg1;
-(void)tabDocument:(id)arg1 didCreatePreviewDocument:(id)arg2;
-(void)tabDocumentCommitPreviewedDocument:(id)arg1;
-(void)tabDocumentCommitPreviewedDocumentAsNewTab:(id)arg1 inBackground:(BOOL)arg2;
-(void)tabDocumentDidDimissPreviewedDocument:(id)arg1;
-(BOOL)tabDocumentSupportsOpenInNewWindow:(id)arg1;
-(BOOL)tabDocumentCanBecomeCurrentUserActivity:(id)arg1;
-(BOOL)tabDocumentDidBecomeActiveDueToWindowArrangementChanges:(id)arg1;
-(id)blankTabTitleForTabDocument:(id)arg1;
-(void)composeEmailWithMailToURL:(id)arg1 forTabDocument:(id)arg2;
-(void)tabDocumentDidCompleteCheckForAppBanner:(id)arg1;
-(void)setAppBannerPinnedToTop:(BOOL)arg1 forTabDocument:(id)arg2;
-(void)tabDocumentDidBeginNavigationGesture:(id)arg1;
-(void)tabDocumentWillEndNavigationGesture:(id)arg1 withNavigationToBackForwardListItem:(id)arg2;
-(void)tabDocumentDidEndNavigationGesture:(id)arg1 withNavigationToBackForwardListItem:(id)arg2;
-(void)tabDocument:(id)arg1 presentViewControllerAnimated:(id)arg2;
-(long long)tabDocumentOrderIndex:(id)arg1;
-(id)tabDocumentSavedSessionStateData:(id)arg1;

@end

