/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, December 27, 2016 at 5:08:24 PM Japan Standard Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /Applications/MobileSafari.app/MobileSafari
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MobileSafari/MobileSafari-Structs.h>
#import <UIKit/UIView.h>

@class _UIBackdropView, TabBarItemView, TabOverviewItemView;

@interface TabDragView : UIView {

	double _tabHeight;
	_UIBackdropView* _backdropView;
	BOOL _hasDarkBackground;
	TabBarItemView* _tabBarItemView;
	TabOverviewItemView* _tabOverviewItemView;
	unsigned long long _presentationType;
	CGSize _contentsSize;

}

@property (nonatomic,readonly) TabBarItemView * tabBarItemView;                        //@synthesize tabBarItemView=_tabBarItemView - In the implementation block
@property (nonatomic,readonly) TabOverviewItemView * tabOverviewItemView;              //@synthesize tabOverviewItemView=_tabOverviewItemView - In the implementation block
@property (assign,nonatomic) CGSize contentsSize;                                      //@synthesize contentsSize=_contentsSize - In the implementation block
@property (assign,nonatomic) BOOL hasDarkBackground;                                   //@synthesize hasDarkBackground=_hasDarkBackground - In the implementation block
@property (assign,nonatomic) unsigned long long presentationType;                      //@synthesize presentationType=_presentationType - In the implementation block
-(void)setContentsSize:(CGSize)arg1 ;
-(void)setPresentationType:(unsigned long long)arg1 ;
-(TabBarItemView *)tabBarItemView;
-(TabOverviewItemView *)tabOverviewItemView;
-(CGSize)contentsSize;
-(void)_updatePresentationType;
-(void)layoutSubviews;
-(id)initWithTabBar:(id)arg1 ;
-(unsigned long long)presentationType;
-(void)setHasDarkBackground:(BOOL)arg1 ;
-(BOOL)hasDarkBackground;
@end

