/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, December 27, 2016 at 5:08:24 PM Japan Standard Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /Applications/MobileSafari.app/MobileSafari
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol OS_dispatch_queue;
@class NSMapTable, NSMutableDictionary, NSString, NSObject;

@interface TabSnapshotCache : NSObject {

	NSMapTable* _delegateToContextMap;
	unsigned long long _currentlyRequestedSnapshotCount;
	NSMutableDictionary* _snapshots;
	BOOL _updating;
	NSString* _thumbnailCacheDirectoryPath;
	NSObject*<OS_dispatch_queue> _fileSystemAccessQueue;
	BOOL _currentlyRequestingNextSnapshot;
	BOOL _needsRequestNextSnapshot;

}

@property (nonatomic,copy) NSString * thumbnailCacheDirectoryPath; 
@property (getter=isFinishedUpdating,nonatomic,readonly) BOOL finishedUpdating; 
+(void)removeSavedSnapshotsKeepingSnapshotsWithIdentifiers:(id)arg1 ;
+(id)defaultSnapshotCache;
+(unsigned long long)maximumSnapshotCacheCapacity;
+(void)initialize;
-(id)snapshotWithIdentifier:(id)arg1 ;
-(BOOL)hasValidSnapshotWithIdentifier:(id)arg1 ;
-(void)setIdentifiersToCache:(id)arg1 forDelegate:(id)arg2 ;
-(void)invalidateSnapshotWithIdentifier:(id)arg1 ;
-(void)setUpdating:(BOOL)arg1 forDelegate:(id)arg2 ;
-(void)setCapacity:(unsigned long long)arg1 forDelegate:(id)arg2 ;
-(BOOL)isFinishedUpdating;
-(void)_requestNextSnapshotIfNecessary;
-(id)_pathForSavedSnapshotWithIdentifier:(id)arg1 extension:(id)arg2 ;
-(id)_pathForSavedPNGSnapshotWithIdentifier:(id)arg1 ;
-(id)identifiersToCacheForDelegate:(id)arg1 ;
-(id)_contextForDelegate:(id)arg1 ;
-(id)_pathForSavedSnapshotWithIdentifier:(id)arg1 ;
-(void)_beginUpdatingStateForIdentifier:(id)arg1 ;
-(void)_finishUpdatingToState:(long long)arg1 forIdentifier:(id)arg2 ;
-(void)_finishUpdatingToState:(long long)arg1 cachedSnapshot:(id)arg2 forIdentifier:(id)arg3 ;
-(void)_sendDidFinishUpdatingToDelegateIfNeeded;
-(id)_allIdentifiersToCache;
-(void)_determineInitialStateForIdentifier:(id)arg1 ;
-(void)_saveSnapshotForIdentifier:(id)arg1 ;
-(void)_requestSavedSnapshotForIdentifier:(id)arg1 ;
-(void)_requestNextSnapshotIfNecessaryForDelegate:(id)arg1 ;
-(void)setThumbnailCacheDirectoryPath:(NSString *)arg1 ;
-(NSString *)thumbnailCacheDirectoryPath;
-(id)init;
-(void)dealloc;
-(id)debugDescription;
-(void)_didReceiveMemoryWarning:(id)arg1 ;
@end

