/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, December 27, 2016 at 5:08:24 PM Japan Standard Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /Applications/MobileSafari.app/MobileSafari
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MobileSafari/MobileSafari-Structs.h>
#import <MobileSafari/BrowserPopoverPresentationDelegate.h>

@interface TabViewPopoverPresentationDelegate : BrowserPopoverPresentationDelegate {

	long long _buttonIdentifier;

}
-(id)initWithPopoverPresentationController:(id)arg1 browserController:(id)arg2 buttonIdentifier:(long long)arg3 ;
-(id)sourceView;
-(CGRect)sourceRect;
@end

