/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, December 27, 2016 at 5:08:24 PM Japan Standard Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /Applications/MobileSafari.app/MobileSafari
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <MobileSafari/MobileSafari-Structs.h>
@class UIImage, UIView, TiltedTabThumbnailView, TiltedTabView, TiltedTabItem, UIButton, NSString, UIColor;

@interface TiltedTabItemLayoutInfo : NSObject {

	BOOL _closeButtonUsesOutlineStyle;
	BOOL _reordering;
	BOOL _closing;
	BOOL _finishedClosing;
	UIImage* _blankSnapshot;
	double _borrowedContentScale;
	UIView* _borrowedContentView;
	double _contentOpacity;
	TiltedTabThumbnailView* _contentView;
	double _topBackdropHeight;
	TiltedTabView* _tiltedTabView;
	TiltedTabItem* _item;
	long long _transition;
	unsigned long long _indexForLayout;
	unsigned long long _countForLayout;
	double _verticalScrollAdjustment;
	CGRect _closeButtonHitRect;
	CGRect _contentFrame;
	CATransform3D _contentTransform;

}

@property (nonatomic,retain) UIImage * blankSnapshot;                                    //@synthesize blankSnapshot=_blankSnapshot - In the implementation block
@property (assign,nonatomic) double borrowedContentScale;                                //@synthesize borrowedContentScale=_borrowedContentScale - In the implementation block
@property (nonatomic,retain) UIView * borrowedContentView;                               //@synthesize borrowedContentView=_borrowedContentView - In the implementation block
@property (nonatomic,readonly) UIButton * closeButton; 
@property (assign,nonatomic) CGRect closeButtonHitRect;                                  //@synthesize closeButtonHitRect=_closeButtonHitRect - In the implementation block
@property (assign,nonatomic) BOOL closeButtonUsesOutlineStyle;                           //@synthesize closeButtonUsesOutlineStyle=_closeButtonUsesOutlineStyle - In the implementation block
@property (nonatomic,readonly) CGRect contentClipperBounds; 
@property (assign,nonatomic) CGRect contentFrame;                                        //@synthesize contentFrame=_contentFrame - In the implementation block
@property (assign,nonatomic) double contentOpacity;                                      //@synthesize contentOpacity=_contentOpacity - In the implementation block
@property (assign,nonatomic) CATransform3D contentTransform;                             //@synthesize contentTransform=_contentTransform - In the implementation block
@property (nonatomic,retain) TiltedTabThumbnailView * contentView;                       //@synthesize contentView=_contentView - In the implementation block
@property (nonatomic,readonly) UIView * contentShadowView; 
@property (nonatomic,readonly) UIView * contentClipperView; 
@property (assign,nonatomic) double topBackdropHeight;                                   //@synthesize topBackdropHeight=_topBackdropHeight - In the implementation block
@property (nonatomic,__weak,readonly) TiltedTabView * tiltedTabView;                     //@synthesize tiltedTabView=_tiltedTabView - In the implementation block
@property (nonatomic,__weak,readonly) TiltedTabItem * item;                              //@synthesize item=_item - In the implementation block
@property (nonatomic,copy) NSString * title; 
@property (nonatomic,copy) UIColor * titleColor; 
@property (assign,getter=isReordering,nonatomic) BOOL reordering;                        //@synthesize reordering=_reordering - In the implementation block
@property (assign,getter=isClosing,nonatomic) BOOL closing;                              //@synthesize closing=_closing - In the implementation block
@property (assign,getter=isFinishedClosing,nonatomic) BOOL finishedClosing;              //@synthesize finishedClosing=_finishedClosing - In the implementation block
@property (assign,nonatomic) long long transition;                                       //@synthesize transition=_transition - In the implementation block
@property (assign,nonatomic) unsigned long long indexForLayout;                          //@synthesize indexForLayout=_indexForLayout - In the implementation block
@property (assign,nonatomic) unsigned long long countForLayout;                          //@synthesize countForLayout=_countForLayout - In the implementation block
@property (assign,nonatomic) double verticalScrollAdjustment;                            //@synthesize verticalScrollAdjustment=_verticalScrollAdjustment - In the implementation block
-(void)setBorrowedContentView:(UIView *)arg1 ;
-(UIView *)borrowedContentView;
-(TiltedTabView *)tiltedTabView;
-(void)setClosing:(BOOL)arg1 ;
-(UIView *)contentShadowView;
-(UIView *)contentClipperView;
-(void)tearDownThumbnailView;
-(void)_updateCloseButtonImage;
-(void)updateSnapshotViewAnimated:(BOOL)arg1 ;
-(CGRect)contentClipperBounds;
-(CGRect)clippedContentFrame;
-(void)_updateBorrowedContentFrame;
-(void)setUpThumbnailView;
-(id)initWithTiltedTabView:(id)arg1 item:(id)arg2 ;
-(void)setBlankSnapshot:(UIImage *)arg1 ;
-(void)setBorrowedContentScale:(double)arg1 ;
-(void)setCloseButtonUsesOutlineStyle:(BOOL)arg1 ;
-(UIImage *)blankSnapshot;
-(double)borrowedContentScale;
-(CGRect)closeButtonHitRect;
-(void)setCloseButtonHitRect:(CGRect)arg1 ;
-(BOOL)closeButtonUsesOutlineStyle;
-(double)contentOpacity;
-(void)setContentOpacity:(double)arg1 ;
-(CATransform3D)contentTransform;
-(void)setContentTransform:(CATransform3D)arg1 ;
-(double)topBackdropHeight;
-(void)setTopBackdropHeight:(double)arg1 ;
-(BOOL)isFinishedClosing;
-(void)setFinishedClosing:(BOOL)arg1 ;
-(unsigned long long)indexForLayout;
-(void)setIndexForLayout:(unsigned long long)arg1 ;
-(unsigned long long)countForLayout;
-(void)setCountForLayout:(unsigned long long)arg1 ;
-(double)verticalScrollAdjustment;
-(void)setVerticalScrollAdjustment:(double)arg1 ;
-(void)setContentView:(TiltedTabThumbnailView *)arg1 ;
-(TiltedTabThumbnailView *)contentView;
-(void)dealloc;
-(void)setTitle:(NSString *)arg1 ;
-(TiltedTabItem *)item;
-(NSString *)title;
-(void)setTransition:(long long)arg1 ;
-(long long)transition;
-(void)setTitleColor:(UIColor *)arg1 ;
-(UIColor *)titleColor;
-(UIButton *)closeButton;
-(void)setContentFrame:(CGRect)arg1 ;
-(BOOL)isClosing;
-(CGRect)contentFrame;
-(void)setReordering:(BOOL)arg1 ;
-(BOOL)isReordering;
@end

