/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, December 27, 2016 at 5:08:24 PM Japan Standard Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /Applications/MobileSafari.app/MobileSafari
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MobileSafari/MobileSafari-Structs.h>
#import <UIKit/UIView.h>
#import <MobileSafari/CloudTabTableDelegate.h>
#import <UIKit/UIGestureRecognizerDelegate.h>
#import <UIKit/UIScrollViewDelegate.h>
#import <libobjc.A.dylib/_UIBasicAnimationFactory.h>
#import <UIKit/UIInteractionProgressObserver.h>
#import <libobjc.A.dylib/CAAnimationDelegate.h>

@protocol TiltedTabViewDelegate;
@class UIPanGestureRecognizer, UILongPressGestureRecognizer, UITapGestureRecognizer, UIScrollView, ViewReuseManager, GradientView, TiltedTabItem, UIView, UIPreviewForceInteractionProgress, HighlightRecognizer, ReorderingAutoscroller, NSArray, NSMutableSet, WBSCloudTab, CloudTabTable, CloudTabItemView, NSTimer, UIImage, TabExplanationView, NSString;

@interface TiltedTabView : UIView <CloudTabTableDelegate, UIGestureRecognizerDelegate, UIScrollViewDelegate, _UIBasicAnimationFactory, UIInteractionProgressObserver, CAAnimationDelegate> {

	BOOL _presented;
	BOOL _sentDidDismissToDelegate;
	BOOL _sentDidPresentToDelegate;
	UIPanGestureRecognizer* _tabCloseRecognizer;
	UILongPressGestureRecognizer* _tabReorderRecognizer;
	UITapGestureRecognizer* _tabSelectionRecognizer;
	UIScrollView* _scrollView;
	BOOL _suppressingScrollViewDidScroll;
	ViewReuseManager* _viewReuseManager;
	GradientView* _statusBarGradient;
	unsigned long long _activeAnimationCount;
	TiltedTabItem* _animatingItem;
	BOOL _startedAnimatingItem;
	UIView* _animatingTopBackdropView;
	TiltedTabItem* _itemToScrollIntoView;
	BOOL _topBackdropViewHidden;
	UILongPressGestureRecognizer* _tabPreviewRecognizer;
	UILongPressGestureRecognizer* _tabCommitRecognizer;
	long long _currentTabPreviewState;
	TiltedTabItem* _interactivelyPreviewingItem;
	double _tabPreviewProgress;
	double _tabReadyToCommitProgress;
	UIPreviewForceInteractionProgress* _tabPreviewInteractionProgress;
	UIPreviewForceInteractionProgress* _tabReadyToCommitInteractionProgress;
	TiltedTabItem* _interactivelyClosingItem;
	double _interactiveCloseProgress;
	double _interactiveCloseVelocity;
	TiltedTabItem* _onlyHorizontalVelocityItem;
	BOOL _applyVelocityOnlyToHorizontalPosition;
	TiltedTabItem* _pressedItem;
	HighlightRecognizer* _pressRecognizer;
	TiltedTabItem* _interactivelyReorderingItem;
	double _interactiveReorderOffsetDistanceFromTouch;
	double _interactiveReorderOffset;
	BOOL _reorderOffsetNeedsReset;
	BOOL _itemsReordered;
	ReorderingAutoscroller* _reorderingAutoscroller;
	NSArray* _itemsInvolvedInAnimation;
	NSMutableSet* _itemsCurrentlyClosing;
	NSArray* _itemsInvolvedInTransition;
	TiltedTabItem* _visiblyCenteredItem;
	BOOL _scrollingToTop;
	UIView* _cloudTabContainer;
	NSArray* _cloudTabDevices;
	NSArray* _cloudTabTables;
	WBSCloudTab* _selectedCloudTab;
	CloudTabTable* _selectedCloudTabTable;
	CloudTabItemView* _editedCloudTabItemView;
	BOOL _cloudTabsNeedLayout;
	NSTimer* _itemActivationTimer;
	UIImage* _blankSnapshot;
	UIView* _bottomMaskView;
	TabExplanationView* _explanationView;
	BOOL _explanationViewVisible;
	BOOL _defersActivation;
	id<TiltedTabViewDelegate> _delegate;
	NSArray* _items;
	TiltedTabItem* _itemToActivate;
	TiltedTabItem* _itemToAdd;

}

@property (assign,nonatomic,__weak) id<TiltedTabViewDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (nonatomic,copy) NSArray * items;                                          //@synthesize items=_items - In the implementation block
@property (assign,getter=isPresented,nonatomic) BOOL presented;                      //@synthesize presented=_presented - In the implementation block
@property (nonatomic,retain) TiltedTabItem * itemToActivate;                         //@synthesize itemToActivate=_itemToActivate - In the implementation block
@property (assign,nonatomic) BOOL defersActivation;                                  //@synthesize defersActivation=_defersActivation - In the implementation block
@property (nonatomic,retain) TiltedTabItem * itemToAdd;                              //@synthesize itemToAdd=_itemToAdd - In the implementation block
@property (nonatomic,readonly) BOOL showsExplanationView; 
@property (nonatomic,readonly) double desiredSnapshotScale; 
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)_snapshotForItem:(id)arg1 ;
-(void)setPresented:(BOOL)arg1 animated:(BOOL)arg2 ;
-(void)cloudTabTable:(id)arg1 didSelectCloudTab:(id)arg2 ;
-(void)cloudTabTable:(id)arg1 didStartEditingTabItemView:(id)arg2 ;
-(void)cloudTabTable:(id)arg1 didFinishEditingTabItemView:(id)arg2 ;
-(void)cloudTabTable:(id)arg1 closeCloudTab:(id)arg2 onDevice:(id)arg3 ;
-(id)_requestReusableTiltedTabThumbnailView;
-(void)_closeButtonPressed:(id)arg1 ;
-(void)_relinquishReusableTiltedTabThumbnailView:(id)arg1 ;
-(void)_tabPressUpdated:(id)arg1 ;
-(void)_tabCloseRecognized:(id)arg1 ;
-(void)_tabReorderRecognized:(id)arg1 ;
-(void)_tabPreviewGestureRecognized:(id)arg1 ;
-(void)_tabCommitGestureRecognized:(id)arg1 ;
-(void)_tabSelectionRecognized:(id)arg1 ;
-(void)_relinquishBorrowedContent;
-(void)_sendPresentedStateDidChangeToDelegateIfNeeded;
-(double)_scrollingEffectFactorForTabsWithCount:(double)arg1 ;
-(double)_baseOffsetForItem:(id)arg1 index:(unsigned long long*)arg2 count:(double*)arg3 ;
-(double)_baseOffsetForCloudTabViews;
-(double)_topAreaHeightForTabsWithCount:(double)arg1 ;
-(CGRect)_tabLayoutBounds;
-(CGRect)_hitRectForItem:(id)arg1 ;
-(void)_layoutItemsAnimated:(BOOL)arg1 ;
-(id)_tiltedTabItemForLocation:(CGPoint)arg1 ;
-(void)_setPressedItem:(id)arg1 animated:(BOOL)arg2 ;
-(BOOL)_gestureRecognizer:(id)arg1 shouldInteractWithItem:(id)arg2 ;
-(double)_tabCloseAnimationSlideDistance;
-(double)_spaceBetweenTabsWithCount:(double)arg1 ;
-(void)_resetInteractiveReorderOffsetAtLocation:(CGPoint)arg1 ;
-(void)_updateTabPreviewProgress:(double)arg1 ;
-(void)_updateReorderGesture;
-(void)_stopTabReordering;
-(void)_stopTabPreviewing;
-(void)_activateItemToActivate;
-(void)_updateItemsInvolvedInAnimation;
-(void)_attemptToRelinquishBorrowedContentEarly;
-(void)_setItemActivationTimer:(id)arg1 ;
-(void)setItemToActivate:(TiltedTabItem *)arg1 ;
-(void)_activateItemToActivate:(id)arg1 ;
-(void)_finishAnimations;
-(void)_setItemsCloseButtonEnabled:(BOOL)arg1 ;
-(void)setShowsExplanationView:(BOOL)arg1 animated:(BOOL)arg2 ;
-(void)_stopReorderingItem:(id)arg1 withFinalTimeAdjustment:(double)arg2 tabCount:(double)arg3 ;
-(BOOL)_shouldContinueAnimatingItem:(id)arg1 ;
-(void)_resetItem:(id)arg1 ;
-(void)setItems:(id)arg1 withTransition:(long long)arg2 ;
-(void)_prepareForTransition:(long long)arg1 toItems:(id)arg2 ;
-(void)_finishTransition;
-(void)_layoutItemsWithTransition:(long long)arg1 ;
-(void)_updateSpringAnimationForView:(id)arg1 withFrame:(CGRect)arg2 transform:(CATransform3D)arg3 zPosition:(double)arg4 opacity:(double)arg5 verticalScrollAdjustment:(double)arg6 animated:(BOOL)arg7 delay:(double)arg8 additionalSpeed:(float)arg9 useRelaxedTimingFunction:(BOOL)arg10 useBounceAnimation:(BOOL)arg11 ;
-(double)_velocityForSpringAnimations;
-(void)_configureStaticPropertiesForSpringAnimation:(id)arg1 ;
-(void)_configureVelocityForSpringAnimation:(id)arg1 withKeyPath:(id)arg2 ;
-(double)_speedForSpringAnimations;
-(double)_durationForSpringAnimations;
-(void)_addSpringAnimationWithKeyPath:(id)arg1 toLayer:(id)arg2 fromValue:(id)arg3 toValue:(id)arg4 delay:(double)arg5 additionalSpeed:(float)arg6 useRelaxedTimingFunction:(BOOL)arg7 useBounceAnimation:(BOOL)arg8 ;
-(id)_makeReorderAnimationWithDirection:(long long)arg1 springDuration:(double)arg2 tabCount:(double)arg3 ;
-(void)_updateReorderAnimationBeginTimeForLayer:(id)arg1 withTimeAdjustment:(double)arg2 ;
-(double)_cloudTabsContentHeightForItemCount:(double)arg1 ;
-(double)_cloudTabsTopPaddingForItemCount:(double)arg1 ;
-(double)_interactiveCloseProgressForLayout;
-(CGSize)_contentSizeForItemCount:(double)arg1 ;
-(double)_baseOffsetForItemAtIndex:(unsigned long long)arg1 withItemCountForLayout:(double)arg2 ;
-(BOOL)_shouldUseFastExplanationViewAnimation;
-(CGRect)_visibleContentFrame;
-(void)_updateReorderAnimationsForItem:(id)arg1 withTimeAdjustment:(double)arg2 tabCount:(double)arg3 createIfNecessary:(BOOL)arg4 ;
-(BOOL)_isTabCommitGestureRecognized;
-(double)_multipleItemCloseAnimationDelayForItemAtIndex:(unsigned long long)arg1 ;
-(void)_updateSpringAnimationForView:(id)arg1 withBounds:(CGRect)arg2 animated:(BOOL)arg3 ;
-(void)_setTopBackdropViewHidden:(BOOL)arg1 ;
-(void)_updateSpringAnimationForView:(id)arg1 withFrame:(CGRect)arg2 verticalScrollAdjustment:(double)arg3 animated:(BOOL)arg4 ;
-(double)_heightForStatusBarGradientWithItemCount:(double)arg1 ;
-(void)_updateExplanationViewVisibilityForcingLayout:(BOOL)arg1 ;
-(CGSize)_requestedSnapshotSize;
-(BOOL)showsExplanationView;
-(void)_stopTrackingEditedTabItemView;
-(void)setDefersActivation:(BOOL)arg1 ;
-(void)setItemToAdd:(TiltedTabItem *)arg1 ;
-(void)enumerateItemsOrderedByVisibility:(/*^block*/id)arg1 ;
-(BOOL)itemIsCoveredBySlidingWindow:(id)arg1 windowSize:(unsigned long long)arg2 ;
-(unsigned long long)countOfVisibleItems;
-(double)desiredSnapshotHeightForSize:(CGSize)arg1 ;
-(double)desiredSnapshotScale;
-(void)updateSnapshotForItem:(id)arg1 animated:(BOOL)arg2 ;
-(void)setCloudTabDevices:(id)arg1 ;
-(TiltedTabItem *)itemToActivate;
-(BOOL)defersActivation;
-(TiltedTabItem *)itemToAdd;
-(id)initWithFrame:(CGRect)arg1 ;
-(void)layoutSubviews;
-(void)setDelegate:(id<TiltedTabViewDelegate>)arg1 ;
-(void)dealloc;
-(id)hitTest:(CGPoint)arg1 withEvent:(id)arg2 ;
-(void)scrollViewDidScroll:(id)arg1 ;
-(void)scrollViewWillBeginDragging:(id)arg1 ;
-(BOOL)scrollViewShouldScrollToTop:(id)arg1 ;
-(id<TiltedTabViewDelegate>)delegate;
-(id)_basicAnimationForView:(id)arg1 withKeyPath:(id)arg2 ;
-(id)_timingFunctionForAnimation;
-(BOOL)gestureRecognizerShouldBegin:(id)arg1 ;
-(BOOL)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2 ;
-(BOOL)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2 ;
-(NSArray *)items;
-(void)setItems:(NSArray *)arg1 ;
-(void)animationDidStop:(id)arg1 finished:(BOOL)arg2 ;
-(void)interactionProgressDidUpdate:(id)arg1 ;
-(void)interactionProgress:(id)arg1 didEnd:(BOOL)arg2 ;
-(BOOL)isPresented;
-(void)setPresented:(BOOL)arg1 ;
@end

