/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, December 27, 2016 at 5:08:24 PM Japan Standard Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /Applications/MobileSafari.app/MobileSafari
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MobileSafari/TouchIconFetcherObserver.h>

@protocol TouchIconFetcherWebProcessController;
@class WKWebView, NSMutableArray, _WKRemoteObjectInterface, NSString;

@interface TouchIconFetcher : NSObject <TouchIconFetcherObserver> {

	WKWebView* _webView;
	BOOL _fetchingURLs;
	BOOL _invalidated;
	NSMutableArray* _completionBlocks;
	id<TouchIconFetcherWebProcessController> _activityProxy;
	_WKRemoteObjectInterface* _touchIconFetcherObserver;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)fetchTouchIconURLsWithCompletion:(/*^block*/id)arg1 ;
-(void)_setUpTouchIconFetcherObserver;
-(void)didFetchTouchIconURLs:(id)arg1 forURL:(id)arg2 ;
-(void)invalidate;
-(id)_webProcessActivityProxy;
-(id)initWithWebView:(id)arg1 ;
@end

