/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, December 27, 2016 at 5:08:24 PM Japan Standard Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /Applications/MobileSafari.app/MobileSafari
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol UIDocumentInteractionControllerDelegatePrivate <UIDocumentInteractionControllerDelegate>
@optional
-(id)excludedActivityTypesForDocumentInteractionController:(id)arg1;
-(void)documentInteractionControllerWillEndPreview:(id)arg1;
-(id)documentInteractionControllerTransitionImageForPreview:(id)arg1 contentRect:(CGRect*)arg2;
-(void)previewController:(id)arg1 willMarkUpAtURL:(id)arg2;
-(id)documentProxyForPreview:(id)arg1 name:(id)arg2 UTI:(id)arg3;
-(id)documentInteractionControllerURLOfDirectoryForUnzippedDocument:(id)arg1;
-(BOOL)shouldBlockRemoteImagesInPreviewForDocumentInteractionController:(id)arg1;
-(id)additionalActivitiesForDocumentInteractionController:(id)arg1;
-(id)activityItemForDocumentInteractionController:(id)arg1;
-(id)printInfoForDocumentInteractionController:(id)arg1;

@end

