/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, December 27, 2016 at 5:08:24 PM Japan Standard Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /Applications/MobileSafari.app/MobileSafari
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol UnifiedFieldDelegate <UITextFieldDelegate>
@required
-(void)unifiedField:(id)arg1 didEndEditingWithParsecTopHit:(id)arg2;
-(void)unifiedField:(id)arg1 didEndEditingWithAddress:(id)arg2;
-(void)unifiedField:(id)arg1 didEndEditingWithSearch:(id)arg2;
-(BOOL)unifiedField:(id)arg1 shouldWaitForTopHitForText:(id)arg2;
-(id)unifiedField:(id)arg1 topHitForText:(id)arg2;
-(void)unifiedFieldReflectedItemDidChange:(id)arg1;
-(void)unifiedField:(id)arg1 registerKeyCommandsUsingBlock:(/*^block*/id)arg2;
-(BOOL)unifiedField:(id)arg1 canPerformAction:(SEL)arg2 withSender:(id)arg3;

@end

