/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, December 27, 2016 at 5:08:24 PM Japan Standard Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /Applications/MobileSafari.app/MobileSafari
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface UniqueAnimationKeyCounter : NSObject {

	unsigned long long _nextAnimationKey;
	unsigned long long _finishedUsingKeys;

}

@property (getter=isFinishedUsingAllKeys,nonatomic,readonly) BOOL finishedUsingAllKeys; 
-(unsigned long long)nextAnimationKey;
-(void)didFinishUsingAnimationKey;
-(BOOL)isFinishedUsingAllKeys;
@end

