/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, December 27, 2016 at 5:08:24 PM Japan Standard Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /Applications/MobileSafari.app/MobileSafari
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UITableViewHeaderFooterView.h>
#import <MobileSafari/UniversalSearchSectionHeaderViewWithFeedbackDelegate.h>

@protocol UniversalSearchFeedbackDelegate;
@class UIButton, NSString, NSURL;

@interface UniversalSearchResultTableSectionHeaderView : UITableViewHeaderFooterView <UniversalSearchSectionHeaderViewWithFeedbackDelegate> {

	UIButton* _feedbackButton;
	NSString* _title;
	NSURL* _reportProblemURL;
	id<UniversalSearchFeedbackDelegate> _feedbackDelegate;

}

@property (nonatomic,copy) NSString * title;                                                           //@synthesize title=_title - In the implementation block
@property (nonatomic,retain) NSURL * reportProblemURL;                                                 //@synthesize reportProblemURL=_reportProblemURL - In the implementation block
@property (assign,nonatomic,__weak) id<UniversalSearchFeedbackDelegate> feedbackDelegate;              //@synthesize feedbackDelegate=_feedbackDelegate - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)_handleParsecFeedbackButtonTap:(id)arg1 ;
-(void)setReportProblemURL:(NSURL *)arg1 ;
-(void)setTitle:(NSString *)arg1 ;
-(NSString *)title;
-(NSURL *)reportProblemURL;
-(void)setFeedbackDelegate:(id<UniversalSearchFeedbackDelegate>)arg1 ;
-(id<UniversalSearchFeedbackDelegate>)feedbackDelegate;
@end

