/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, December 27, 2016 at 5:08:24 PM Japan Standard Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /Applications/MobileSafari.app/MobileSafari
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <SafariShared/WBSURLCompletionDatabase.h>
#import <libobjc.A.dylib/WBSURLCompletionDataSource.h>

@protocol OS_dispatch_queue, WBBookmarkProvider;
@class CloudTabStore, NSArray, NSObject, NSCache, NSString;

@interface URLCompletionDatabase : WBSURLCompletionDatabase <WBSURLCompletionDataSource> {

	CloudTabStore* _cloudTabStore;
	NSArray* _cloudDevices;
	NSObject*<OS_dispatch_queue> _cloudTabsAccessQueue;
	NSCache* _bookmarksCache;
	id<WBBookmarkProvider> _bookmarkProvider;
	int _searchableCollectionsMask;

}

@property (assign,nonatomic) int searchableCollectionsMask;              //@synthesize searchableCollectionsMask=_searchableCollectionsMask - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(id)initWithCloudTabStore:(id)arg1 searchableCollectionsMask:(int)arg2 bookmarkProvider:(id)arg3 ;
-(void)clearBookmarksCache;
-(void)_updateCloudDevices:(id)arg1 ;
-(int)searchableCollectionsMask;
-(void)setSearchableCollectionsMask:(int)arg1 ;
-(void)dealloc;
-(id)fakeBookmarkMatchDataWithURLString:(id)arg1 title:(id)arg2 ;
-(void)enumerateMatchDataForTypedStringHint:(id)arg1 withBlock:(/*^block*/id)arg2 ;
@end

