/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, December 27, 2016 at 5:08:24 PM Japan Standard Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /Applications/MobileSafari.app/MobileSafari
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol WebBookmarksClientDelegateProtocol <NSObject>
@optional
-(void)bookmarksServerProxy:(id)arg1 didStartFetchingReadingListItem:(id)arg2;
-(void)bookmarksServerProxy:(id)arg1 didStopFetchingReadingListItem:(id)arg2;
-(void)bookmarksServerProxy:(id)arg1 didUpdateReadingListFetchingProgress:(double)arg2;
-(void)bookmarksServerProxyDidFinishFetching:(id)arg1;

@end

