/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, December 27, 2016 at 5:08:24 PM Japan Standard Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /Applications/MobileSafari.app/MobileSafari
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <MobileSafari/ReplayPagesTestRunner.h>

@interface WhiteTabsTestRunner : ReplayPagesTestRunner {

	unsigned long long _runCount;
	unsigned long long _totalHibernatedTabs;
	unsigned long long _totalLiveTabs;

}
-(void)finishedTestPage:(id)arg1 ;
-(void)collectPPTResults;
-(id)init;
@end

