/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, December 27, 2016 at 4:39:56 PM Japan Standard Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /usr/lib/libAWDSupportFramework.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libAWDSupportFramework.dylib/libAWDSupportFramework.dylib-Structs.h>
#import <ProtocolBuffer/PBCodable.h>
#import <libobjc.A.dylib/NSCopying.h>

@class NSData, NSString, NSMutableArray;

@interface AWDNotificationInteractionContext : PBCodable <NSCopying> {

	unsigned long long _dateAlertActivelyDismisssed;
	unsigned long long _dateAlertEngaged;
	unsigned long long _dateAlertWasCovered;
	unsigned long long _dateAlertWasScrolled;
	unsigned long long _dateAllClearedFromNotificationCenter;
	unsigned long long _dateCrownPressed;
	unsigned long long _dateDelivered;
	unsigned long long _dateSpecificallyClearedFromNotificationCenter;
	unsigned long long _dateWristQuicklyRaised;
	unsigned long long _timestamp;
	NSData* _accelerometerDataDuringDelivery;
	NSString* _appName;
	unsigned _batteryLevelDuringDelivery;
	NSString* _bulletinId;
	NSData* _coreMotionActivityDuringDelivery;
	int _coreRoutineLocationOfInterestTypeDuringDelivery;
	NSMutableArray* _hashedPeopleIDs;
	unsigned _numberOfNotificationsInNotificationCenter;
	NSString* _toneIdentifier;
	NSString* _vibrationIdentifier;
	BOOL _didHapticPlayDuringDelivery;
	BOOL _didSoundPlayDuringDelivery;
	BOOL _noInteractionWithinMaxWindow;
	BOOL _wasDoNotDisturbEnabledDuringDelivery;
	BOOL _wasInCalendarEventDuringDelivery;
	BOOL _wasNotificationPrivacyEnabledDuringDelivery;
	BOOL _wasScreenOnDuringDelivery;
	BOOL _wasSilentModeEnabledDuringDelivery;
	BOOL _wasUnreadNotificationsIndicatorEnabledDuringDelivery;
	SCD_Struct_AW8 _has;

}

@property (assign,nonatomic) BOOL hasTimestamp; 
@property (assign,nonatomic) unsigned long long timestamp;                                                  //@synthesize timestamp=_timestamp - In the implementation block
@property (nonatomic,readonly) BOOL hasBulletinId; 
@property (nonatomic,retain) NSString * bulletinId;                                                         //@synthesize bulletinId=_bulletinId - In the implementation block
@property (nonatomic,readonly) BOOL hasAppName; 
@property (nonatomic,retain) NSString * appName;                                                            //@synthesize appName=_appName - In the implementation block
@property (nonatomic,readonly) BOOL hasToneIdentifier; 
@property (nonatomic,retain) NSString * toneIdentifier;                                                     //@synthesize toneIdentifier=_toneIdentifier - In the implementation block
@property (nonatomic,readonly) BOOL hasVibrationIdentifier; 
@property (nonatomic,retain) NSString * vibrationIdentifier;                                                //@synthesize vibrationIdentifier=_vibrationIdentifier - In the implementation block
@property (nonatomic,retain) NSMutableArray * hashedPeopleIDs;                                              //@synthesize hashedPeopleIDs=_hashedPeopleIDs - In the implementation block
@property (assign,nonatomic) BOOL hasDateDelivered; 
@property (assign,nonatomic) unsigned long long dateDelivered;                                              //@synthesize dateDelivered=_dateDelivered - In the implementation block
@property (assign,nonatomic) BOOL hasDidHapticPlayDuringDelivery; 
@property (assign,nonatomic) BOOL didHapticPlayDuringDelivery;                                              //@synthesize didHapticPlayDuringDelivery=_didHapticPlayDuringDelivery - In the implementation block
@property (assign,nonatomic) BOOL hasDidSoundPlayDuringDelivery; 
@property (assign,nonatomic) BOOL didSoundPlayDuringDelivery;                                               //@synthesize didSoundPlayDuringDelivery=_didSoundPlayDuringDelivery - In the implementation block
@property (assign,nonatomic) BOOL hasWasUnreadNotificationsIndicatorEnabledDuringDelivery; 
@property (assign,nonatomic) BOOL wasUnreadNotificationsIndicatorEnabledDuringDelivery;                     //@synthesize wasUnreadNotificationsIndicatorEnabledDuringDelivery=_wasUnreadNotificationsIndicatorEnabledDuringDelivery - In the implementation block
@property (assign,nonatomic) BOOL hasWasNotificationPrivacyEnabledDuringDelivery; 
@property (assign,nonatomic) BOOL wasNotificationPrivacyEnabledDuringDelivery;                              //@synthesize wasNotificationPrivacyEnabledDuringDelivery=_wasNotificationPrivacyEnabledDuringDelivery - In the implementation block
@property (assign,nonatomic) BOOL hasWasScreenOnDuringDelivery; 
@property (assign,nonatomic) BOOL wasScreenOnDuringDelivery;                                                //@synthesize wasScreenOnDuringDelivery=_wasScreenOnDuringDelivery - In the implementation block
@property (assign,nonatomic) BOOL hasWasInCalendarEventDuringDelivery; 
@property (assign,nonatomic) BOOL wasInCalendarEventDuringDelivery;                                         //@synthesize wasInCalendarEventDuringDelivery=_wasInCalendarEventDuringDelivery - In the implementation block
@property (assign,nonatomic) BOOL hasWasDoNotDisturbEnabledDuringDelivery; 
@property (assign,nonatomic) BOOL wasDoNotDisturbEnabledDuringDelivery;                                     //@synthesize wasDoNotDisturbEnabledDuringDelivery=_wasDoNotDisturbEnabledDuringDelivery - In the implementation block
@property (assign,nonatomic) BOOL hasWasSilentModeEnabledDuringDelivery; 
@property (assign,nonatomic) BOOL wasSilentModeEnabledDuringDelivery;                                       //@synthesize wasSilentModeEnabledDuringDelivery=_wasSilentModeEnabledDuringDelivery - In the implementation block
@property (assign,nonatomic) BOOL hasNumberOfNotificationsInNotificationCenter; 
@property (assign,nonatomic) unsigned numberOfNotificationsInNotificationCenter;                            //@synthesize numberOfNotificationsInNotificationCenter=_numberOfNotificationsInNotificationCenter - In the implementation block
@property (assign,nonatomic) BOOL hasBatteryLevelDuringDelivery; 
@property (assign,nonatomic) unsigned batteryLevelDuringDelivery;                                           //@synthesize batteryLevelDuringDelivery=_batteryLevelDuringDelivery - In the implementation block
@property (nonatomic,readonly) BOOL hasCoreMotionActivityDuringDelivery; 
@property (nonatomic,retain) NSData * coreMotionActivityDuringDelivery;                                     //@synthesize coreMotionActivityDuringDelivery=_coreMotionActivityDuringDelivery - In the implementation block
@property (nonatomic,readonly) BOOL hasAccelerometerDataDuringDelivery; 
@property (nonatomic,retain) NSData * accelerometerDataDuringDelivery;                                      //@synthesize accelerometerDataDuringDelivery=_accelerometerDataDuringDelivery - In the implementation block
@property (assign,nonatomic) BOOL hasCoreRoutineLocationOfInterestTypeDuringDelivery; 
@property (assign,nonatomic) int coreRoutineLocationOfInterestTypeDuringDelivery;                           //@synthesize coreRoutineLocationOfInterestTypeDuringDelivery=_coreRoutineLocationOfInterestTypeDuringDelivery - In the implementation block
@property (assign,nonatomic) BOOL hasDateAlertWasScrolled; 
@property (assign,nonatomic) unsigned long long dateAlertWasScrolled;                                       //@synthesize dateAlertWasScrolled=_dateAlertWasScrolled - In the implementation block
@property (assign,nonatomic) BOOL hasDateAlertWasCovered; 
@property (assign,nonatomic) unsigned long long dateAlertWasCovered;                                        //@synthesize dateAlertWasCovered=_dateAlertWasCovered - In the implementation block
@property (assign,nonatomic) BOOL hasDateAlertEngaged; 
@property (assign,nonatomic) unsigned long long dateAlertEngaged;                                           //@synthesize dateAlertEngaged=_dateAlertEngaged - In the implementation block
@property (assign,nonatomic) BOOL hasDateAlertActivelyDismisssed; 
@property (assign,nonatomic) unsigned long long dateAlertActivelyDismisssed;                                //@synthesize dateAlertActivelyDismisssed=_dateAlertActivelyDismisssed - In the implementation block
@property (assign,nonatomic) BOOL hasDateCrownPressed; 
@property (assign,nonatomic) unsigned long long dateCrownPressed;                                           //@synthesize dateCrownPressed=_dateCrownPressed - In the implementation block
@property (assign,nonatomic) BOOL hasDateWristQuicklyRaised; 
@property (assign,nonatomic) unsigned long long dateWristQuicklyRaised;                                     //@synthesize dateWristQuicklyRaised=_dateWristQuicklyRaised - In the implementation block
@property (assign,nonatomic) BOOL hasDateSpecificallyClearedFromNotificationCenter; 
@property (assign,nonatomic) unsigned long long dateSpecificallyClearedFromNotificationCenter;              //@synthesize dateSpecificallyClearedFromNotificationCenter=_dateSpecificallyClearedFromNotificationCenter - In the implementation block
@property (assign,nonatomic) BOOL hasDateAllClearedFromNotificationCenter; 
@property (assign,nonatomic) unsigned long long dateAllClearedFromNotificationCenter;                       //@synthesize dateAllClearedFromNotificationCenter=_dateAllClearedFromNotificationCenter - In the implementation block
@property (assign,nonatomic) BOOL hasNoInteractionWithinMaxWindow; 
@property (assign,nonatomic) BOOL noInteractionWithinMaxWindow;                                             //@synthesize noInteractionWithinMaxWindow=_noInteractionWithinMaxWindow - In the implementation block
+(Class)hashedPeopleIDsType;
-(void)dealloc;
-(BOOL)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(id)description;
-(unsigned long long)timestamp;
-(void)setTimestamp:(unsigned long long)arg1 ;
-(id)copyWithZone:(NSZone*)arg1 ;
-(id)dictionaryRepresentation;
-(void)setVibrationIdentifier:(NSString *)arg1 ;
-(void)setToneIdentifier:(NSString *)arg1 ;
-(NSString *)vibrationIdentifier;
-(NSString *)toneIdentifier;
-(BOOL)readFrom:(id)arg1 ;
-(void)writeTo:(id)arg1 ;
-(void)copyTo:(id)arg1 ;
-(void)mergeFrom:(id)arg1 ;
-(void)setHasTimestamp:(BOOL)arg1 ;
-(BOOL)hasTimestamp;
-(void)setHashedPeopleIDs:(NSMutableArray *)arg1 ;
-(void)setCoreMotionActivityDuringDelivery:(NSData *)arg1 ;
-(void)setAccelerometerDataDuringDelivery:(NSData *)arg1 ;
-(void)addHashedPeopleIDs:(id)arg1 ;
-(unsigned long long)hashedPeopleIDsCount;
-(void)clearHashedPeopleIDs;
-(id)hashedPeopleIDsAtIndex:(unsigned long long)arg1 ;
-(BOOL)hasAppName;
-(BOOL)hasToneIdentifier;
-(BOOL)hasVibrationIdentifier;
-(void)setDateDelivered:(unsigned long long)arg1 ;
-(void)setHasDateDelivered:(BOOL)arg1 ;
-(BOOL)hasDateDelivered;
-(void)setWasUnreadNotificationsIndicatorEnabledDuringDelivery:(BOOL)arg1 ;
-(void)setHasWasUnreadNotificationsIndicatorEnabledDuringDelivery:(BOOL)arg1 ;
-(BOOL)hasWasUnreadNotificationsIndicatorEnabledDuringDelivery;
-(void)setWasNotificationPrivacyEnabledDuringDelivery:(BOOL)arg1 ;
-(void)setHasWasNotificationPrivacyEnabledDuringDelivery:(BOOL)arg1 ;
-(BOOL)hasWasNotificationPrivacyEnabledDuringDelivery;
-(void)setWasScreenOnDuringDelivery:(BOOL)arg1 ;
-(void)setHasWasScreenOnDuringDelivery:(BOOL)arg1 ;
-(BOOL)hasWasScreenOnDuringDelivery;
-(void)setWasInCalendarEventDuringDelivery:(BOOL)arg1 ;
-(void)setHasWasInCalendarEventDuringDelivery:(BOOL)arg1 ;
-(BOOL)hasWasInCalendarEventDuringDelivery;
-(void)setWasDoNotDisturbEnabledDuringDelivery:(BOOL)arg1 ;
-(void)setHasWasDoNotDisturbEnabledDuringDelivery:(BOOL)arg1 ;
-(BOOL)hasWasDoNotDisturbEnabledDuringDelivery;
-(void)setWasSilentModeEnabledDuringDelivery:(BOOL)arg1 ;
-(void)setHasWasSilentModeEnabledDuringDelivery:(BOOL)arg1 ;
-(BOOL)hasWasSilentModeEnabledDuringDelivery;
-(void)setBatteryLevelDuringDelivery:(unsigned)arg1 ;
-(void)setHasBatteryLevelDuringDelivery:(BOOL)arg1 ;
-(BOOL)hasBatteryLevelDuringDelivery;
-(BOOL)hasCoreMotionActivityDuringDelivery;
-(BOOL)hasAccelerometerDataDuringDelivery;
-(int)coreRoutineLocationOfInterestTypeDuringDelivery;
-(void)setCoreRoutineLocationOfInterestTypeDuringDelivery:(int)arg1 ;
-(void)setHasCoreRoutineLocationOfInterestTypeDuringDelivery:(BOOL)arg1 ;
-(BOOL)hasCoreRoutineLocationOfInterestTypeDuringDelivery;
-(id)coreRoutineLocationOfInterestTypeDuringDeliveryAsString:(int)arg1 ;
-(int)StringAsCoreRoutineLocationOfInterestTypeDuringDelivery:(id)arg1 ;
-(void)setNoInteractionWithinMaxWindow:(BOOL)arg1 ;
-(void)setHasNoInteractionWithinMaxWindow:(BOOL)arg1 ;
-(BOOL)hasNoInteractionWithinMaxWindow;
-(NSString *)appName;
-(NSMutableArray *)hashedPeopleIDs;
-(unsigned long long)dateDelivered;
-(BOOL)wasUnreadNotificationsIndicatorEnabledDuringDelivery;
-(BOOL)wasNotificationPrivacyEnabledDuringDelivery;
-(BOOL)wasScreenOnDuringDelivery;
-(BOOL)wasInCalendarEventDuringDelivery;
-(BOOL)wasDoNotDisturbEnabledDuringDelivery;
-(BOOL)wasSilentModeEnabledDuringDelivery;
-(unsigned)batteryLevelDuringDelivery;
-(NSData *)coreMotionActivityDuringDelivery;
-(NSData *)accelerometerDataDuringDelivery;
-(BOOL)noInteractionWithinMaxWindow;
-(void)setBulletinId:(NSString *)arg1 ;
-(BOOL)hasBulletinId;
-(void)setDidHapticPlayDuringDelivery:(BOOL)arg1 ;
-(void)setHasDidHapticPlayDuringDelivery:(BOOL)arg1 ;
-(BOOL)hasDidHapticPlayDuringDelivery;
-(void)setDidSoundPlayDuringDelivery:(BOOL)arg1 ;
-(void)setHasDidSoundPlayDuringDelivery:(BOOL)arg1 ;
-(BOOL)hasDidSoundPlayDuringDelivery;
-(void)setNumberOfNotificationsInNotificationCenter:(unsigned)arg1 ;
-(void)setHasNumberOfNotificationsInNotificationCenter:(BOOL)arg1 ;
-(BOOL)hasNumberOfNotificationsInNotificationCenter;
-(void)setDateAlertWasScrolled:(unsigned long long)arg1 ;
-(void)setHasDateAlertWasScrolled:(BOOL)arg1 ;
-(BOOL)hasDateAlertWasScrolled;
-(void)setDateAlertWasCovered:(unsigned long long)arg1 ;
-(void)setHasDateAlertWasCovered:(BOOL)arg1 ;
-(BOOL)hasDateAlertWasCovered;
-(void)setDateAlertEngaged:(unsigned long long)arg1 ;
-(void)setHasDateAlertEngaged:(BOOL)arg1 ;
-(BOOL)hasDateAlertEngaged;
-(void)setDateAlertActivelyDismisssed:(unsigned long long)arg1 ;
-(void)setHasDateAlertActivelyDismisssed:(BOOL)arg1 ;
-(BOOL)hasDateAlertActivelyDismisssed;
-(void)setDateCrownPressed:(unsigned long long)arg1 ;
-(void)setHasDateCrownPressed:(BOOL)arg1 ;
-(BOOL)hasDateCrownPressed;
-(void)setDateWristQuicklyRaised:(unsigned long long)arg1 ;
-(void)setHasDateWristQuicklyRaised:(BOOL)arg1 ;
-(BOOL)hasDateWristQuicklyRaised;
-(void)setDateSpecificallyClearedFromNotificationCenter:(unsigned long long)arg1 ;
-(void)setHasDateSpecificallyClearedFromNotificationCenter:(BOOL)arg1 ;
-(BOOL)hasDateSpecificallyClearedFromNotificationCenter;
-(void)setDateAllClearedFromNotificationCenter:(unsigned long long)arg1 ;
-(void)setHasDateAllClearedFromNotificationCenter:(BOOL)arg1 ;
-(BOOL)hasDateAllClearedFromNotificationCenter;
-(NSString *)bulletinId;
-(BOOL)didHapticPlayDuringDelivery;
-(BOOL)didSoundPlayDuringDelivery;
-(unsigned)numberOfNotificationsInNotificationCenter;
-(unsigned long long)dateAlertWasScrolled;
-(unsigned long long)dateAlertWasCovered;
-(unsigned long long)dateAlertEngaged;
-(unsigned long long)dateAlertActivelyDismisssed;
-(unsigned long long)dateCrownPressed;
-(unsigned long long)dateWristQuicklyRaised;
-(unsigned long long)dateSpecificallyClearedFromNotificationCenter;
-(unsigned long long)dateAllClearedFromNotificationCenter;
-(void)setAppName:(NSString *)arg1 ;
@end

