/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, December 27, 2016 at 5:08:27 PM Japan Standard Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /Applications/Podcasts.app/Frameworks/IMUtil.framework/IMUtil
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface IMJSONUtil : NSObject
+(id)fromJSONData:(id)arg1 ;
+(id)fromJSONString:(id)arg1 ;
+(id)toJSONString:(id)arg1 ;
@end

