/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, December 27, 2016 at 4:41:29 PM Japan Standard Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /usr/lib/libQLCharts.dylib
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol OIPieSliceRenderer
@required
-(void)renderPieSliceFromSeries:(OISeriesRef)arg1 radius:(double)arg2 angle:(double)arg3 newAngle:(double)arg4 xOffset:(double)arg5 yOffset:(double)arg6 thickness:(double)arg7;

@end

