/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, December 27, 2016 at 5:08:24 PM Japan Standard Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /Applications/MobileSafari.app/PlugIns/Safari.wkbundle/Safari
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Safari/Safari-Structs.h>
#import <MailWebProcessBundle/WKWebProcessPlugInLoadDelegate.h>

@protocol PageLoadTestEventsListener;
@class NSTimer, NSMutableDictionary, NSMutableSet, WKWebProcessPlugInBrowserContextController, NSString;

@interface MeasurementControllerBase : NSObject <WKWebProcessPlugInLoadDelegate> {

	NSTimer* _waitForLoadToReallyEnd;
	NSMutableDictionary* _loadData;
	BOOL _currentPageLoadFinished;
	HashSet<unsigned long long, WTF::IntHash<unsigned long long>, WTF::HashTraits<unsigned long long> >* _loadingSubresources;
	NSMutableSet* _loadingFrames;
	WKWebProcessPlugInBrowserContextController* _contextController;
	id<PageLoadTestEventsListener> _pageLoadTestEventsProxy;

}

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)_maybeEndPageLoadSoon;
-(void)_doAfterPageLoad;
-(void)_clearPageLoadState;
-(void)_waitforLoadEndTimerFired:(id)arg1 ;
-(void)_doBeforePageLoad;
-(void)_sendPageLoadFinishedEvent;
-(BOOL)_shouldConsiderPageLoadEnded;
-(void)_postPageLoadEnd;
-(id)initWithPluginPageContextController:(id)arg1 ;
-(void)webProcessPlugInBrowserContextController:(id)arg1 didHandleOnloadEventsForFrame:(id)arg2 ;
-(void)webProcessPlugInBrowserContextController:(id)arg1 didStartProvisionalLoadForFrame:(id)arg2 ;
-(void)webProcessPlugInBrowserContextController:(id)arg1 didCommitLoadForFrame:(id)arg2 ;
-(void)webProcessPlugInBrowserContextController:(id)arg1 didFailLoadWithErrorForFrame:(id)arg2 error:(id)arg3 ;
-(void)webProcessPlugInBrowserContextController:(id)arg1 didFinishLoadForFrame:(id)arg2 ;
-(void)webProcessPlugInBrowserContextController:(id)arg1 didFirstVisuallyNonEmptyLayoutForFrame:(id)arg2 ;
-(void)webProcessPlugInBrowserContextController:(id)arg1 frame:(id)arg2 didInitiateLoadForResource:(unsigned long long)arg3 request:(id)arg4 ;
-(void)webProcessPlugInBrowserContextController:(id)arg1 frame:(id)arg2 didFinishLoadForResource:(unsigned long long)arg3 ;
-(void)webProcessPlugInBrowserContextController:(id)arg1 frame:(id)arg2 didFailLoadForResource:(unsigned long long)arg3 error:(id)arg4 ;
@end

