/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, December 27, 2016 at 5:08:25 PM Japan Standard Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /Applications/MobileSafari.app/PlugIns/Safari.wkbundle/Safari
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <WebUI/WBUWebProcessPlugIn.h>

@interface SafariWebProcessPlugIn : WBUWebProcessPlugIn
-(id)pageControllerWithBrowserContextController:(id)arg1 ;
@end

