/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, December 27, 2016 at 5:08:31 PM Japan Standard Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /Applications/Weather.app/PlugIns/WeatherAppTodayWidget.appex/WeatherAppTodayWidget
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol NCWidgetProviding <NSObject>
@optional
-(void)widgetPerformUpdateWithCompletionHandler:(/*^block*/id)arg1;
-(void)widgetActiveDisplayModeDidChange:(long long)arg1 withMaximumSize:(CGSize)arg2;
-(UIEdgeInsets*)widgetMarginInsetsForProposedMarginInsets:(UIEdgeInsets)arg1;

@end

