/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, December 27, 2016 at 5:08:14 PM Japan Standard Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /Applications/Cydia.app/Cydia
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Cydia/Cydia-Structs.h>
#import <Cydia/CyteWebViewController.h>

@interface CydiaWebViewController : CyteWebViewController {

	MenesObjectHandle<CydiaObject, 0> cydia_;

}
+(void)addDiversion:(id)arg1 ;
+(void)didClearWindowObject:(id)arg1 forFrame:(id)arg2 withCydia:(id)arg3 ;
+(id)requestWithHeaders:(id)arg1 ;
+(void)_initialize;
-(id)navigationURL;
-(id)URLWithURL:(id)arg1 ;
-(void)_setupMail:(id)arg1 ;
-(id)init;
-(void)setDelegate:(id)arg1 ;
-(void)webView:(id)arg1 didClearWindowObject:(id)arg2 forFrame:(id)arg3 ;
-(id)webThreadWebView:(id)arg1 resource:(id)arg2 willSendRequest:(id)arg3 redirectResponse:(id)arg4 fromDataSource:(id)arg5 ;
-(id)webView:(id)arg1 resource:(id)arg2 willSendRequest:(id)arg3 redirectResponse:(id)arg4 fromDataSource:(id)arg5 ;
-(id)applicationNameForUserAgent;
@end

