/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, December 27, 2016 at 5:08:14 PM Japan Standard Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /Applications/Cydia.app/Cydia
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class UIColor, CyteTableViewCellContentView, CyteWebView, UIActivityIndicatorView, IndirectDelegate, NSURLAuthenticationChallenge, NSURLRequest, NSURL, NSString, NSMutableSet, NSTimer, NSObject, WebScriptObject, UIBarButtonItem, UIViewController, UILabel, UIView, NSArray, NSMutableDictionary, CydiaOperation, NSMutableArray, Source, NSDate, NSObject<ProgressDelegate>, CyteWebViewController, CydiaObject, UIAlertView, NSDictionary, CydiaProgressData, UIImage, UISwitch, Package, UITableView, UIActionSheet, UISearchBar, UITableViewCell, UIProgressHUD, NSError, UIWindow, CydiaTabBarController, CyteTabBarController, AppCacheController, StashController;

typedef struct MenesObjectHandle<UIColor, 0> {
	UIColor* value_;
} MenesObjectHandle<UIColor, 0>;

typedef struct MenesObjectHandle<CyteTableViewCellContentView, 1> {
	CyteTableViewCellContentView* value_;
} MenesObjectHandle<CyteTableViewCellContentView, 1>;

typedef struct MenesObjectHandle<CyteWebView, 1> {
	CyteWebView* value_;
} MenesObjectHandle<CyteWebView, 1>;

typedef struct MenesObjectHandle<UIActivityIndicatorView, 0> {
	UIActivityIndicatorView* value_;
} MenesObjectHandle<UIActivityIndicatorView, 0>;

typedef struct MenesObjectHandle<IndirectDelegate, 1> {
	IndirectDelegate* value_;
} MenesObjectHandle<IndirectDelegate, 1>;

typedef struct MenesObjectHandle<NSURLAuthenticationChallenge, 0> {
	NSURLAuthenticationChallenge* value_;
} MenesObjectHandle<NSURLAuthenticationChallenge, 0>;

typedef struct MenesObjectHandle<NSURLRequest, 0> {
	NSURLRequest* value_;
} MenesObjectHandle<NSURLRequest, 0>;

typedef struct MenesObjectHandle<NSURL, 0> {
	NSURL* value_;
} MenesObjectHandle<NSURL, 0>;

typedef struct MenesObjectHandle<NSString, 0> {
	NSString* value_;
} MenesObjectHandle<NSString, 0>;

typedef struct MenesObjectHandle<NSMutableSet, 0> {
	NSMutableSet* value_;
} MenesObjectHandle<NSMutableSet, 0>;

typedef struct MenesObjectHandle<NSTimer, 0> {
	NSTimer* value_;
} MenesObjectHandle<NSTimer, 0>;

typedef struct MenesObjectHandle<NSObject, 0> {
	NSObject* value_;
} MenesObjectHandle<NSObject, 0>;

typedef struct MenesObjectHandle<WebScriptObject, 0> {
	WebScriptObject* value_;
} MenesObjectHandle<WebScriptObject, 0>;

typedef struct MenesObjectHandle<UIBarButtonItem, 0> {
	UIBarButtonItem* value_;
} MenesObjectHandle<UIBarButtonItem, 0>;

typedef struct MenesObjectHandle<UIViewController, 0> {
	UIViewController* value_;
} MenesObjectHandle<UIViewController, 0>;

typedef struct MenesObjectHandle<UILabel, 0> {
	UILabel* value_;
} MenesObjectHandle<UILabel, 0>;

typedef struct MenesObjectHandle<UIView, 0> {
	UIView* value_;
} MenesObjectHandle<UIView, 0>;

typedef struct MenesObjectHandle<NSArray, 0> {
	NSArray* value_;
} MenesObjectHandle<NSArray, 0>;

typedef struct CYString {
	char* data_;
	unsigned size_;
	__CFString cache_;
} CYString;

typedef struct MenesObjectHandle<NSMutableDictionary, 0> {
	NSMutableDictionary* value_;
} MenesObjectHandle<NSMutableDictionary, 0>;

typedef struct Rb_tree_node_base {
	int _M_color;
	_Rb_tree_node_base _M_parent;
	_Rb_tree_node_base _M_left;
	_Rb_tree_node_base _M_right;
} Rb_tree_node_base;

typedef struct Rb_tree_impl<std::less<std::basic_string<char> >, false> {
	less<std::basic_string<char> > _M_key_compare;
	Rb_tree_node_base _M_header;
	unsigned _M_node_count;
} Rb_tree_impl<std::less<std::basic_string<char> >, false>;

typedef struct Rb_tree<std::basic_string<char>, std::basic_string<char>, std::_Identity<std::basic_string<char> >, std::less<std::basic_string<char> >, std::allocator<std::basic_string<char> > > {
	Rb_tree_impl<std::less<std::basic_string<char> >, false> _M_impl;
} Rb_tree<std::basic_string<char>, std::basic_string<char>, std::_Identity<std::basic_string<char> >, std::less<std::basic_string<char> >, std::allocator<std::basic_string<char> > >;

typedef struct set<std::basic_string<char>, std::less<std::basic_string<char> >, std::allocator<std::basic_string<char> > > {
	Rb_tree<std::basic_string<char>, std::basic_string<char>, std::_Identity<std::basic_string<char> >, std::less<std::basic_string<char> >, std::allocator<std::basic_string<char> > > _M_t;
} set<std::basic_string<char>, std::less<std::basic_string<char> >, std::allocator<std::basic_string<char> > >;

typedef struct MenesObjectHandle<CydiaOperation, 0> {
	CydiaOperation* value_;
} MenesObjectHandle<CydiaOperation, 0>;

typedef struct MenesObjectHandle<NSMutableArray, 0> {
	NSMutableArray* value_;
} MenesObjectHandle<NSMutableArray, 0>;

typedef struct VerIterator {
	Version Ver;
	pkgCache Owner;
} VerIterator;

typedef struct PkgIterator {
	Package Pkg;
	pkgCache Owner;
	long HashIndex;
} PkgIterator;

typedef struct VerFileIterator {
	pkgCache Owner;
	VerFile FileP;
} VerFileIterator;

typedef struct MenesObjectHandle<Source, 0> {
	Source* value_;
} MenesObjectHandle<Source, 0>;

typedef struct _NSZone* NSZoneRef;

typedef struct CYPool {
	char* data_;
	unsigned size_;
	Cleaner cleaner_;
} CYPool;

typedef struct MenesObjectHandle<NSDate, 0> {
	NSDate* value_;
} MenesObjectHandle<NSDate, 0>;

typedef struct pkgCacheFile {
	MMap Map;
	pkgCache Cache;
	pkgDepCache DCache;
	pkgPolicy Policy;
} pkgCacheFile;

typedef struct SPtr<pkgPackageManager> {
	pkgPackageManager Ptr;
} SPtr<pkgPackageManager>;

typedef struct Rb_tree_impl<std::less<unsigned long>, false> {
	less<unsigned long> _M_key_compare;
	Rb_tree_node_base _M_header;
	unsigned _M_node_count;
} Rb_tree_impl<std::less<unsigned long>, false>;

typedef struct Rb_tree<unsigned long, std::pair<const unsigned long, MenesObjectHandle<Source, 0> >, std::_Select1st<std::pair<const unsigned long, MenesObjectHandle<Source, 0> > >, std::less<unsigned long>, std::allocator<std::pair<const unsigned long, MenesObjectHandle<Source, 0> > > > {
	Rb_tree_impl<std::less<unsigned long>, false> _M_impl;
} Rb_tree<unsigned long, std::pair<const unsigned long, MenesObjectHandle<Source, 0> >, std::_Select1st<std::pair<const unsigned long, MenesObjectHandle<Source, 0> > >, std::less<unsigned long>, std::allocator<std::pair<const unsigned long, MenesObjectHandle<Source, 0> > > >;

typedef struct map<unsigned long, MenesObjectHandle<Source, 0>, std::less<unsigned long>, std::allocator<std::pair<const unsigned long, MenesObjectHandle<Source, 0> > > > {
	Rb_tree<unsigned long, std::pair<const unsigned long, MenesObjectHandle<Source, 0> >, std::_Select1st<std::pair<const unsigned long, MenesObjectHandle<Source, 0> > >, std::less<unsigned long>, std::allocator<std::pair<const unsigned long, MenesObjectHandle<Source, 0> > > > _M_t;
} map<unsigned long, MenesObjectHandle<Source, 0>, std::less<unsigned long>, std::allocator<std::pair<const unsigned long, MenesObjectHandle<Source, 0> > > >;

typedef struct __CFArray* CFArrayRef;

typedef struct timeval {
	int tv_sec;
	int tv_usec;
} timeval;

typedef struct CydiaStatus {
	/*function pointer*/void* _vptr$pkgAcquireStatus;
	timeval Time;
	timeval StartTime;
	double LastBytes;
	double CurrentCPS;
	double CurrentBytes;
	double TotalBytes;
	double FetchedBytes;
	unsigned long ElapsedTime;
	unsigned long TotalItems;
	unsigned long CurrentItems;
	BOOL Update;
	BOOL MorePulses;
	BOOL cancelled_;
	NSObject<ProgressDelegate>* delegate_;
} CydiaStatus;

typedef struct Rb_tree_impl<std::less<const char *>, false> {
	less<const char *> _M_key_compare;
	Rb_tree_node_base _M_header;
	unsigned _M_node_count;
} Rb_tree_impl<std::less<const char *>, false>;

typedef struct Rb_tree<const char *, std::pair<const char *const, MenesObjectHandle<NSString, 0> >, std::_Select1st<std::pair<const char *const, MenesObjectHandle<NSString, 0> > >, std::less<const char *>, std::allocator<std::pair<const char *const, MenesObjectHandle<NSString, 0> > > > {
	Rb_tree_impl<std::less<const char *>, false> _M_impl;
} Rb_tree<const char *, std::pair<const char *const, MenesObjectHandle<NSString, 0> >, std::_Select1st<std::pair<const char *const, MenesObjectHandle<NSString, 0> > >, std::less<const char *>, std::allocator<std::pair<const char *const, MenesObjectHandle<NSString, 0> > > >;

typedef struct map<const char *, MenesObjectHandle<NSString, 0>, std::less<const char *>, std::allocator<std::pair<const char *const, MenesObjectHandle<NSString, 0> > > > {
	Rb_tree<const char *, std::pair<const char *const, MenesObjectHandle<NSString, 0> >, std::_Select1st<std::pair<const char *const, MenesObjectHandle<NSString, 0> > >, std::less<const char *>, std::allocator<std::pair<const char *const, MenesObjectHandle<NSString, 0> > > > _M_t;
} map<const char *, MenesObjectHandle<NSString, 0>, std::less<const char *>, std::allocator<std::pair<const char *const, MenesObjectHandle<NSString, 0> > > >;

typedef struct RegEx {
	URegularExpression regex_;
	int capture_;
	unsigned size_;
} RegEx;

typedef struct MenesObjectHandle<CyteWebViewController, 0> {
	CyteWebViewController* value_;
} MenesObjectHandle<CyteWebViewController, 0>;

typedef struct MenesObjectHandle<CydiaObject, 0> {
	CydiaObject* value_;
} MenesObjectHandle<CydiaObject, 0>;

typedef struct MenesObjectHandle<UIAlertView, 0> {
	UIAlertView* value_;
} MenesObjectHandle<UIAlertView, 0>;

typedef struct MenesObjectHandle<NSDictionary, 0> {
	NSDictionary* value_;
} MenesObjectHandle<NSDictionary, 0>;

typedef struct MenesObjectHandle<CydiaProgressData, 1> {
	CydiaProgressData* value_;
} MenesObjectHandle<CydiaProgressData, 1>;

typedef struct MenesObjectHandle<UIImage, 0> {
	UIImage* value_;
} MenesObjectHandle<UIImage, 0>;

typedef struct MenesObjectHandle<UISwitch, 0> {
	UISwitch* value_;
} MenesObjectHandle<UISwitch, 0>;

typedef struct MenesObjectHandle<Package, 0> {
	Package* value_;
} MenesObjectHandle<Package, 0>;

typedef struct MenesObjectHandle<UITableView, 2> {
	UITableView* value_;
} MenesObjectHandle<UITableView, 2>;

typedef struct Vector_impl {
	pair<MenesObjectHandle<NSString, 0>, MenesObjectHandle<NSString, 0> > _M_start;
	pair<MenesObjectHandle<NSString, 0>, MenesObjectHandle<NSString, 0> > _M_finish;
	pair<MenesObjectHandle<NSString, 0>, MenesObjectHandle<NSString, 0> > _M_end_of_storage;
} Vector_impl;

typedef struct vector<std::pair<MenesObjectHandle<NSString, 0>, MenesObjectHandle<NSString, 0> >, std::allocator<std::pair<MenesObjectHandle<NSString, 0>, MenesObjectHandle<NSString, 0> > > > {
	Vector_impl _M_impl;
} vector<std::pair<MenesObjectHandle<NSString, 0>, MenesObjectHandle<NSString, 0> >, std::allocator<std::pair<MenesObjectHandle<NSString, 0>, MenesObjectHandle<NSString, 0> > > >;

typedef struct MenesObjectHandle<UIActionSheet, 0> {
	UIActionSheet* value_;
} MenesObjectHandle<UIActionSheet, 0>;

typedef struct vector<int, std::allocator<int> > {
	Vector_impl _M_impl;
} vector<int, std::allocator<int> >;

typedef struct Function<bool, Package *> {
	Abstract abstract_;
} Function<bool, Package *>;

typedef struct Function<void, NSMutableArray *> {
	Abstract abstract_;
} Function<void, NSMutableArray *>;

typedef struct __CFRunLoop* CFRunLoopRef;

typedef struct __SCNetworkReachability* SCNetworkReachabilityRef;

typedef struct MenesObjectHandle<UISearchBar, 1> {
	UISearchBar* value_;
} MenesObjectHandle<UISearchBar, 1>;

typedef struct MenesObjectHandle<UITableViewCell, 0> {
	UITableViewCell* value_;
} MenesObjectHandle<UITableViewCell, 0>;

typedef struct MenesObjectHandle<Source, 1> {
	Source* value_;
} MenesObjectHandle<Source, 1>;

typedef struct MenesObjectHandle<UIProgressHUD, 0> {
	UIProgressHUD* value_;
} MenesObjectHandle<UIProgressHUD, 0>;

typedef struct MenesObjectHandle<NSError, 0> {
	NSError* value_;
} MenesObjectHandle<NSError, 0>;

typedef struct MenesObjectHandle<UIWindow, 0> {
	UIWindow* value_;
} MenesObjectHandle<UIWindow, 0>;

typedef struct MenesObjectHandle<CydiaTabBarController, 0> {
	CydiaTabBarController* value_;
} MenesObjectHandle<CydiaTabBarController, 0>;

typedef struct MenesObjectHandle<CyteTabBarController, 0> {
	CyteTabBarController* value_;
} MenesObjectHandle<CyteTabBarController, 0>;

typedef struct MenesObjectHandle<AppCacheController, 0> {
	AppCacheController* value_;
} MenesObjectHandle<AppCacheController, 0>;

typedef struct MenesObjectHandle<StashController, 0> {
	StashController* value_;
} MenesObjectHandle<StashController, 0>;

typedef struct __GSEvent* GSEventRef;

