/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, December 27, 2016 at 5:08:14 PM Japan Standard Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /Applications/Cydia.app/Cydia
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <Cydia/Cydia-Structs.h>
@interface CydiaOperation : NSObject {

	MenesObjectHandle<NSString, 0> operator_;
	MenesObjectHandle<NSString, 0> value_;

}
+(id)_attributeKeys;
+(char)isKeyExcludedFromWebScript:(const char*)arg1 ;
-(id)initWithOperator:(const char*)arg1 value:(const char*)arg2 ;
-(id)value;
-(id)attributeKeys;
-(id)operator;
@end

