/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, December 27, 2016 at 5:08:14 PM Japan Standard Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /Applications/Cydia.app/Cydia
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Cydia/Cydia-Structs.h>
#import <UIKit/UITabBarController.h>

@class UIViewController;

@interface CyteTabBarController : UITabBarController {

	UIViewController* transient_;
	MenesObjectHandle<UIViewController, 0> remembered_;

}
-(void)unloadData;
-(id)unselectedViewController;
-(void)setUnselectedViewController:(id)arg1 ;
-(unsigned)supportedInterfaceOrientations;
-(void)didReceiveMemoryWarning;
-(char)shouldAutorotate;
-(char)shouldAutorotateToInterfaceOrientation:(int)arg1 ;
-(void)dismissModalViewControllerAnimated:(char)arg1 ;
-(void)tabBarController:(id)arg1 didSelectViewController:(id)arg2 ;
@end

