/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, December 27, 2016 at 5:08:14 PM Japan Standard Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /Applications/Cydia.app/Cydia
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Cydia/Cydia-Structs.h>
#import <UIKit/UIViewController.h>

@interface CyteViewController : UIViewController {

	id delegate_;
	char loaded_;
	MenesObjectHandle<UIColor, 0> color_;

}
-(void)unloadData;
-(void)releaseSubviews;
-(id)navigationURL;
-(void)setDelegate:(id)arg1 ;
-(void)reloadData;
-(id)delegate;
-(unsigned)supportedInterfaceOrientations;
-(char)shouldAutorotate;
-(void)setView:(id)arg1 ;
-(char)shouldAutorotateToInterfaceOrientation:(int)arg1 ;
-(void)viewWillAppear:(char)arg1 ;
-(char)hasLoaded;
-(void)setPageColor:(id)arg1 ;
@end

