/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, December 27, 2016 at 5:08:14 PM Japan Standard Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /Applications/Cydia.app/Cydia
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Cydia/Cydia-Structs.h>
#import <UIKit/UITableViewCell.h>

@interface CyteTableViewCell : UITableViewCell {

	MenesObjectHandle<CyteTableViewCellContentView, 1> content_;
	BOOL highlighted_;

}
-(void)setSelected:(char)arg1 animated:(char)arg2 ;
-(void)_updateHighlightColorsForView:(id)arg1 highlighted:(char)arg2 ;
@end

