/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, December 27, 2016 at 5:08:14 PM Japan Standard Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /Applications/Cydia.app/Cydia
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libobjc.A.dylib/WebPolicyDecisionListener.h>

@protocol WebPolicyDecisionListener;
@interface CYWebPolicyDecisionMediator : NSObject <WebPolicyDecisionListener> {

	id<WebPolicyDecisionListener> listener_;
	int decision_;

}
-(BOOL)decided;
-(BOOL)decide;
-(void)ignore;
-(void)use;
-(id)initWithListener:(id)arg1 ;
-(void)download;
-(int)decision;
@end

