/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, December 27, 2016 at 5:08:14 PM Japan Standard Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /Applications/Cydia.app/Cydia
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Cydia/Cydia-Structs.h>
#import <Cydia/CydiaWebViewController.h>
#import <Cydia/ProgressDelegate.h>

@class Database;

@interface ProgressController : CydiaWebViewController <ProgressDelegate> {

	Database* database_;
	MenesObjectHandle<CydiaProgressData, 1> progress_;
	unsigned cancel_;

}
-(void)addProgressEvent:(id)arg1 ;
-(void)setProgressPercent:(id)arg1 ;
-(void)updateCancel;
-(void)setProgressStatus:(id)arg1 ;
-(void)setProgressCancellable:(id)arg1 ;
-(BOOL)isProgressCancelled;
-(id)initWithDatabase:(id)arg1 delegate:(id)arg2 ;
-(void)invoke:(id)arg1 withTitle:(id)arg2 ;
-(void)setCancellable:(BOOL)arg1 ;
-(void)cancel;
-(void)dealloc;
-(void)setTitle:(id)arg1 ;
-(void)viewWillAppear:(char)arg1 ;
-(void)close;
-(void)webView:(id)arg1 didClearWindowObject:(id)arg2 forFrame:(id)arg3 ;
-(id)leftButton;
-(id)rightButton;
-(void)updateProgress;
@end

