/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, December 27, 2016 at 5:08:14 PM Japan Standard Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /Applications/Cydia.app/Cydia
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Cydia/Cydia-Structs.h>
#import <Cydia/FilteredPackageListController.h>
#import <UIKit/UISearchBarDelegate.h>

@interface SearchController : FilteredPackageListController <UISearchBarDelegate> {

	MenesObjectHandle<UISearchBar, 1> search_;
	char searchloaded_;
	BOOL summary_;

}
-(id)navigationURL;
-(BOOL)isSummarized;
-(void)didSelectPackage:(id)arg1 ;
-(BOOL)shouldYield;
-(BOOL)shouldBlock;
-(BOOL)showsSections;
-(id)termsForQuery:(id)arg1 ;
-(void)usePrefix:(id)arg1 ;
-(void)useSearch;
-(void)searchBarButtonClicked:(id)arg1 ;
-(void)reloadData;
-(void)viewDidAppear:(char)arg1 ;
-(void)searchBar:(id)arg1 textDidChange:(id)arg2 ;
-(void)searchBarCancelButtonClicked:(id)arg1 ;
-(void)searchBarTextDidBeginEditing:(id)arg1 ;
-(void)searchBarSearchButtonClicked:(id)arg1 ;
-(id)referrerURL;
-(id)initWithDatabase:(id)arg1 query:(id)arg2 ;
@end

