/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, December 27, 2016 at 5:08:14 PM Japan Standard Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /Applications/Cydia.app/Cydia
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <Cydia/Cydia-Structs.h>
@interface Section : NSObject {

	MenesObjectHandle<NSString, 0> name_;
	unsigned long row_;
	unsigned long count_;
	MenesObjectHandle<NSString, 0> localized_;

}
-(id)localized;
-(id)initWithName:(id)arg1 localize:(char)arg2 ;
-(id)initWithName:(id)arg1 row:(unsigned long)arg2 localize:(char)arg3 ;
-(int)compareByLocalized:(id)arg1 ;
-(id)initWithName:(id)arg1 localized:(id)arg2 ;
-(void)addToRow;
-(void)addToCount;
-(unsigned long)count;
-(unsigned long)row;
-(void)setName:(id)arg1 ;
-(id)name;
-(void)setCount:(unsigned long)arg1 ;
@end

