/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, December 27, 2016 at 5:08:14 PM Japan Standard Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /Applications/Cydia.app/Cydia
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Cydia/Cydia-Structs.h>
#import <Cydia/CyteViewController.h>

@interface StashController : CyteViewController {

	MenesObjectHandle<UIActivityIndicatorView, 0> spinner_;
	MenesObjectHandle<UILabel, 0> status_;
	MenesObjectHandle<UILabel, 0> caption_;

}
-(void)releaseSubviews;
-(void)loadView;
@end

